# 分析模块应用配置
spring:
  application:
    name: law-firm-analysis
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:local}
    # 引入数据分析模块特定配置
    include: analysis

# 服务器配置
server:
  servlet:
    # 上下文路径
    context-path: ${ANALYSIS_CONTEXT_PATH:/api/analysis}

# 数据分析配置
analysis:
  # 数据源配置
  datasource:
    enabled: ${ANALYSIS_DATASOURCE_ENABLED:true}
    mysql:
      enabled: ${ANALYSIS_DATASOURCE_MYSQL_ENABLED:true}
    redis:
      enabled: ${ANALYSIS_DATASOURCE_REDIS_ENABLED:true}
    elasticsearch:
      enabled: ${ANALYSIS_DATASOURCE_ES_ENABLED:true}
  
  # 分析指标配置
  metrics:
    enabled: ${ANALYSIS_METRICS_ENABLED:true}
  
  # 报表配置
  report:
    enabled: ${ANALYSIS_REPORT_ENABLED:true}
    storage:
      type: ${ANALYSIS_REPORT_STORAGE_TYPE:minio}
      path: ${ANALYSIS_REPORT_STORAGE_PATH:./reports}
    retention-days: ${ANALYSIS_REPORT_RETENTION_DAYS:365}
  
  # 可视化配置
  visualization:
    enabled: ${ANALYSIS_VISUALIZATION_ENABLED:true}
    export:
      enabled: ${ANALYSIS_VISUALIZATION_EXPORT_ENABLED:true}
  
  # 搜索配置
  search:
    enabled: ${ANALYSIS_SEARCH_ENABLED:true}
    type: ${ANALYSIS_SEARCH_TYPE:lucene}
    lucene:
      index-path: ${ANALYSIS_LUCENE_INDEX_PATH:./lucene/analysis}
      analyzer: standard
      max-results: ${ANALYSIS_SEARCH_MAX_RESULTS:1000}
      commit-interval: ${ANALYSIS_SEARCH_COMMIT_INTERVAL:1000}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm.analysis: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/analysis.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 