# 案件管理模块基础配置
spring:
  application:
    name: law-firm-case
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入案件管理模块特定配置
    include: case

# 服务器配置
server:
  # 服务端口
  port: ${CASE_SERVER_PORT:8095}
  servlet:
    # 上下文路径
    context-path: ${CASE_CONTEXT_PATH:/api/case}

# 日志配置
logging:
  level:
    # 案件模块日志级别
    com.lawfirm.case: ${CASE_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO 