# 存储服务配置
storage:
  # 默认存储类型
  default-type: LOCAL
  # 默认存储桶ID
  default-bucket-id: 1
  
  # 路径配置
  path:
    # 本地存储根路径
    base-dir: /data/files
    # 临时目录
    temp-dir: /data/temp
    # URL前缀
    url-prefix: http://localhost:8080/api/files
    
  # 上传配置
  upload:
    # 最大文件大小 (100MB)
    max-size: 104857600
    # 分片大小 (5MB)
    chunk-size: 5242880
    # 允许的文件类型 (全部允许使用*)
    allowed-types: '*'
    # 禁止的文件类型
    denied-types: exe,bat,sh,dll
    
  # 本地存储配置
  local:
    enabled: true
    base-path: /data/files
    url-prefix: http://localhost:8080/api/files
    
  # MinIO配置
  minio:
    enabled: true
    endpoint: http://minio.example.com
    port: 9000
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    use-ssl: false
    
  # 阿里云OSS配置
  aliyun-oss:
    enabled: false
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key: ${ALIYUN_ACCESS_KEY:}
    secret-key: ${ALIYUN_SECRET_KEY:}
    
  # 腾讯云COS配置
  tencent-cos:
    enabled: false
    region: ap-beijing
    app-id: ${TENCENT_APP_ID:}
    secret-id: ${TENCENT_SECRET_ID:}
    secret-key: ${TENCENT_SECRET_KEY:}

# 日志配置
logging:
  level:
    com.lawfirm.core.storage: INFO
    io.minio: WARN

# 文件上传配置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      location: ${storage.path.temp-dir}

# 缓存配置
cache:
  # 文件缓存配置
  file:
    # 缓存名称
    name: fileCache
    # 最大缓存条目
    max-entries: 1000
    # 缓存过期时间(秒)
    ttl: 1800
    # 空闲时间(秒)
    idle-time: 300

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs/storage
  swagger-ui:
    path: /swagger-ui/storage
  group-configs:
    - group: storage
      paths-to-match: /api/storage/**
      packages-to-scan: com.lawfirm.core.storage 