# 冲突检查模块应用配置
spring:
  # 激活冲突检查模块配置文件
  profiles:
    active: conflict
    
  # Flyway配置
  flyway:
    enabled: true
    # 迁移脚本路径
    locations: classpath:db/migration
    # 表名
    table: flyway_conflict_schema_history
    # 迁移SQL脚本文件名前缀
    sql-migration-prefix: V
    # SQL脚本文件名分隔符
    sql-migration-separator: __
    # SQL脚本文件名后缀
    sql-migration-suffixes: .sql
    # 脚本编码
    encoding: UTF-8
    # 是否基线迁移
    baseline-on-migrate: true
    # 基线版本号
    baseline-version: 1.0.0
    # 基线描述
    baseline-description: Conflict Module Baseline
    # 是否校验
    validate-on-migrate: true
    # 迁移时是否校验
    out-of-order: false 