spring:
  datasource:
    # 使用Hikari连接池
    hikari:
      pool-name: ConflictHikariPool
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    # 数据源配置 - 使用动态数据源
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:law_firm_db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:root}
  # 配置Flyway数据库迁移
  flyway:
    enabled: true
    # 迁移脚本位置
    locations: classpath:db/migration
    # 版本表名称
    table: conflict_schema_history
    # 是否基线化
    baseline-on-migrate: true
    # 基线版本
    baseline-version: 0
    # 验证迁移脚本
    validate-on-migrate: true
    # 迁移时是否校验
    out-of-order: false
    # 前缀
    sql-migration-prefix: V
    # 分隔符
    sql-migration-separator: __
    # 后缀
    sql-migration-suffixes: .sql
  # SQL脚本执行配置  
  sql:
    init:
      mode: never
      continue-on-error: true

mybatis-plus:
  type-aliases-package: com.lawfirm.conflict.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      
# 冲突检查配置
conflict:
  # 冲突检查启用标志
  check-enabled: true
  # 强制冲突检查阻止
  force-block: true
  # 冲突白名单检查
  whitelist-enabled: true
  # 冲突审批流程配置
  approval:
    # 是否启用审批
    enabled: true
    # 默认审批角色
    default-approver-role: ROLE_PARTNER
    # 审批截止时间(小时)
    approval-deadline-hours: 48
  # 缓存配置
  cache:
    enabled: true
    expire-time: 1800
  # 最大检查历史记录保留数量
  max-history-records: 100
  # 检查超时时间(秒)
  check-timeout: 60
  # 默认检查规则配置
  default-rules:
    - CLIENT_OPPOSITE_INTEREST
    - CASE_SUBJECT_CONFLICT
  # 异步检查线程池配置
  thread-pool:
    core-size: 5
    max-size: 10
    queue-capacity: 100
    keep-alive: 60
  # 配置不同业务场景使用的检查规则组
  rule-groups:
    # 客户准入场景
    client-admission:
      - CLIENT_OPPOSITE_INTEREST
      - CLIENT_COURT_AVOIDANCE
      - CLIENT_CONFLICT_PARTY
      - CLIENT_GOV_CONFLICT
    # 案件承办场景  
    case-handling:
      - CASE_SUBJECT_CONFLICT
      - CASE_OPPOSITE_PARTY
      - CASE_RELATED_CONFLICT
      - CASE_LAWYER_CONFLICT
    # 律师变更场景
    lawyer-change:
      - CASE_LAWYER_CONFLICT

# Knife4j接口文档配置
knife4j:
  enable: true
  openapi:
    title: 冲突检查模块API文档
    description: 律师事务所冲突检查模块接口文档
    version: 1.0.0
    group:
      conflict:
        group-name: 冲突检查模块
        api-rule: package
        api-rule-resources:
          - com.lawfirm.conflict.controller
          
# 日志配置          
logging:
  level:
    root: info
    com.lawfirm.conflict: debug 