version: '3.8'

services:
  # 应用服务
  law-firm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-firm-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 环境配置
      - SPRING_PROFILES_ACTIVE=docker
      # 数据库配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/law_firm?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-lawfirm_default}
      # Redis配置
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      # Flyway配置
      - FLYWAY_ENABLED=true
      # 禁用工作流
      - FLOWABLE_ENABLED=false
      - LAWFIRM_WORKFLOW_ENABLED=false
      # 系统功能开关
      - ELASTICSEARCH_ENABLED=false
      - LAWFIRM_SEARCH_ENABLED=true
      - LAWFIRM_SEARCH_TYPE=lucene
      - LAWFIRM_STORAGE_ENABLED=true
      - LAWFIRM_STORAGE_PATH=/app/storage
      - LAWFIRM_STORAGE_TEMP_PATH=/app/storage/temp
      - LAWFIRM_STORAGE_LOCAL_PATH=/app/storage
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage
    networks:
      - law-firm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: law-firm-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-lawfirm_default}
      - MYSQL_DATABASE=law_firm
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      # 初始化脚本(如果存在)
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    networks:
      - law-firm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD:-lawfirm_default}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis缓存
  redis:
    image: redis:7.0
    container_name: law-firm-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - law-firm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

# 网络
networks:
  law-firm-network:
    driver: bridge 