version: '3.8'

services:
  # 应用服务
  law-firm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-firm-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/law_firm?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Zjy-1314
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - ELASTICSEARCH_ENABLED=false
    depends_on:
      - mysql
      - redis
    volumes:
      - law-firm-logs:/app/logs
    networks:
      - law-firm-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: law-firm-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Zjy-1314
      - MYSQL_DATABASE=law_firm
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - law-firm-network

  # Redis缓存
  redis:
    image: redis:7.0
    container_name: law-firm-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - law-firm-network

# 数据卷
volumes:
  mysql-data:
  redis-data:
  law-firm-logs:

# 网络
networks:
  law-firm-network:
    driver: bridge 