-- 创建合同基本信息表
CREATE TABLE IF NOT EXISTS contract_info (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  contract_number varchar(50) NOT NULL COMMENT '合同编号',
  contract_name varchar(100) NOT NULL COMMENT '合同名称',
  contract_type varchar(50) NOT NULL COMMENT '合同类型',
  contract_amount decimal(15,2) DEFAULT NULL COMMENT '合同金额',
  contract_status varchar(20) NOT NULL COMMENT '合同状态',
  case_id bigint DEFAULT NULL COMMENT '关联案件ID',
  client_id bigint DEFAULT NULL COMMENT '关联客户ID',
  client_name varchar(100) DEFAULT NULL COMMENT '客户名称',
  opposing_party varchar(100) DEFAULT NULL COMMENT '对方当事人',
  start_date date DEFAULT NULL COMMENT '合同开始日期',
  end_date date DEFAULT NULL COMMENT '合同结束日期',
  sign_date date DEFAULT NULL COMMENT '签订日期',
  sign_place varchar(100) DEFAULT NULL COMMENT '签订地点',
  payment_type varchar(50) DEFAULT NULL COMMENT '付款方式',
  lawyer_id bigint DEFAULT NULL COMMENT '负责律师ID',
  lawyer_name varchar(50) DEFAULT NULL COMMENT '负责律师姓名',
  department_id bigint DEFAULT NULL COMMENT '部门ID',
  department_name varchar(50) DEFAULT NULL COMMENT '部门名称',
  description varchar(500) DEFAULT NULL COMMENT '合同描述',
  confidentiality_level varchar(20) DEFAULT 'NORMAL' COMMENT '保密级别(PUBLIC,NORMAL,SECRET,TOP_SECRET)',
  is_electronic tinyint(1) DEFAULT '0' COMMENT '是否电子合同',
  has_attachment tinyint(1) DEFAULT '0' COMMENT '是否有附件',
  review_status varchar(20) DEFAULT NULL COMMENT '审核状态',
  reviewer_id bigint DEFAULT NULL COMMENT '审核人ID',
  review_time datetime DEFAULT NULL COMMENT '审核时间',
  review_opinion varchar(500) DEFAULT NULL COMMENT '审核意见',
  has_template tinyint(1) DEFAULT '0' COMMENT '是否基于模板',
  template_id bigint DEFAULT NULL COMMENT '模板ID',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  last_reminder_time datetime DEFAULT NULL COMMENT '最近提醒时间',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_number (contract_number, tenant_id, deleted),
  KEY idx_client_id (client_id),
  KEY idx_case_id (case_id),
  KEY idx_lawyer_id (lawyer_id),
  KEY idx_contract_status (contract_status),
  KEY idx_sign_date (sign_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同信息表';

-- 创建合同条款表
CREATE TABLE IF NOT EXISTS contract_clause (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  contract_id bigint NOT NULL COMMENT '合同ID',
  clause_title varchar(100) NOT NULL COMMENT '条款标题',
  clause_content text NOT NULL COMMENT '条款内容',
  clause_type varchar(50) DEFAULT NULL COMMENT '条款类型',
  clause_order int DEFAULT NULL COMMENT '条款顺序',
  is_important tinyint(1) DEFAULT '0' COMMENT '是否重要条款',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同条款表';

-- 创建合同附件表
CREATE TABLE IF NOT EXISTS contract_attachment (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  contract_id bigint NOT NULL COMMENT '合同ID',
  attachment_name varchar(100) NOT NULL COMMENT '附件名称',
  attachment_type varchar(50) DEFAULT NULL COMMENT '附件类型',
  file_path varchar(255) NOT NULL COMMENT '文件路径',
  file_size bigint DEFAULT NULL COMMENT '文件大小(字节)',
  file_format varchar(20) DEFAULT NULL COMMENT '文件格式',
  upload_time datetime DEFAULT NULL COMMENT '上传时间',
  uploader_id bigint DEFAULT NULL COMMENT '上传人ID',
  description varchar(500) DEFAULT NULL COMMENT '附件描述',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同附件表'; 