server:
  port: 8085

spring:
  application:
    name: law-firm-contract
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm_contract?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  # Flyway配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history_contract

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lawfirm.contract.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 合同模块自定义配置
contract:
  # 合同编号生成规则
  number:
    prefix: "CT"
    date-format: "yyyyMMdd"
    sequence-length: 4
    pattern: "${prefix}-${date}-${sequence}"
  
  # 合同模板配置
  template:
    storage-path: ${user.home}/.law-firm/contract-templates
    default-format: docx
    variables-pattern: "${variable}"
  
  # 合同审批配置
  approval:
    enabled: true
    levels: 2
    auto-notify: true
    notify-channels: system,email
  
  # 合同归档配置
  archive:
    auto-archive: true
    archive-delay-days: 30
    require-signature: true
    require-attachment: false
  
  # 合同提醒配置
  reminder:
    enabled: true
    expire-days-before: 30,15,7,3,1
    renew-days-before: 60,30,15
    scheduler-cron: "0 0 8 * * ?" 