# 合同管理模块基础配置
spring:
  application:
    name: law-firm-contract
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入合同管理模块特定配置
    include: contract

# 服务器配置
server:
  # 服务端口
  port: ${CONTRACT_SERVER_PORT:8096}
  servlet:
    # 上下文路径
    context-path: ${CONTRACT_CONTEXT_PATH:/api/contract}

# 日志配置
logging:
  level:
    # 合同模块日志级别
    com.lawfirm.contract: ${CONTRACT_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO 