# 合同管理模块基础配置
spring:
  application:
    name: law-firm-contract
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:local}
    # 引入合同管理模块特定配置
    include: contract

# 服务器配置
server:
  servlet:
    # 上下文路径
    context-path: ${CONTRACT_CONTEXT_PATH:/api/contract}

# 合同管理配置
contract:
  # 审批流程配置
  approval:
    enabled: ${CONTRACT_APPROVAL_ENABLED:true}
    timeout: ${CONTRACT_APPROVAL_TIMEOUT:72h}
    reminder:
      enabled: ${CONTRACT_APPROVAL_REMINDER_ENABLED:true}
      interval: ${CONTRACT_APPROVAL_REMINDER_INTERVAL:24h}
      max-reminders: ${CONTRACT_APPROVAL_REMINDER_MAX:3}
  
  # 合同提醒配置
  reminder:
    enabled: ${CONTRACT_REMINDER_ENABLED:true}
    intervals:
      - 30d
      - 15d
      - 7d
      - 1d
  
  # 合同模板配置
  template:
    enabled: ${CONTRACT_TEMPLATE_ENABLED:true}
    storage:
      type: ${CONTRACT_TEMPLATE_STORAGE_TYPE:minio}
      path: ${CONTRACT_TEMPLATE_STORAGE_PATH:./templates/contract}
  
  # 合同搜索配置
  search:
    enabled: ${CONTRACT_SEARCH_ENABLED:true}
    type: ${CONTRACT_SEARCH_TYPE:lucene}
    lucene:
      index-path: ${CONTRACT_LUCENE_INDEX_PATH:./lucene/contracts}
      analyzer: standard
      max-results: ${CONTRACT_SEARCH_MAX_RESULTS:1000}
      commit-interval: ${CONTRACT_SEARCH_COMMIT_INTERVAL:1000}
  
  # 合同统计配置
  statistics:
    enabled: ${CONTRACT_STATISTICS_ENABLED:true}
    retention-days: ${CONTRACT_STATISTICS_RETENTION_DAYS:365}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm.contract: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/contract.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 