-- Core-Workflow模块表结构初始化
-- 版本: V0075
-- 模块: core-workflow
-- 创建时间: 2023-07-01
-- 说明: 创建工作流相关表，基于workflow-model模块中的实体类定义

-- 设置字符集和数据库选项
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- wf_process_template表（流程模板表）
CREATE TABLE IF NOT EXISTS wf_process_template (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  template_key VARCHAR(100) NOT NULL COMMENT '流程模板标识',
  template_name VARCHAR(100) NOT NULL COMMENT '流程模板名称',
  template_category VARCHAR(50) COMMENT '流程模板分类',
  business_type VARCHAR(50) COMMENT '业务类型',
  template_version VARCHAR(20) COMMENT '模板版本号',
  process_definition_id VARCHAR(100) COMMENT '流程定义ID',
  deployment_id VARCHAR(100) COMMENT '流程部署ID',
  description VARCHAR(255) COMMENT '流程模板描述',
  suspended BOOLEAN DEFAULT FALSE COMMENT '是否挂起',
  creator_name VARCHAR(100) COMMENT '创建人名称',
  updater_name VARCHAR(100) COMMENT '更新人名称',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_template_key_version (template_key, template_version),
  KEY idx_business_type (business_type),
  KEY idx_template_category (template_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程模板表';

-- workflow_process表（流程实例表）
CREATE TABLE IF NOT EXISTS workflow_process (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  process_no VARCHAR(50) NOT NULL COMMENT '流程编号',
  process_name VARCHAR(100) NOT NULL COMMENT '流程名称',
  process_type INTEGER NOT NULL COMMENT '流程类型',
  status INTEGER DEFAULT 0 COMMENT '流程状态',
  description VARCHAR(255) COMMENT '流程描述',
  business_id BIGINT COMMENT '业务ID',
  business_type VARCHAR(50) COMMENT '业务类型',
  initiator_id BIGINT COMMENT '发起人ID',
  initiator_name VARCHAR(100) COMMENT '发起人名称',
  start_time DATETIME COMMENT '发起时间',
  end_time DATETIME COMMENT '结束时间',
  current_handler_id BIGINT COMMENT '当前处理人ID',
  current_handler_name VARCHAR(100) COMMENT '当前处理人名称',
  priority INTEGER DEFAULT 2 COMMENT '优先级 1-低 2-中 3-高',
  allow_revoke INTEGER DEFAULT 1 COMMENT '是否允许撤回 0-不允许 1-允许',
  allow_transfer INTEGER DEFAULT 1 COMMENT '是否允许转办 0-不允许 1-允许',
  process_config TEXT COMMENT '流程配置（JSON格式）',
  process_instance_id VARCHAR(100) COMMENT 'Flowable流程实例ID',
  process_definition_id VARCHAR(100) COMMENT '流程定义ID',
  process_definition_key VARCHAR(100) COMMENT '流程定义Key',
  process_definition_name VARCHAR(100) COMMENT '流程定义名称',
  process_definition_version INTEGER COMMENT '流程定义版本',
  deployment_id VARCHAR(100) COMMENT '部署ID',
  business_key VARCHAR(100) COMMENT '业务键',
  category VARCHAR(50) COMMENT '流程分类',
  tags VARCHAR(255) COMMENT '流程标签',
  template_id BIGINT COMMENT '流程模板ID',
  template_version VARCHAR(20) COMMENT '流程模板版本',
  variables TEXT COMMENT '流程变量（JSON格式）',
  form_data TEXT COMMENT '流程表单（JSON格式）',
  attachment_ids VARCHAR(255) COMMENT '流程附件IDs',
  notes TEXT COMMENT '流程备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_process_no (process_no),
  UNIQUE KEY uk_process_instance_id (process_instance_id),
  KEY idx_business_id_type (business_id, business_type),
  KEY idx_initiator_id (initiator_id),
  KEY idx_current_handler_id (current_handler_id),
  KEY idx_status (status),
  KEY idx_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例表';

-- workflow_task表（流程任务表）
CREATE TABLE IF NOT EXISTS workflow_task (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  task_no VARCHAR(50) NOT NULL COMMENT '任务编号',
  task_name VARCHAR(100) NOT NULL COMMENT '任务名称',
  task_type INTEGER NOT NULL COMMENT '任务类型',
  process_id BIGINT NOT NULL COMMENT '流程ID',
  process_no VARCHAR(50) NOT NULL COMMENT '流程实例编号',
  description VARCHAR(255) COMMENT '任务描述',
  handler_id BIGINT COMMENT '处理人ID',
  handler_name VARCHAR(100) COMMENT '处理人名称',
  handler_type INTEGER DEFAULT 1 COMMENT '处理人类型 1-用户 2-角色 3-部门',
  start_time DATETIME COMMENT '开始时间',
  end_time DATETIME COMMENT '结束时间',
  due_time DATETIME COMMENT '截止时间',
  status INTEGER DEFAULT 0 COMMENT '任务状态 0-未开始 1-进行中 2-已完成 3-已取消',
  result VARCHAR(100) COMMENT '任务结果',
  comment TEXT COMMENT '任务评论',
  priority INTEGER DEFAULT 2 COMMENT '优先级 1-低 2-中 3-高',
  prev_task_ids VARCHAR(255) COMMENT '前置任务IDs',
  next_task_ids VARCHAR(255) COMMENT '后续任务IDs',
  task_config TEXT COMMENT '任务配置（JSON格式）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_no (task_no),
  KEY idx_process_id (process_id),
  KEY idx_process_no (process_no),
  KEY idx_handler_id (handler_id),
  KEY idx_status (status),
  KEY idx_start_time (start_time),
  KEY idx_due_time (due_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程任务表';

-- wf_task表（任务表）
CREATE TABLE IF NOT EXISTS wf_task (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  task_name VARCHAR(100) NOT NULL COMMENT '任务名称',
  task_type INTEGER NOT NULL COMMENT '任务类型',
  description VARCHAR(255) COMMENT '任务描述',
  process_instance_id VARCHAR(100) NOT NULL COMMENT '流程实例ID',
  handler_id BIGINT COMMENT '处理人ID',
  handler_name VARCHAR(100) COMMENT '处理人名称',
  priority INTEGER DEFAULT 2 COMMENT '优先级',
  due_date DATETIME COMMENT '截止时间',
  status INTEGER DEFAULT 0 COMMENT '任务状态 0-待处理 1-处理中 2-已完成 3-已取消',
  result VARCHAR(100) COMMENT '处理结果',
  comment TEXT COMMENT '处理意见',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_process_instance_id (process_instance_id),
  KEY idx_handler_id (handler_id),
  KEY idx_status (status),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务表';

-- wf_process_permission表（流程权限表）
CREATE TABLE IF NOT EXISTS wf_process_permission (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  process_definition_key VARCHAR(100) NOT NULL COMMENT '流程定义ID或流程定义键',
  permission_type INTEGER NOT NULL COMMENT '权限类型：1-流程定义权限，2-流程实例权限',
  operation_type INTEGER NOT NULL COMMENT '操作类型：1-启动，2-查看，3-处理，4-取消，5-挂起，6-激活',
  target_type INTEGER NOT NULL COMMENT '权限目标类型：1-角色，2-用户，3-部门',
  target_id BIGINT NOT NULL COMMENT '权限目标ID（角色ID、用户ID或部门ID）',
  permission_policy INTEGER DEFAULT 1 COMMENT '权限策略：1-允许，2-拒绝',
  sort_order INTEGER DEFAULT 0 COMMENT '排序号',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_process_target (process_definition_key, permission_type, operation_type, target_type, target_id),
  KEY idx_target_id_type (target_id, target_type),
  KEY idx_process_definition_key (process_definition_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程权限表';

-- wf_process_history表（流程历史表）
CREATE TABLE IF NOT EXISTS wf_process_history (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  process_id BIGINT NOT NULL COMMENT '流程ID',
  process_no VARCHAR(50) NOT NULL COMMENT '流程编号',
  operation_type VARCHAR(50) NOT NULL COMMENT '操作类型：start-启动，complete-完成，cancel-取消，suspend-挂起，activate-激活，transfer-转办',
  operation_time DATETIME NOT NULL COMMENT '操作时间',
  operator_id BIGINT COMMENT '操作人ID',
  operator_name VARCHAR(100) COMMENT '操作人名称',
  task_id BIGINT COMMENT '任务ID',
  task_name VARCHAR(100) COMMENT '任务名称',
  comment TEXT COMMENT '操作评论',
  old_status INTEGER COMMENT '旧状态',
  new_status INTEGER COMMENT '新状态',
  details TEXT COMMENT '操作详情（JSON格式）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  PRIMARY KEY (id),
  KEY idx_process_id (process_id),
  KEY idx_process_no (process_no),
  KEY idx_operation_time (operation_time),
  KEY idx_operator_id (operator_id),
  KEY idx_task_id (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程历史表';

-- wf_process_form表（流程表单表）
CREATE TABLE IF NOT EXISTS wf_process_form (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  form_key VARCHAR(100) NOT NULL COMMENT '表单标识',
  form_name VARCHAR(100) NOT NULL COMMENT '表单名称',
  form_category VARCHAR(50) COMMENT '表单分类',
  form_version VARCHAR(20) COMMENT '表单版本',
  form_type INTEGER DEFAULT 1 COMMENT '表单类型：1-发起表单，2-任务表单',
  form_schema TEXT NOT NULL COMMENT '表单结构（JSON格式）',
  process_key VARCHAR(100) COMMENT '关联流程定义Key',
  task_definition_key VARCHAR(100) COMMENT '关联任务定义Key',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_form_key_version (form_key, form_version),
  KEY idx_process_key (process_key),
  KEY idx_task_definition_key (task_definition_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程表单表';

-- 恢复外键约束
SET FOREIGN_KEY_CHECKS = 1; 