spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

upgrade:
  package:
    path: ${user.home}/law-firm/upgrade-packages  # 升级包存储路径
  backup:
    enabled: true
    path: ${user.home}/law-firm/backup  # 备份文件存储路径 