spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm_workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true
    table: flyway_schema_history

flowable:
  database-schema-update: false
  async-executor-activate: true
  history-level: full
  db-history-used: true
  process:
    definition-cache-limit: 1
  cmmn:
    enabled: false
  dmn:
    enabled: false
  form:
    enabled: false
  idm:
    enabled: false
  content:
    enabled: false
  eventregistry:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /workflow

logging:
  level:
    org.flowable: debug
    com.lawfirm.core.workflow: debug 