# 工作流模块配置

# 工作流特定配置
workflow:
  # 基础配置
  config:
    # 工作流数据源配置，将继承主数据源配置
    datasource:
      schema: law_firm_workflow

# Flowable配置
flowable:
  database-schema-update: false
  async-executor-activate: true
  history-level: full
  db-history-used: true
  process:
    definition-cache-limit: 1
  cmmn:
    enabled: false
  dmn:
    enabled: false
  form:
    enabled: false
  idm:
    enabled: false
  content:
    enabled: false
  eventregistry:
    enabled: false

# 数据库迁移
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true
    table: flyway_schema_history_workflow

# 日志配置
logging:
  level:
    org.flowable: ${LOG_LEVEL_FLOWABLE:info}
    com.lawfirm.core.workflow: ${LOG_LEVEL_WORKFLOW:info}

# 消息队列配置
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: workflow-producer
    send-message-timeout: 3000 