# =============================================
# API文档配置 - 简化版本避免冲突
# =============================================

# Springdoc OpenAPI配置
springdoc:
  # API文档配置
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  # Swagger UI配置
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  # 扫描包配置
  packages-to-scan: com.lawfirm
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Knife4j配置
knife4j:
  enable: true
  production: false
  setting:
    language: zh-CN
    enableDebug: true 