# 生产环境配置

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:law_firm}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME}
    password: ENC(${MYSQL_PASSWORD})
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: LawFirmHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ENC(${REDIS_PASSWORD})
      database: 0
      timeout: 10s
      lettuce:
        pool:
          min-idle: 5
          max-idle: 20
          max-active: 20
          max-wait: -1ms

# JWT配置
jwt:
  secret: ENC(${JWT_SECRET})
  expiration: 86400
  header: Authorization
  token-prefix: Bearer

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lawfirm.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    root: WARN
    com.lawfirm: INFO
  file:
    name: /var/log/law-firm/application.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 60

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never 