# 生产环境配置

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:law_firm}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: LawFirmHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 16
          max-active: 32
          max-wait: -1ms
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  main:
    banner-mode: off

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    
# 日志配置
logging:
  level:
    root: WARN
    com.lawfirm: INFO
  file:
    name: ${LOG_PATH:/var/log/lawfirm}/law-firm.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# JWT配置
jwt:
  secret: ${JWT_SECRET:your-production-secret-key}
  expiration: 43200
  header: Authorization
  token-prefix: Bearer

# Management配置
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never 