# Knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  # 是否生产环境
  production: false
  # 基本认证配置
  basic:
    enable: false
  # 开启Swagger的Basic认证功能，默认为false
  setting:
    # 默认语言
    language: zh-CN
    # 是否显示界面中SwaggerModel功能
    enable-swagger-models: true
    # 是否显示界面中"文档管理"功能
    enable-document-manage: true
    # 是否开启界面中对某一个请求的参数过滤功能
    enable-filter-multipart-apis: false
    # 过滤器名称
    enable-filter-multipart-api-method-type: POST
    # 是否开启请求参数缓存
    enable-request-cache: true
    # 显示Footer
    enable-footer: false
    # 是否开启Host过滤
    enable-host-text: false
    # 是否开启自定义主页内容
    enable-home-custom: true
    # 主页内容Markdown文件路径
    home-custom-path: classpath:static/doc/home.md
    # 是否开启全局搜索框
    enable-search: true
    # 是否开启自定义Footer
    enable-footer-custom: true
    footer-custom-content: Law Firm API文档 | Copyright © 2024
    # 是否开启动态参数调试功能
    enable-dynamic-parameter: true
    # 调试过程中显示verbose
    enable-debug: true
  # 禁用文档加密
  enable-website-encrypt: false
  enable-content-encrypt: false 