# 安全配置
spring:
  security:
    enabled: ${SECURITY_ENABLED:true}
    filter:
      dispatcher-types: REQUEST,FORWARD

# 开发环境安全简化配置  
dev:
  auth:
    simplified-security: ${DEV_SIMPLIFIED_SECURITY:false}
    session-store: ${DEV_SESSION_STORE:redis}
    disable-redis: ${DEV_DISABLE_REDIS:false}
    # 允许的匿名访问路径
    anonymous-urls:
      - "/auth/login"
      - "/auth/register"
      - "/auth/captcha"
      - "/auth/refreshToken"
      - "/doc.html"
      - "/doc.html/**"
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/webjars/**"
      - "/actuator/health"
      - "/error"

# 应用安全设置
auth:
  security:
    enabled: ${AUTH_SECURITY_ENABLED:true}

# 生产环境额外安全设置
prod:
  security:
    # 在生产环境中启用更严格的安全检查
    enhanced-checks: ${PROD_ENHANCED_SECURITY:true}
    # 是否启用审计日志
    audit-logging: ${PROD_AUDIT_LOGGING:true}
    # 敏感操作双重验证
    require-two-factor: ${PROD_TWO_FACTOR:false} 