# 供应模块应用配置
spring:
  application:
    name: law-firm-supplies
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: supplies

# 服务器配置
server:
  port: ${SUPPLIES_SERVER_PORT:8093}
  servlet:
    context-path: ${SUPPLIES_CONTEXT_PATH:/api/supplies}

# 日志配置
logging:
  level:
    com.lawfirm.supplies: ${SUPPLIES_LOG_LEVEL:DEBUG}
    org.springframework: INFO 