CREATE TABLE `conflict` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `conflict_no` varchar(32) NOT NULL COMMENT '冲突编号',
  `conflict_type` tinyint NOT NULL COMMENT '冲突类型（1:当事人冲突、2:案件冲突、3:律师冲突、4:业务冲突）',
  `description` varchar(500) NOT NULL COMMENT '冲突描述',
  `party_a` varchar(50) NOT NULL COMMENT '相关方A',
  `party_b` varchar(50) NOT NULL COMMENT '相关方B',
  `discovery_time` datetime NOT NULL COMMENT '发现时间',
  `status` tinyint NOT NULL COMMENT '状态（1:待处理、2:处理中、3:已解决、4:已驳回）',
  `handler_id` bigint DEFAULT NULL COMMENT '处理人ID',
  `handle_opinion` varchar(500) DEFAULT NULL COMMENT '处理意见',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `risk_level` tinyint NOT NULL DEFAULT '1' COMMENT '风险等级（1:低、2:中、3:高）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建者',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conflict_no` (`conflict_no`),
  KEY `idx_conflict_type` (`conflict_type`),
  KEY `idx_status` (`status`),
  KEY `idx_handler_id` (`handler_id`),
  KEY `idx_discovery_time` (`discovery_time`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='利益冲突表';
