# 印章模块应用配置
spring:
  application:
    name: law-firm-seal
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: seal

# 服务器配置
server:
  port: ${SEAL_SERVER_PORT:8090}
  servlet:
    context-path: ${SEAL_CONTEXT_PATH:/api/seal}

# 日志配置
logging:
  level:
    com.lawfirm.seal: ${SEAL_LOG_LEVEL:DEBUG}
    org.springframework: INFO 