# 印章模块配置
spring:
  # Flyway配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 5000
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history_seal
  
  # 数据源配置继承自主应用

# 印章模块自定义配置
seal:
  # 印章存储配置
  storage:
    path: ${user.home}/.law-firm/seal/images
    temp-path: ${user.home}/.law-firm/seal/temp
    allowed-formats: jpg,png,svg
    max-file-size: 5MB
  
  # 电子签章配置
  esign:
    enabled: true
    cert-path: ${user.home}/.law-firm/seal/certs
    timestamp-server: http://timestamp.digicert.com
    signature-algorithm: SHA256withRSA
  
  # 印章使用记录
  usage-log:
    enabled: true
    retention-days: 365
    record-detail-level: full
  
  # 印章权限
  permission:
    require-approval: true
    multi-level-approval: true
    emergency-use-enabled: true 