-- 文档模块表结构初始化
-- 版本: V5001
-- 模块: document
-- 创建时间: 2023-09-01
-- 说明: 创建文档管理模块相关表结构，基于实体类定义

-- 设置字符集和数据库选项
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- doc_category表（文档分类表）
CREATE TABLE IF NOT EXISTS doc_category (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  category_name VARCHAR(100) NOT NULL COMMENT '分类名称',
  category_code VARCHAR(50) NOT NULL COMMENT '分类编码',
  parent_id BIGINT DEFAULT 0 COMMENT '父级分类ID',
  level INTEGER DEFAULT 1 COMMENT '分类层级',
  sort_no INTEGER DEFAULT 0 COMMENT '排序号',
  description VARCHAR(255) COMMENT '分类描述',
  is_enabled BOOLEAN DEFAULT TRUE COMMENT '是否启用',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_category_code (category_code),
  KEY idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档分类表';

-- doc_tag表（文档标签表）
CREATE TABLE IF NOT EXISTS doc_tag (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  tag_name VARCHAR(50) NOT NULL COMMENT '标签名称',
  tag_code VARCHAR(50) NOT NULL COMMENT '标签编码',
  tag_type VARCHAR(50) COMMENT '标签类型',
  color VARCHAR(20) COMMENT '标签颜色',
  description VARCHAR(255) COMMENT '标签描述',
  is_system BOOLEAN DEFAULT FALSE COMMENT '是否系统标签',
  is_enabled BOOLEAN DEFAULT TRUE COMMENT '是否启用',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tag_code (tag_code),
  KEY idx_tag_type (tag_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档标签表';

-- doc_info表（文档信息表）
CREATE TABLE IF NOT EXISTS doc_info (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  doc_id BIGINT NOT NULL COMMENT '文档ID',
  author VARCHAR(100) COMMENT '作者',
  owner VARCHAR(100) COMMENT '所有者',
  dept_id BIGINT COMMENT '所属部门ID',
  category_id BIGINT COMMENT '文档分类ID',
  tags VARCHAR(500) COMMENT '标签，多个标签用逗号分隔',
  source_path VARCHAR(255) COMMENT '源文件路径',
  language VARCHAR(50) DEFAULT 'zh-CN' COMMENT '文档语言',
  page_count INTEGER COMMENT '页数',
  word_count INTEGER COMMENT '字数',
  last_access_time DATETIME COMMENT '最后访问时间',
  last_modify_time DATETIME COMMENT '最后修改时间',
  source VARCHAR(100) COMMENT '文档来源',
  format VARCHAR(50) COMMENT '文档格式',
  encoding VARCHAR(50) COMMENT '文档编码',
  summary TEXT COMMENT '文档摘要',
  related_docs VARCHAR(500) COMMENT '相关文档ID，多个用逗号分隔',
  reviewer VARCHAR(100) COMMENT '审核人',
  review_time DATETIME COMMENT '审核时间',
  review_comment VARCHAR(500) COMMENT '审核意见',
  attributes TEXT COMMENT '扩展属性（JSON格式）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_doc_id (doc_id),
  KEY idx_category_id (category_id),
  KEY idx_dept_id (dept_id),
  KEY idx_review_time (review_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档信息表';

-- doc_tag_rel表（文档标签关联表）
CREATE TABLE IF NOT EXISTS doc_tag_rel (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  doc_id BIGINT NOT NULL COMMENT '文档ID',
  tag_id BIGINT NOT NULL COMMENT '标签ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uk_doc_tag (doc_id, tag_id),
  KEY idx_doc_id (doc_id),
  KEY idx_tag_id (tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档标签关联表';

-- doc_permission表（文档权限表）
CREATE TABLE IF NOT EXISTS doc_permission (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  document_id BIGINT NOT NULL COMMENT '文档ID',
  subject_type VARCHAR(50) NOT NULL COMMENT '权限主体类型（USER-用户、ROLE-角色、DEPT-部门）',
  subject_id BIGINT NOT NULL COMMENT '权限主体ID',
  permission_type VARCHAR(50) NOT NULL COMMENT '权限类型（READ-读取、WRITE-写入、DELETE-删除等）',
  is_allowed BOOLEAN DEFAULT TRUE COMMENT '是否允许',
  permission_source VARCHAR(50) COMMENT '权限来源（DIRECT-直接授权、INHERIT-继承、SHARE-分享）',
  expire_time DATETIME COMMENT '过期时间',
  is_enabled BOOLEAN DEFAULT TRUE COMMENT '是否启用',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_doc_subject_perm (document_id, subject_type, subject_id, permission_type),
  KEY idx_document_id (document_id),
  KEY idx_subject_id (subject_id),
  KEY idx_permission_type (permission_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档权限表';

-- doc_base表（文档基础表）
CREATE TABLE IF NOT EXISTS doc_base (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  title VARCHAR(200) NOT NULL COMMENT '文档标题',
  doc_type VARCHAR(50) NOT NULL COMMENT '文档类型',
  file_name VARCHAR(200) COMMENT '文件名',
  file_size BIGINT COMMENT '文件大小（字节）',
  file_type VARCHAR(50) COMMENT '文件类型（存储层面）',
  document_format VARCHAR(50) COMMENT '文档格式（业务层面）',
  storage_path VARCHAR(500) COMMENT '存储路径',
  storage_type VARCHAR(50) DEFAULT 'LOCAL' COMMENT '存储类型（LOCAL-本地、OSS-对象存储等）',
  doc_status VARCHAR(50) DEFAULT 'DRAFT' COMMENT '文档状态（DRAFT-草稿、PUBLISHED-已发布等）',
  document_version VARCHAR(50) DEFAULT '1.0' COMMENT '文档版本号',
  keywords VARCHAR(500) COMMENT '关键词',
  description TEXT COMMENT '文档描述',
  is_encrypted BOOLEAN DEFAULT FALSE COMMENT '是否加密',
  access_level VARCHAR(50) DEFAULT 'PRIVATE' COMMENT '访问权限（PUBLIC-公开, PRIVATE-私有, RESTRICTED-受限）',
  download_count BIGINT DEFAULT 0 COMMENT '下载次数',
  view_count BIGINT DEFAULT 0 COMMENT '查看次数',
  business_id BIGINT COMMENT '业务ID',
  business_type VARCHAR(50) COMMENT '业务类型',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_doc_type (doc_type),
  KEY idx_doc_status (doc_status),
  KEY idx_business_id (business_id),
  KEY idx_business_type (business_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档基础表';

-- doc_case表（案件文档表）
CREATE TABLE IF NOT EXISTS doc_case (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  title VARCHAR(200) NOT NULL COMMENT '文档标题',
  doc_type VARCHAR(50) NOT NULL COMMENT '文档类型',
  file_name VARCHAR(200) COMMENT '文件名',
  file_size BIGINT COMMENT '文件大小（字节）',
  file_type VARCHAR(50) COMMENT '文件类型（存储层面）',
  document_format VARCHAR(50) COMMENT '文档格式（业务层面）',
  storage_path VARCHAR(500) COMMENT '存储路径',
  storage_type VARCHAR(50) DEFAULT 'LOCAL' COMMENT '存储类型（LOCAL-本地、OSS-对象存储等）',
  doc_status VARCHAR(50) DEFAULT 'DRAFT' COMMENT '文档状态（DRAFT-草稿、PUBLISHED-已发布等）',
  document_version VARCHAR(50) DEFAULT '1.0' COMMENT '文档版本号',
  keywords VARCHAR(500) COMMENT '关键词',
  description TEXT COMMENT '文档描述',
  is_encrypted BOOLEAN DEFAULT FALSE COMMENT '是否加密',
  access_level VARCHAR(50) DEFAULT 'PRIVATE' COMMENT '访问权限（PUBLIC-公开, PRIVATE-私有, RESTRICTED-受限）',
  download_count BIGINT DEFAULT 0 COMMENT '下载次数',
  view_count BIGINT DEFAULT 0 COMMENT '查看次数',
  business_id BIGINT COMMENT '业务ID',
  business_type VARCHAR(50) COMMENT '业务类型',
  
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_code VARCHAR(50) COMMENT '案件编号',
  doc_stage VARCHAR(50) COMMENT '文档阶段（立案、庭审、结案等）',
  doc_category VARCHAR(50) COMMENT '文档分类（起诉书、判决书、证据等）',
  is_confidential BOOLEAN DEFAULT FALSE COMMENT '是否为机密文件',
  need_signature BOOLEAN DEFAULT FALSE COMMENT '是否需要签名',
  signature_status VARCHAR(50) COMMENT '签名状态',
  submitter VARCHAR(100) COMMENT '文档提交人',
  reviewer VARCHAR(100) COMMENT '文档审核人',
  related_parties VARCHAR(500) COMMENT '相关方（多个用逗号分隔）',
  
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_case_code (case_code),
  KEY idx_doc_stage (doc_stage),
  KEY idx_submitter (submitter)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件文档表';

-- doc_contract表（合同文档表）
CREATE TABLE IF NOT EXISTS doc_contract (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  title VARCHAR(200) NOT NULL COMMENT '文档标题',
  doc_type VARCHAR(50) NOT NULL COMMENT '文档类型',
  file_name VARCHAR(200) COMMENT '文件名',
  file_size BIGINT COMMENT '文件大小（字节）',
  file_type VARCHAR(50) COMMENT '文件类型（存储层面）',
  document_format VARCHAR(50) COMMENT '文档格式（业务层面）',
  storage_path VARCHAR(500) COMMENT '存储路径',
  storage_type VARCHAR(50) DEFAULT 'LOCAL' COMMENT '存储类型（LOCAL-本地、OSS-对象存储等）',
  doc_status VARCHAR(50) DEFAULT 'DRAFT' COMMENT '文档状态（DRAFT-草稿、PUBLISHED-已发布等）',
  document_version VARCHAR(50) DEFAULT '1.0' COMMENT '文档版本号',
  keywords VARCHAR(500) COMMENT '关键词',
  description TEXT COMMENT '文档描述',
  is_encrypted BOOLEAN DEFAULT FALSE COMMENT '是否加密',
  access_level VARCHAR(50) DEFAULT 'PRIVATE' COMMENT '访问权限（PUBLIC-公开, PRIVATE-私有, RESTRICTED-受限）',
  download_count BIGINT DEFAULT 0 COMMENT '下载次数',
  view_count BIGINT DEFAULT 0 COMMENT '查看次数',
  business_id BIGINT COMMENT '业务ID',
  business_type VARCHAR(50) COMMENT '业务类型',
  
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  contract_code VARCHAR(50) COMMENT '合同编号',
  contract_type VARCHAR(50) COMMENT '合同类型',
  contract_status VARCHAR(50) COMMENT '合同状态',
  party_a VARCHAR(100) COMMENT '签约方A',
  party_b VARCHAR(100) COMMENT '签约方B',
  sign_date DATETIME COMMENT '签约日期',
  effective_date DATETIME COMMENT '生效日期',
  expiry_date DATETIME COMMENT '到期日期',
  amount DECIMAL(12,2) COMMENT '合同金额',
  currency VARCHAR(20) DEFAULT 'CNY' COMMENT '币种',
  need_seal BOOLEAN DEFAULT FALSE COMMENT '是否需要盖章',
  seal_status VARCHAR(50) COMMENT '盖章状态',
  workflow_id BIGINT COMMENT '审批流程ID',
  approval_status VARCHAR(50) COMMENT '审批状态',
  
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_contract_code (contract_code),
  KEY idx_contract_type (contract_type),
  KEY idx_contract_status (contract_status),
  KEY idx_effective_date (effective_date),
  KEY idx_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同文档表';

-- doc_article表（知识文章表）
CREATE TABLE IF NOT EXISTS doc_article (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  title VARCHAR(200) NOT NULL COMMENT '文档标题',
  doc_type VARCHAR(50) NOT NULL COMMENT '文档类型',
  file_name VARCHAR(200) COMMENT '文件名',
  file_size BIGINT COMMENT '文件大小（字节）',
  file_type VARCHAR(50) COMMENT '文件类型（存储层面）',
  document_format VARCHAR(50) COMMENT '文档格式（业务层面）',
  storage_path VARCHAR(500) COMMENT '存储路径',
  storage_type VARCHAR(50) DEFAULT 'LOCAL' COMMENT '存储类型（LOCAL-本地、OSS-对象存储等）',
  doc_status VARCHAR(50) DEFAULT 'DRAFT' COMMENT '文档状态（DRAFT-草稿、PUBLISHED-已发布等）',
  document_version VARCHAR(50) DEFAULT '1.0' COMMENT '文档版本号',
  keywords VARCHAR(500) COMMENT '关键词',
  description TEXT COMMENT '文档描述',
  is_encrypted BOOLEAN DEFAULT FALSE COMMENT '是否加密',
  access_level VARCHAR(50) DEFAULT 'PRIVATE' COMMENT '访问权限（PUBLIC-公开, PRIVATE-私有, RESTRICTED-受限）',
  download_count BIGINT DEFAULT 0 COMMENT '下载次数',
  view_count BIGINT DEFAULT 0 COMMENT '查看次数',
  business_id BIGINT COMMENT '业务ID',
  business_type VARCHAR(50) COMMENT '业务类型',
  
  category_id BIGINT COMMENT '文章分类ID',
  article_type VARCHAR(50) COMMENT '文章类型',
  author VARCHAR(100) COMMENT '作者',
  source VARCHAR(100) COMMENT '来源',
  summary TEXT COMMENT '摘要',
  cover_image VARCHAR(500) COMMENT '封面图片',
  read_count BIGINT DEFAULT 0 COMMENT '阅读量',
  like_count BIGINT DEFAULT 0 COMMENT '点赞数',
  favorite_count BIGINT DEFAULT 0 COMMENT '收藏数',
  comment_count BIGINT DEFAULT 0 COMMENT '评论数',
  is_top BOOLEAN DEFAULT FALSE COMMENT '是否置顶',
  is_recommend BOOLEAN DEFAULT FALSE COMMENT '是否推荐',
  is_original BOOLEAN DEFAULT FALSE COMMENT '是否原创',
  review_status VARCHAR(50) COMMENT '审核状态',
  review_comment VARCHAR(500) COMMENT '审核意见',
  
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_category_id (category_id),
  KEY idx_article_type (article_type),
  KEY idx_author (author),
  KEY idx_review_status (review_status),
  KEY idx_is_top (is_top),
  KEY idx_is_recommend (is_recommend)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识文章表';

-- doc_template表（文档模板表）
CREATE TABLE IF NOT EXISTS doc_template (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  title VARCHAR(200) NOT NULL COMMENT '模板标题',
  template_code VARCHAR(50) NOT NULL COMMENT '模板编码',
  doc_type VARCHAR(50) NOT NULL COMMENT '文档类型',
  category_id BIGINT COMMENT '模板分类ID',
  template_type VARCHAR(50) COMMENT '模板类型（WORD/PDF/HTML等）',
  file_name VARCHAR(200) COMMENT '文件名',
  file_size BIGINT COMMENT '文件大小（字节）',
  file_type VARCHAR(50) COMMENT '文件类型',
  storage_path VARCHAR(500) COMMENT '存储路径',
  storage_type VARCHAR(50) DEFAULT 'LOCAL' COMMENT '存储类型（LOCAL-本地、OSS-对象存储等）',
  description TEXT COMMENT '模板描述',
  tags VARCHAR(500) COMMENT '模板标签，多个用逗号分隔',
  variable_fields TEXT COMMENT '变量字段（JSON格式）',
  apply_scope VARCHAR(200) COMMENT '适用范围',
  author VARCHAR(100) COMMENT '作者',
  use_count BIGINT DEFAULT 0 COMMENT '使用次数',
  is_public BOOLEAN DEFAULT FALSE COMMENT '是否公开',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_template_code (template_code),
  KEY idx_category_id (category_id),
  KEY idx_template_type (template_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档模板表';

-- 恢复外键约束
SET FOREIGN_KEY_CHECKS = 1;
