# 认证管理模块基础配置
spring:
  application:
    name: law-firm-auth
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入认证管理模块特定配置
    include: auth

# 服务器配置
server:
  # 服务端口
  port: ${AUTH_SERVER_PORT:8097}
  servlet:
    # 上下文路径
    context-path: ${AUTH_CONTEXT_PATH:/api/auth}

# 日志配置
logging:
  level:
    # 认证模块日志级别
    com.lawfirm.auth: ${AUTH_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO 