spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    locations: classpath:db
    table: flyway_schema_history
    validate-on-migrate: true
    out-of-order: false
    placeholder-replacement: false 