# 资产模块应用配置
spring:
  application:
    name: law-firm-asset
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: asset

# 服务器配置
server:
  port: ${ASSET_SERVER_PORT:8091}
  servlet:
    context-path: ${ASSET_CONTEXT_PATH:/api/asset}

# 日志配置
logging:
  level:
    com.lawfirm.asset: ${ASSET_LOG_LEVEL:DEBUG}
    org.springframework: INFO 