server:
  port: 8081
  servlet:
    context-path: /admin-api

spring:
  application:
    name: admin-api
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

# JWT配置
jwt:
  secret: your-secret-key
  expiration: 86400000  # 24小时

# 文件上传配置
file:
  upload:
    path: /data/upload
    maxSize: 100MB
    allowTypes: .jpg,.jpeg,.png,.doc,.docx,.pdf,.xls,.xlsx

# Swagger配置
swagger:
  enabled: true
  title: 律所管理系统-管理后台API
  description: 系统管理员使用的API接口文档
  version: 1.0.0
  contact:
    name: Admin
    email: admin@lawfirm.com

# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: DEBUG
  file:
    path: /data/logs/admin-api

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lawfirm.**.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
  basic:
    enable: false

# 自定义配置
lawfirm:
  security:
    ignore-urls:
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /v3/api-docs/**
      - /actuator/** 