# 任务模块应用配置
spring:
  application:
    name: law-firm-task
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: task

# 服务器配置
server:
  port: ${TASK_SERVER_PORT:8088}
  servlet:
    context-path: ${TASK_CONTEXT_PATH:/api/task}

# 日志配置
logging:
  level:
    com.lawfirm.task: ${TASK_LOG_LEVEL:DEBUG}
    org.springframework: INFO