# 任务模块应用配置
spring:
  application:
    name: law-firm-task
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: task

# 服务器配置
server:
  servlet:
    context-path: ${TASK_CONTEXT_PATH:/api/task}

# 任务管理配置
task:
  # 任务提醒配置
  reminder:
    enabled: ${TASK_REMINDER_ENABLED:true}
    max-reminders: ${TASK_REMINDER_MAX:3}
  
  # 任务分配配置
  assignment:
    strategy: ${TASK_ASSIGNMENT_STRATEGY:round-robin}
    load-balance: ${TASK_ASSIGNMENT_LOAD_BALANCE:true}
    max-tasks: ${TASK_ASSIGNMENT_MAX_TASKS:10}
    auto-assign: ${TASK_ASSIGNMENT_AUTO:true}
  
  # 任务搜索配置
  search:
    enabled: ${TASK_SEARCH_ENABLED:true}
    type: ${TASK_SEARCH_TYPE:lucene}
    lucene:
      index-path: ${TASK_LUCENE_INDEX_PATH:./lucene/tasks}
      analyzer: standard
      max-results: ${TASK_SEARCH_MAX_RESULTS:1000}
      commit-interval: ${TASK_SEARCH_COMMIT_INTERVAL:1000}
  
  # 任务统计配置
  statistics:
    enabled: ${TASK_STATISTICS_ENABLED:true}
    retention-days: ${TASK_STATISTICS_RETENTION_DAYS:90}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm.task: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/task.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"