# 财务管理模块基础配置
spring:
  application:
    name: law-firm-finance
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入财务管理模块特定配置
    include: finance

# 服务器配置
server:
  # 服务端口
  port: ${FINANCE_SERVER_PORT:8083}
  servlet:
    # 上下文路径
    context-path: ${FINANCE_CONTEXT_PATH:/api/finance}

# 日志配置
logging:
  level:
    # 财务模块日志级别
    com.lawfirm.finance: ${FINANCE_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO