# 财务模块配置
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history_finance
  
  # 数据源配置继承自主应用

# 财务模块自定义配置
finance:
  # 发票配置
  invoice:
    # 发票编号格式
    number-format: "INV-%Y%m%d%H%M%S"
    # 开票信息模板
    template-path: ${user.home}/.law-firm/finance/invoice-templates
    # 是否启用电子发票
    e-invoice-enabled: true
  
  # 收款配置
  payment:
    # 支持的支付方式
    methods: cash,bank_transfer,wechat,alipay
    # 支付超时时间(分钟)
    timeout-minutes: 30
    # 自动发送收款提醒
    auto-reminder: true
    # 提醒事件(逾期前天数)
    reminder-days-before: 7,3,1
    # 定期对账单发送
    statement-sending-enabled: true
  
  # 财务报表配置
  reporting:
    # 报表存储目录
    storage-path: ${user.home}/.law-firm/finance/reports
    # 报表格式
    formats: pdf,excel,csv
    # 自动生成报表
    auto-generate: true
    # 报表生成周期
    generation-cron: "0 0 1 1 * ?" 