# 知识管理模块配置
spring:
  application:
    name: law-firm-knowledge
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入知识库模块特定配置
    include: knowledge
    
  # 数据库配置
  datasource:
    url: ${KNOWLEDGE_DB_URL:jdbc:mysql://localhost:3306/law_firm_knowledge?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${KNOWLEDGE_DB_USERNAME:root}
    password: ${KNOWLEDGE_DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      
  # Flyway数据库迁移配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 8000
    validate-on-migrate: true
    table: flyway_schema_history_knowledge

# 服务器配置
server:
  servlet:
    # 上下文路径
    context-path: ${KNOWLEDGE_CONTEXT_PATH:/api/knowledge}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm.knowledge: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/knowledge.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 知识管理模块业务配置
knowledge:
  # 存储配置
  storage:
    # 基础存储路径
    base-path: ${KNOWLEDGE_STORAGE_PATH:${user.home}/lawfirm/knowledge}
    # 临时文件路径
    temp-path: ${KNOWLEDGE_TEMP_PATH:${user.home}/lawfirm/knowledge/temp}
    
  # 文档配置
  document:
    # 最大文档大小
    max-size: ${KNOWLEDGE_DOC_MAX_SIZE:10MB}
    # 允许的文件扩展名
    allowed-extensions: ${KNOWLEDGE_DOC_EXTENSIONS:.doc,.docx,.pdf,.md,.txt}
    
  # 附件配置
  attachment:
    # 最大附件大小
    max-size: ${KNOWLEDGE_ATTACH_MAX_SIZE:20MB}
    # 每个知识条目最大附件数量
    max-count-per-knowledge: ${KNOWLEDGE_ATTACH_MAX_COUNT:10}
    # 允许的附件扩展名
    allowed-extensions: ${KNOWLEDGE_ATTACH_EXTENSIONS:.doc,.docx,.pdf,.jpg,.png,.zip}
    
  # 分类配置
  category:
    # 分类最大层级深度
    max-depth: ${KNOWLEDGE_CATEGORY_MAX_DEPTH:3}
    
  # 搜索配置
  search:
    # 是否启用高亮显示
    enable-highlight: ${KNOWLEDGE_SEARCH_HIGHLIGHT:true}
    # 最大搜索结果数量
    max-result-count: ${KNOWLEDGE_SEARCH_MAX_RESULTS:1000}
    # 最小关键词长度
    min-keyword-length: ${KNOWLEDGE_SEARCH_MIN_KEYWORD:2}
    # 搜索引擎类型
    type: ${LAWFIRM_SEARCH_TYPE:lucene}
    # Lucene配置
    lucene:
      index-path: ${LAWFIRM_LUCENE_INDEX_PATH:/data/law-firm/lucene}
      analyzer: standard
      commit-interval: 1000
    
  # 权限配置
  permission:
    # 公开分类ID列表
    public-categories: ${KNOWLEDGE_PUBLIC_CATEGORIES:[1, 2, 3]}
    
  # 统计任务配置
  statistic:
    # 统计任务执行时间 - 每天凌晨1点执行
    cron: ${KNOWLEDGE_STATISTIC_CRON:"0 0 1 * * ?"}
    
  # 标签配置
  tags:
    enabled: ${KNOWLEDGE_TAGS_ENABLED:true}
    max-per-article: ${KNOWLEDGE_TAGS_MAX:10}
    popular:
      enabled: ${KNOWLEDGE_TAGS_POPULAR_ENABLED:true}
      threshold: ${KNOWLEDGE_TAGS_POPULAR_THRESHOLD:10}
      update-interval: ${KNOWLEDGE_TAGS_POPULAR_INTERVAL:1d}
  
  # 版本控制配置
  version:
    enabled: ${KNOWLEDGE_VERSION_ENABLED:true}
    max-versions: ${KNOWLEDGE_VERSION_MAX:10}
    auto-clean: ${KNOWLEDGE_VERSION_AUTO_CLEAN:true}
    clean-days: ${KNOWLEDGE_VERSION_CLEAN_DAYS:30}
  
  # 评论配置
  comment:
    enabled: ${KNOWLEDGE_COMMENT_ENABLED:true}
    moderation:
      enabled: ${KNOWLEDGE_COMMENT_MODERATION:true}
    max-length: ${KNOWLEDGE_COMMENT_MAX_LENGTH:1000}
    max-depth: ${KNOWLEDGE_COMMENT_MAX_DEPTH:3}
    
# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lawfirm.model.knowledge.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 存储服务配置
storage:
  # MinIO对象存储配置
  minio:
    enabled: ${KNOWLEDGE_MINIO_ENABLED:true}
    # MinIO服务器地址
    endpoint: ${KNOWLEDGE_MINIO_ENDPOINT:http://minio:9000}
    # 访问密钥
    access-key: ${MINIO_ACCESS_KEY:miniouser}
    # 密钥
    secret-key: ${MINIO_SECRET_KEY:${random.uuid}}
    # 存储桶名称
    bucket: ${KNOWLEDGE_MINIO_BUCKET:knowledge-documents} 