server:
  port: 8083
  servlet:
    context-path: /
    
spring:
  application:
    name: law-firm-knowledge
  profiles:
    active: dev
    include: knowledge
    
# 日志配置
logging:
  level:
    root: info
    com.lawfirm: debug
  file:
    name: ${user.home}/logs/law-firm-knowledge.log
    
# Swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.lawfirm.knowledge.controller 