spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/law_firm_knowledge?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
    
  # Flyway配置
  flyway:
    enabled: true
    clean-disabled: false
    
# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
# 日志配置
logging:
  level:
    com.lawfirm: debug
    org.springframework.web: debug
    
# 知识管理模块配置
knowledge:
  storage:
    base-path: ${user.home}/lawfirm/knowledge
    temp-path: ${user.home}/lawfirm/knowledge/temp 