# 知识管理模块基础配置
spring:
  application:
    name: law-firm-knowledge
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入知识管理模块特定配置
    include: knowledge

# 服务器配置
server:
  # 服务端口
  port: ${KNOWLEDGE_SERVER_PORT:8085}
  servlet:
    # 上下文路径
    context-path: ${KNOWLEDGE_CONTEXT_PATH:/api/knowledge}

# 日志配置
logging:
  level:
    # 知识模块日志级别
    com.lawfirm.knowledge: ${KNOWLEDGE_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO
  file:
    # 日志文件路径
    name: ${KNOWLEDGE_LOG_FILE:${user.home}/logs/law-firm-knowledge.log} 