spring:
  # RabbitMQ配置
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 10000
        # 批量处理配置
        batch-size: 100
        prefetch: 10
        concurrency: 5
        max-concurrency: 10
    publisher-confirm-type: correlated
    publisher-returns: true
    # 消息持久化
    template:
      mandatory: true
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000

  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

# 消息服务配置
message:
  # 阿里云短信配置
  sms:
    access-key-id: ${SMS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${SMS_ACCESS_KEY_SECRET:your-access-key-secret}
    endpoint: dysmsapi.aliyuncs.com
    sign-name: ${SMS_SIGN_NAME:your-sign-name}
  
  # 微信配置
  wechat:
    app-id: ${WECHAT_APP_ID:your-app-id}
    app-secret: ${WECHAT_APP_SECRET:your-app-secret}
    token: ${WECHAT_TOKEN:your-token}
    aes-key: ${WECHAT_AES_KEY:your-aes-key}
  
  # Redis配置
  redis:
    message-key-prefix: message:user:
    subscription-key-prefix: message:subscription:
    message-expire-days: 7

  # 消息处理配置
  processing:
    # 消息幂等性配置
    idempotent:
      enabled: true
      expire-hours: 24
    # 限流配置
    rate-limit:
      enabled: true
      capacity: 1000
      rate: 100
    # 批量处理配置
    batch:
      enabled: true
      max-size: 100
      wait-timeout: 1000

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true 