-- 收费记录表
CREATE TABLE `fee_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `amount` decimal(15,2) NOT NULL COMMENT '收费金额',
  `paid_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '已支付金额',
  `fee_status` varchar(20) NOT NULL COMMENT '收费状态（UNPAID:未支付、PAID:已支付、PARTIAL:部分支付、REFUNDED:已退款）',
  `fee_type` varchar(20) NOT NULL COMMENT '收费类型（CASE:案件收费、CONSULTATION:咨询收费、OTHER:其他收费）',
  `case_id` bigint DEFAULT NULL COMMENT '关联案件ID',
  `client_id` bigint NOT NULL COMMENT '关联客户ID',
  `law_firm_id` bigint NOT NULL COMMENT '关联律所ID',
  `payment_time` datetime DEFAULT NULL COMMENT '支付时间',
  `payment_method` varchar(20) DEFAULT NULL COMMENT '支付方式',
  `description` varchar(500) DEFAULT NULL COMMENT '收费说明',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建者',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (`id`),
  KEY `idx_case_id` (`case_id`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_law_firm_id` (`law_firm_id`),
  KEY `idx_fee_status` (`fee_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='收费记录表';

-- 支出记录表
CREATE TABLE `expense_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `amount` decimal(15,2) NOT NULL COMMENT '支出金额',
  `expense_status` varchar(20) NOT NULL COMMENT '支出状态（PENDING:待审批、APPROVED:已审批、REJECTED:已驳回、PAID:已支付）',
  `expense_type` varchar(20) NOT NULL COMMENT '支出类型（OPERATION:日常运营、SALARY:人员工资、EQUIPMENT:办公设备、OTHER:其他支出）',
  `law_firm_id` bigint NOT NULL COMMENT '关联律所ID',
  `department_id` bigint DEFAULT NULL COMMENT '关联部门ID',
  `applicant_id` bigint NOT NULL COMMENT '申请人ID',
  `approver_id` bigint DEFAULT NULL COMMENT '审批人ID',
  `expense_time` datetime DEFAULT NULL COMMENT '支出时间',
  `payment_method` varchar(20) DEFAULT NULL COMMENT '支付方式',
  `description` varchar(500) DEFAULT NULL COMMENT '支出说明',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建者',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (`id`),
  KEY `idx_law_firm_id` (`law_firm_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_applicant_id` (`applicant_id`),
  KEY `idx_expense_status` (`expense_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支出记录表';

-- 发票表
CREATE TABLE `fin_invoice` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` varchar(100) NOT NULL COMMENT '发票抬头',
  `type` tinyint NOT NULL COMMENT '发票类型（1:增值税普通发票、2:增值税专用发票）',
  `amount` decimal(15,2) NOT NULL COMMENT '发票金额',
  `tax_rate` decimal(5,2) NOT NULL COMMENT '税率',
  `tax_amount` decimal(15,2) NOT NULL COMMENT '税额',
  `issue_date` datetime NOT NULL COMMENT '开票日期',
  `invoice_no` varchar(50) NOT NULL COMMENT '发票号码',
  `matter_id` bigint DEFAULT NULL COMMENT '关联事项ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1:正常、2:作废）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_no` (`invoice_no`),
  KEY `idx_matter_id` (`matter_id`),
  KEY `idx_issue_date` (`issue_date`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='发票表'; 