# 人事管理模块基础配置
spring:
  application:
    name: law-firm-personnel
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入人事管理模块特定配置
    include: personnel

# 服务器配置
server:
  # 服务端口
  port: ${PERSONNEL_SERVER_PORT:8082}
  servlet:
    # 上下文路径
    context-path: ${PERSONNEL_CONTEXT_PATH:/api/personnel}

# 日志配置
logging:
  level:
    # 人事模块日志级别
    com.lawfirm.personnel: ${PERSONNEL_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO