# 人事管理模块基础配置
spring:
  application:
    name: law-firm-personnel
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:local}
    # 引入人事管理模块特定配置
    include: personnel

# 服务器配置
server:
  servlet:
    # 上下文路径
    context-path: ${PERSONNEL_CONTEXT_PATH:/api/personnel}

# 人事管理配置
personnel:
  # 考勤配置
  attendance:
    enabled: ${ATTENDANCE_ENABLED:true}
    work-time:
      start: ${ATTENDANCE_WORK_START:09:00}
      end: ${ATTENDANCE_WORK_END:18:00}
    overtime:
      enabled: ${ATTENDANCE_OVERTIME_ENABLED:true}
      rate: ${ATTENDANCE_OVERTIME_RATE:1.5}
    leave:
      max-days:
        annual: ${ATTENDANCE_LEAVE_MAX_ANNUAL:15}
        sick: ${ATTENDANCE_LEAVE_MAX_SICK:30}
        personal: ${ATTENDANCE_LEAVE_MAX_PERSONAL:5}
  
  # 绩效配置
  performance:
    enabled: ${PERFORMANCE_ENABLED:true}
  
  # 培训配置
  training:
    enabled: ${TRAINING_ENABLED:true}
    evaluation:
      enabled: ${TRAINING_EVALUATION_ENABLED:true}
      required: ${TRAINING_EVALUATION_REQUIRED:true}
  
  # 薪资配置
  salary:
    enabled: ${SALARY_ENABLED:true}
    payment:
      method: ${SALARY_PAYMENT_METHOD:BANK_TRANSFER}
      day: ${SALARY_PAYMENT_DAY:15}
    tax:
      enabled: ${SALARY_TAX_ENABLED:true}
      rate: ${SALARY_TAX_RATE:0.2}
  
  # 搜索配置
  search:
    enabled: ${PERSONNEL_SEARCH_ENABLED:true}
    type: ${PERSONNEL_SEARCH_TYPE:lucene}
    lucene:
      index-path: ${PERSONNEL_LUCENE_INDEX_PATH:./lucene/personnel}
      analyzer: standard
      max-results: ${PERSONNEL_SEARCH_MAX_RESULTS:1000}
      commit-interval: ${PERSONNEL_SEARCH_COMMIT_INTERVAL:1000}
  
  # 统计配置
  statistics:
    enabled: ${PERSONNEL_STATISTICS_ENABLED:true}
    retention-days: ${PERSONNEL_STATISTICS_RETENTION_DAYS:365}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm.personnel: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/personnel.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"