# 日程模块应用配置
spring:
  application:
    name: law-firm-schedule
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: schedule

# 服务器配置
server:
  port: ${SCHEDULE_SERVER_PORT:8092}
  servlet:
    context-path: ${SCHEDULE_CONTEXT_PATH:/api/schedule}

# 日志配置
logging:
  level:
    com.lawfirm.schedule: ${SCHEDULE_LOG_LEVEL:DEBUG}
    org.springframework: INFO 