# 日程模块应用配置
spring:
  application:
    name: law-firm-schedule
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:local}
    # 引入日程管理模块特定配置
    include: schedule

# 服务器配置
server:
  servlet:
    # 上下文路径
    context-path: ${SCHEDULE_CONTEXT_PATH:/api/schedule}

# 日程管理配置
schedule:
  # 日程提醒配置
  reminder:
    enabled: ${SCHEDULE_REMINDER_ENABLED:true}
    max-reminders: ${SCHEDULE_REMINDER_MAX:3}
  
  # 重复规则配置
  recurrence:
    enabled: ${SCHEDULE_RECURRENCE_ENABLED:true}
    max-occurrences: ${SCHEDULE_RECURRENCE_MAX:365}
    end-date: ${SCHEDULE_RECURRENCE_END_DATE:2099-12-31}
  
  # 日程共享配置
  sharing:
    enabled: ${SCHEDULE_SHARING_ENABLED:true}
    default-level: ${SCHEDULE_SHARING_DEFAULT:PRIVATE}
  
  # 冲突检查配置
  conflict:
    enabled: ${SCHEDULE_CONFLICT_ENABLED:true}
    check-interval: ${SCHEDULE_CONFLICT_CHECK_INTERVAL:15m}
    buffer-time: ${SCHEDULE_CONFLICT_BUFFER_TIME:30m}
    auto-resolve: ${SCHEDULE_CONFLICT_AUTO_RESOLVE:false}
  
  # 日程搜索配置
  search:
    enabled: ${SCHEDULE_SEARCH_ENABLED:true}
    type: ${SCHEDULE_SEARCH_TYPE:lucene}
    lucene:
      index-path: ${SCHEDULE_LUCENE_INDEX_PATH:./lucene/schedules}
      analyzer: standard
      max-results: ${SCHEDULE_SEARCH_MAX_RESULTS:1000}
      commit-interval: ${SCHEDULE_SEARCH_COMMIT_INTERVAL:1000}
  
  # 日程统计配置
  statistics:
    enabled: ${SCHEDULE_STATISTICS_ENABLED:true}
    retention-days: ${SCHEDULE_STATISTICS_RETENTION_DAYS:90}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm.schedule: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/schedule.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"