# 客户管理模块基础配置
spring:
  application:
    name: law-firm-client
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入客户管理模块特定配置
    include: client

# 服务器配置
server:
  # 服务端口
  port: ${CLIENT_SERVER_PORT:8086}
  servlet:
    # 上下文路径
    context-path: ${CLIENT_CONTEXT_PATH:/api/client}

# 日志配置
logging:
  level:
    # 客户模块日志级别
    com.lawfirm.client: ${CLIENT_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO