-- 合同模块表结构初始化
-- 版本: V6001
-- 模块: contract
-- 创建时间: 2023-10-01
-- 说明: 创建合同管理模块相关表结构，基于实体类定义

-- 设置字符集和数据库选项
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- contract_info表（合同基本信息表）
CREATE TABLE IF NOT EXISTS contract_info (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_no VARCHAR(50) NOT NULL COMMENT '合同编号',
  contract_name VARCHAR(200) NOT NULL COMMENT '合同名称',
  contract_type VARCHAR(50) COMMENT '合同类型',
  status INTEGER DEFAULT 0 COMMENT '合同状态',
  amount DOUBLE COMMENT '合同基础金额',
  signing_date DATE COMMENT '签约日期',
  client_id BIGINT COMMENT '客户ID',
  case_id BIGINT COMMENT '关联案件ID',
  effective_date DATE COMMENT '生效日期',
  expiry_date DATE COMMENT '到期日期',
  service_scope TEXT COMMENT '服务范围',
  delegate_power VARCHAR(100) COMMENT '授权范围',
  fee_type VARCHAR(50) COMMENT '收费类型',
  payment_terms VARCHAR(500) COMMENT '付款条件',
  lead_attorney_id BIGINT COMMENT '主办律师ID',
  department_id BIGINT COMMENT '承办部门ID',
  contract_text TEXT COMMENT '合同正文内容',
  confidentiality_level INTEGER COMMENT '保密级别',
  remarks VARCHAR(500) COMMENT '备注说明',
  template_id BIGINT COMMENT '合同模板ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_no (contract_no),
  KEY idx_contract_name (contract_name),
  KEY idx_contract_type (contract_type),
  KEY idx_status (status),
  KEY idx_client_id (client_id),
  KEY idx_case_id (case_id),
  KEY idx_signing_date (signing_date),
  KEY idx_effective_date (effective_date),
  KEY idx_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同基本信息表';

-- contract_attachment表（合同附件表）
CREATE TABLE IF NOT EXISTS contract_attachment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  file_name VARCHAR(200) NOT NULL COMMENT '附件文件名',
  file_path VARCHAR(500) COMMENT '附件路径',
  file_type VARCHAR(50) COMMENT '附件类型',
  file_size BIGINT COMMENT '附件大小（字节）',
  upload_time DATETIME COMMENT '上传时间',
  uploader_id BIGINT COMMENT '上传人ID',
  description VARCHAR(500) COMMENT '附件描述',
  confidentiality_level INTEGER COMMENT '保密级别',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_file_type (file_type),
  KEY idx_uploader_id (uploader_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同附件表';

-- contract_team表（合同团队表）
CREATE TABLE IF NOT EXISTS contract_team (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '关联的合同ID',
  attorney_id BIGINT NOT NULL COMMENT '律师ID',
  role_type VARCHAR(50) NOT NULL COMMENT '角色类型',
  responsibility VARCHAR(500) COMMENT '负责内容描述',
  join_date DATE COMMENT '加入团队日期',
  status INTEGER DEFAULT 1 COMMENT '状态(1-活跃, 0-已退出)',
  billable_hours DOUBLE COMMENT '计费小时数',
  hourly_rate DOUBLE COMMENT '小时费率',
  workload_percent INTEGER COMMENT '工作量占比(百分比)',
  remarks VARCHAR(500) COMMENT '备注说明',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_attorney_id (attorney_id),
  KEY idx_role_type (role_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同团队表';

-- contract_clause表（合同条款表）
CREATE TABLE IF NOT EXISTS contract_clause (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  clause_content TEXT NOT NULL COMMENT '条款内容',
  clause_type VARCHAR(50) COMMENT '条款类型',
  sort_order INTEGER DEFAULT 0 COMMENT '排序号',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_clause_type (clause_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同条款表';

-- contract_fee表（合同费用表）
CREATE TABLE IF NOT EXISTS contract_fee (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  fee_type VARCHAR(50) COMMENT '收费类型',
  fee_name VARCHAR(100) NOT NULL COMMENT '费用名称',
  fee_amount DECIMAL(12,2) NOT NULL COMMENT '费用金额',
  currency VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
  rate DOUBLE COMMENT '费率(适用于风险代理类型)',
  calculation_method VARCHAR(255) COMMENT '计算方式说明',
  due_date DATE COMMENT '应付日期',
  payment_status INTEGER DEFAULT 0 COMMENT '支付状态（0-未支付，1-部分支付，2-已支付）',
  paid_amount DOUBLE DEFAULT 0 COMMENT '已支付金额',
  is_taxable BOOLEAN DEFAULT FALSE COMMENT '是否含税',
  tax_rate DOUBLE COMMENT '税率',
  condition_desc VARCHAR(500) COMMENT '收费条件说明',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  case_id BIGINT COMMENT '案件ID',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_fee_type (fee_type),
  KEY idx_payment_status (payment_status),
  KEY idx_due_date (due_date),
  KEY idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同费用表';

-- contract_review表（合同审核表）
CREATE TABLE IF NOT EXISTS contract_review (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  review_type VARCHAR(50) NOT NULL COMMENT '审核类型',
  review_status INTEGER DEFAULT 0 COMMENT '审核状态（0-待审核 1-审核通过 2-审核拒绝）',
  review_opinion TEXT COMMENT '审核意见',
  reviewer_id BIGINT COMMENT '审核人ID',
  review_time DATETIME COMMENT '审核时间',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_review_type (review_type),
  KEY idx_review_status (review_status),
  KEY idx_reviewer_id (reviewer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同审核表';

-- contract_approval表（合同审批表）
CREATE TABLE IF NOT EXISTS contract_approval (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  approval_node VARCHAR(50) COMMENT '审批节点',
  approval_status INTEGER DEFAULT 0 COMMENT '审批状态（0-待审批 1-审批通过 2-审批拒绝）',
  approval_opinion TEXT COMMENT '审批意见',
  approver_id BIGINT COMMENT '审批人ID',
  approval_time DATETIME COMMENT '审批时间',
  process_instance_id VARCHAR(64) COMMENT '流程实例ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_approval_status (approval_status),
  KEY idx_approver_id (approver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同审批表';

-- contract_milestone表（合同里程碑表）
CREATE TABLE IF NOT EXISTS contract_milestone (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  milestone_name VARCHAR(100) NOT NULL COMMENT '里程碑名称',
  description VARCHAR(500) COMMENT '里程碑描述',
  plan_date DATE COMMENT '计划完成日期',
  actual_date DATE COMMENT '实际完成日期',
  status INTEGER DEFAULT 0 COMMENT '状态(0-未开始，1-进行中，2-已完成，3-已延期)',
  completion_percent INTEGER DEFAULT 0 COMMENT '完成百分比',
  responsible_id BIGINT COMMENT '负责人ID',
  linked_fee_id BIGINT COMMENT '关联的收费项ID',
  is_key_point BOOLEAN DEFAULT FALSE COMMENT '是否重要节点',
  is_reminder_sent BOOLEAN DEFAULT FALSE COMMENT '是否已发送提醒',
  reminder_days INTEGER COMMENT '提前提醒天数',
  sequence INTEGER COMMENT '序列号，用于排序',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_status (status),
  KEY idx_plan_date (plan_date),
  KEY idx_actual_date (actual_date),
  KEY idx_responsible_id (responsible_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同里程碑表';

-- contract_template表（合同模板表）
CREATE TABLE IF NOT EXISTS contract_template (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  template_name VARCHAR(100) NOT NULL COMMENT '模板名称',
  template_code VARCHAR(50) COMMENT '模板编码',
  template_type VARCHAR(50) COMMENT '模板类型',
  content TEXT COMMENT '模板内容',
  status INTEGER DEFAULT 0 COMMENT '状态(0-禁用，1-启用)',
  template_version VARCHAR(20) COMMENT '模板版本号',
  is_default BOOLEAN DEFAULT FALSE COMMENT '是否默认模板',
  category VARCHAR(50) COMMENT '分类',
  department_id BIGINT COMMENT '所属部门ID',
  creator_id BIGINT COMMENT '创建人ID',
  reviewer_id BIGINT COMMENT '审核人ID',
  variables TEXT COMMENT '变量列表，JSON格式',
  description VARCHAR(500) COMMENT '模板描述',
  usage_count INTEGER DEFAULT 0 COMMENT '使用次数',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_template_code (template_code),
  KEY idx_template_name (template_name),
  KEY idx_template_type (template_type),
  KEY idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同模板表';

-- contract_change表（合同变更表）
CREATE TABLE IF NOT EXISTS contract_change (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  change_type VARCHAR(50) NOT NULL COMMENT '变更类型',
  change_content TEXT NOT NULL COMMENT '变更内容',
  change_reason VARCHAR(500) COMMENT '变更原因',
  change_date DATE COMMENT '变更日期',
  change_status INTEGER DEFAULT 0 COMMENT '变更状态（0-待审批 1-已通过 2-已拒绝）',
  approver_id BIGINT COMMENT '审批人ID',
  approval_time DATETIME COMMENT '审批时间',
  approval_opinion VARCHAR(500) COMMENT '审批意见',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_change_type (change_type),
  KEY idx_change_status (change_status),
  KEY idx_change_date (change_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同变更表';

-- contract_conflict表（合同冲突检查表）
CREATE TABLE IF NOT EXISTS contract_conflict (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  check_status INTEGER DEFAULT 0 COMMENT '检查状态',
  check_time DATETIME COMMENT '检查时间',
  checker_id BIGINT COMMENT '检查人ID',
  conflict_type VARCHAR(50) COMMENT '冲突类型',
  conflict_level INTEGER COMMENT '冲突级别',
  conflict_desc VARCHAR(255) COMMENT '冲突描述',
  conflict_details TEXT COMMENT '冲突详情',
  related_contract_id BIGINT COMMENT '关联合同ID',
  related_client_id BIGINT COMMENT '关联客户ID',
  related_lawyer_id BIGINT COMMENT '关联律师ID',
  related_case_id BIGINT COMMENT '关联案件ID',
  resolution TEXT COMMENT '解决方案',
  is_resolved BOOLEAN DEFAULT FALSE COMMENT '是否已解决',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_contract_id (contract_id),
  KEY idx_check_status (check_status),
  KEY idx_conflict_type (conflict_type),
  KEY idx_conflict_level (conflict_level),
  KEY idx_related_contract_id (related_contract_id),
  KEY idx_related_client_id (related_client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同冲突检查表';

-- 恢复外键约束
SET FOREIGN_KEY_CHECKS = 1;
