-- 创建系统管理模块基础表

-- 创建系统用户表
CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  password VARCHAR(100) NOT NULL COMMENT '密码',
  real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  avatar_url VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0-否，1-是',
  tenant_id BIGINT(20) NOT NULL DEFAULT 0 COMMENT '租户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by BIGINT(20) DEFAULT NULL COMMENT '创建人ID',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by BIGINT(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (id),
  UNIQUE KEY uk_username (username),
  KEY idx_phone (phone),
  KEY idx_email (email),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

-- 创建系统配置表
CREATE TABLE IF NOT EXISTS sys_config (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  config_key VARCHAR(50) NOT NULL COMMENT '配置键',
  config_value VARCHAR(500) NOT NULL COMMENT '配置值',
  category VARCHAR(50) DEFAULT NULL COMMENT '配置分类',
  description VARCHAR(200) DEFAULT NULL COMMENT '配置描述',
  is_system TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否系统配置：0-否，1-是',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0-否，1-是',
  tenant_id BIGINT(20) NOT NULL DEFAULT 0 COMMENT '租户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by BIGINT(20) DEFAULT NULL COMMENT '创建人ID',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by BIGINT(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (id),
  UNIQUE KEY uk_config_key (config_key, tenant_id),
  KEY idx_category (category),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置表';

-- 创建数据字典表
CREATE TABLE IF NOT EXISTS sys_dict (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  dict_code VARCHAR(50) NOT NULL COMMENT '字典编码',
  dict_name VARCHAR(50) NOT NULL COMMENT '字典名称',
  description VARCHAR(200) DEFAULT NULL COMMENT '字典描述',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0-否，1-是',
  tenant_id BIGINT(20) NOT NULL DEFAULT 0 COMMENT '租户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by BIGINT(20) DEFAULT NULL COMMENT '创建人ID',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by BIGINT(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (id),
  UNIQUE KEY uk_dict_code (dict_code),
  KEY idx_dict_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据字典表';

-- 创建数据字典项表
CREATE TABLE IF NOT EXISTS sys_dict_item (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  dict_id BIGINT(20) NOT NULL COMMENT '字典ID',
  item_name VARCHAR(50) NOT NULL COMMENT '字典项名称',
  item_value VARCHAR(50) NOT NULL COMMENT '字典项值',
  description VARCHAR(200) DEFAULT NULL COMMENT '字典项描述',
  sort INT(11) NOT NULL DEFAULT 0 COMMENT '排序号',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0-否，1-是',
  tenant_id BIGINT(20) NOT NULL DEFAULT 0 COMMENT '租户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by BIGINT(20) DEFAULT NULL COMMENT '创建人ID',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by BIGINT(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (id),
  KEY idx_dict_item_dict_id (dict_id),
  KEY idx_dict_item_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据字典项表';

-- 创建系统日志表
CREATE TABLE IF NOT EXISTS sys_log (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
  operation VARCHAR(50) NOT NULL COMMENT '操作',
  method VARCHAR(200) DEFAULT NULL COMMENT '方法名',
  params TEXT DEFAULT NULL COMMENT '请求参数',
  time BIGINT(20) NOT NULL DEFAULT 0 COMMENT '执行时长(毫秒)',
  ip VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
  location VARCHAR(100) DEFAULT NULL COMMENT '操作地点',
  browser VARCHAR(100) DEFAULT NULL COMMENT '浏览器',
  os VARCHAR(100) DEFAULT NULL COMMENT '操作系统',
  status TINYINT(4) NOT NULL DEFAULT 0 COMMENT '状态：0-成功，1-失败',
  error_msg TEXT DEFAULT NULL COMMENT '错误消息',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0-否，1-是',
  tenant_id BIGINT(20) NOT NULL DEFAULT 0 COMMENT '租户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_log_user_id (user_id),
  KEY idx_log_status (status),
  KEY idx_log_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统日志表'; 