-- 创建客户模块基础表

-- 创建客户信息表
CREATE TABLE IF NOT EXISTS `client_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `client_no` varchar(50) NOT NULL COMMENT '客户编号',
  `name` varchar(100) NOT NULL COMMENT '客户名称',
  `type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '客户类型：1-个人客户，2-企业客户，3-政府机构，0-其他',
  `source` tinyint(4) DEFAULT NULL COMMENT '客户来源：1-直接咨询，2-老客户介绍，3-合作伙伴介绍，4-广告宣传，5-活动营销，0-其他',
  `industry` varchar(50) DEFAULT NULL COMMENT '所属行业',
  `level` tinyint(4) DEFAULT '1' COMMENT '客户等级：1-普通客户，2-重要客户，3-核心客户，4-VIP客户',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1-潜在客户，2-意向客户，3-成交客户，4-流失客户，5-黑名单客户',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '主要联系人姓名',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '主要联系人电话',
  `contact_email` varchar(100) DEFAULT NULL COMMENT '主要联系人邮箱',
  `address` varchar(200) DEFAULT NULL COMMENT '地址',
  `region` varchar(50) DEFAULT NULL COMMENT '所在区域',
  `legal_representative` varchar(50) DEFAULT NULL COMMENT '法定代表人（企业客户）',
  `business_license` varchar(50) DEFAULT NULL COMMENT '营业执照号（企业客户）',
  `registered_capital` decimal(16,2) DEFAULT NULL COMMENT '注册资本（企业客户）',
  `unified_social_credit_code` varchar(50) DEFAULT NULL COMMENT '统一社会信用代码（企业客户）',
  `establish_date` date DEFAULT NULL COMMENT '成立日期（企业客户）',
  `id_type` tinyint(4) DEFAULT NULL COMMENT '证件类型（个人客户）：1-身份证，2-护照，3-军官证，4-港澳通行证，5-台湾通行证，0-其他',
  `id_number` varchar(50) DEFAULT NULL COMMENT '证件号码（个人客户）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `follow_up_status` tinyint(4) DEFAULT '1' COMMENT '跟进状态：1-未跟进，2-跟进中，3-已跟进，4-已成交，5-已流失',
  `last_follow_up_time` datetime DEFAULT NULL COMMENT '最近跟进时间',
  `next_follow_up_time` datetime DEFAULT NULL COMMENT '下次跟进时间',
  `follow_up_times` int(11) DEFAULT '0' COMMENT '跟进次数',
  `responsible_lawyer_id` bigint(20) DEFAULT NULL COMMENT '负责律师ID',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_no` (`client_no`),
  KEY `idx_client_name` (`name`),
  KEY `idx_client_type` (`type`),
  KEY `idx_client_status` (`status`),
  KEY `idx_client_contact_phone` (`contact_phone`),
  KEY `idx_client_responsible_lawyer_id` (`responsible_lawyer_id`),
  KEY `idx_client_follow_up_status` (`follow_up_status`),
  KEY `idx_client_id_number` (`id_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户信息表';

-- 创建客户联系人表
CREATE TABLE IF NOT EXISTS `client_contact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `client_id` bigint(20) NOT NULL COMMENT '客户ID',
  `name` varchar(50) NOT NULL COMMENT '联系人姓名',
  `gender` tinyint(4) DEFAULT NULL COMMENT '性别：1-男，2-女，0-未知',
  `position` varchar(50) DEFAULT NULL COMMENT '职位',
  `department` varchar(50) DEFAULT NULL COMMENT '部门',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) DEFAULT NULL COMMENT '电子邮箱',
  `is_primary` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否主要联系人：0-否，1-是',
  `is_decision_maker` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否决策者：0-否，1-是',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  KEY `idx_contact_client_id` (`client_id`),
  KEY `idx_contact_name` (`name`),
  KEY `idx_contact_phone` (`phone`),
  KEY `idx_contact_is_primary` (`is_primary`),
  KEY `idx_contact_is_decision_maker` (`is_decision_maker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户联系人表';

-- 创建客户跟进记录表
CREATE TABLE IF NOT EXISTS `client_follow_up` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `client_id` bigint(20) NOT NULL COMMENT '客户ID',
  `follow_up_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '跟进方式：1-电话跟进，2-邮件跟进，3-会议跟进，4-拜访跟进，5-其他',
  `follow_up_time` datetime NOT NULL COMMENT '跟进时间',
  `content` text NOT NULL COMMENT '跟进内容',
  `next_follow_up_time` datetime DEFAULT NULL COMMENT '下次跟进时间',
  `next_plan` varchar(500) DEFAULT NULL COMMENT '下次计划',
  `follow_up_result` tinyint(4) DEFAULT NULL COMMENT '跟进结果：1-意向增强，2-意向不变，3-意向减弱，4-成交，5-无法接通，6-无意向',
  `follow_up_by` bigint(20) NOT NULL COMMENT '跟进人ID',
  `follow_up_by_name` varchar(50) DEFAULT NULL COMMENT '跟进人姓名',
  `contact_id` bigint(20) DEFAULT NULL COMMENT '联系人ID',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '联系人姓名',
  `attachment_url` varchar(255) DEFAULT NULL COMMENT '附件URL',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  KEY `idx_follow_up_client_id` (`client_id`),
  KEY `idx_follow_up_type` (`follow_up_type`),
  KEY `idx_follow_up_time` (`follow_up_time`),
  KEY `idx_follow_up_by` (`follow_up_by`),
  KEY `idx_follow_up_result` (`follow_up_result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户跟进记录表'; 