# 归档模块应用配置
spring:
  application:
    name: law-firm-archive
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: archive

# 服务器配置
server:
  servlet:
    context-path: ${ARCHIVE_CONTEXT_PATH:/api/archive}

# 日志配置
logging:
  level:
    com.lawfirm.archive: ${ARCHIVE_LOG_LEVEL:DEBUG}
    org.springframework: INFO