-- Personnel模块表结构初始化
-- 版本: V3001
-- 模块: personnel
-- 创建时间: 2023-07-01
-- 说明: 创建人事模块相关表结构

-- 设置字符集和数据库选项
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ======================= Organization模块表结构 =======================

-- org_department表（部门表）
CREATE TABLE IF NOT EXISTS org_department (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  name VARCHAR(100) NOT NULL COMMENT '部门名称',
  code VARCHAR(50) NOT NULL COMMENT '部门编码',
  parent_id BIGINT DEFAULT 0 COMMENT '父部门ID',
  ancestors VARCHAR(500) DEFAULT '' COMMENT '祖级列表',
  type INTEGER COMMENT '部门类型',
  firm_id BIGINT COMMENT '所属律所ID',
  manager_id BIGINT COMMENT '负责人ID',
  manager_name VARCHAR(50) COMMENT '负责人姓名',
  phone VARCHAR(20) COMMENT '联系电话',
  email VARCHAR(100) COMMENT '联系邮箱',
  function_desc VARCHAR(500) COMMENT '职能描述',
  office_location VARCHAR(200) COMMENT '办公地点',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_department_code (code),
  KEY idx_department_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门表';

-- org_position表（职位表）
CREATE TABLE IF NOT EXISTS org_position (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  code VARCHAR(32) NOT NULL COMMENT '职位编码',
  name VARCHAR(64) NOT NULL COMMENT '职位名称',
  type INTEGER NOT NULL COMMENT '职位类型',
  level INTEGER COMMENT '职位等级',
  department_id BIGINT NOT NULL COMMENT '所属部门ID',
  description VARCHAR(500) COMMENT '职位描述',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_position_code (code),
  KEY idx_position_name (name),
  KEY idx_position_department (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='职位表';

-- org_team表（团队表）
CREATE TABLE IF NOT EXISTS org_team (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  name VARCHAR(100) NOT NULL COMMENT '团队名称',
  parent_id BIGINT DEFAULT 0 COMMENT '父团队ID',
  ancestors VARCHAR(500) DEFAULT '' COMMENT '祖级列表',
  firm_id BIGINT COMMENT '所属律所ID',
  department_id BIGINT COMMENT '所属部门ID',
  type INTEGER COMMENT '团队类型',
  team_code VARCHAR(50) COMMENT '团队编码',
  leader_id BIGINT COMMENT '负责人ID',
  leader_name VARCHAR(32) COMMENT '负责人姓名',
  phone VARCHAR(20) COMMENT '联系电话',
  email VARCHAR(100) COMMENT '联系邮箱',
  team_size INTEGER DEFAULT 0 COMMENT '团队规模（人数）',
  responsibility VARCHAR(500) COMMENT '团队职责',
  team_status INTEGER DEFAULT 1 COMMENT '团队状态（0-筹备中 1-运行中 2-已解散）',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_team_code (team_code),
  KEY idx_team_department (department_id),
  KEY idx_team_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='团队表';

-- org_project_group表（项目组表）
CREATE TABLE IF NOT EXISTS org_project_group (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  name VARCHAR(100) NOT NULL COMMENT '项目组名称',
  code VARCHAR(50) NOT NULL COMMENT '项目组编码',
  team_id BIGINT COMMENT '所属团队ID',
  project_id BIGINT COMMENT '关联项目ID',
  case_id BIGINT COMMENT '关联案件ID',
  leader_id BIGINT COMMENT '负责人ID',
  leader_name VARCHAR(32) COMMENT '负责人姓名',
  member_count INTEGER DEFAULT 0 COMMENT '成员数量',
  start_date DATE COMMENT '开始日期',
  end_date DATE COMMENT '结束日期',
  status INTEGER DEFAULT 1 COMMENT '状态（0-筹备 1-进行中 2-已结束）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_project_group_code (code),
  KEY idx_project_group_team (team_id),
  KEY idx_project_group_project (project_id),
  KEY idx_project_group_case (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目组表';

-- ======================= Personnel模块表结构 =======================

-- per_person表（人员基本信息表）
CREATE TABLE IF NOT EXISTS per_person (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  person_code VARCHAR(32) NOT NULL COMMENT '人员编号',
  name VARCHAR(64) NOT NULL COMMENT '姓名',
  english_name VARCHAR(64) COMMENT '英文名',
  gender INTEGER DEFAULT 0 COMMENT '性别（0-未知 1-男 2-女）',
  birth_date DATE COMMENT '出生日期',
  id_type INTEGER DEFAULT 1 COMMENT '证件类型（1-身份证 2-护照 3-其他）',
  id_number VARCHAR(50) COMMENT '证件号码',
  mobile VARCHAR(20) COMMENT '手机号码',
  email VARCHAR(100) COMMENT '电子邮箱',
  type VARCHAR(20) COMMENT '人员类型',
  firm_id BIGINT COMMENT '所属律所ID',
  emergency_contact VARCHAR(32) COMMENT '紧急联系人',
  emergency_mobile VARCHAR(20) COMMENT '紧急联系人电话',
  photo_url VARCHAR(255) COMMENT '照片URL',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_person_code (person_code),
  KEY idx_name (name),
  KEY idx_id_number (id_number),
  KEY idx_mobile (mobile),
  KEY idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人员基本信息表';

-- per_employee表（员工信息表）
CREATE TABLE IF NOT EXISTS per_employee (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  person_id BIGINT NOT NULL COMMENT '关联的人员ID',
  work_number VARCHAR(32) NOT NULL COMMENT '工号',
  user_id BIGINT COMMENT '关联的用户ID（auth模块）',
  employee_status INTEGER DEFAULT 1 COMMENT '员工状态（1-在职 2-离职 3-试用期 4-休假 5-停职）',
  employee_type INTEGER DEFAULT 1 COMMENT '员工类型（1-律师 2-行政人员 3-实习生 4-顾问 99-其他）',
  department_id BIGINT COMMENT '所属部门ID',
  position_id BIGINT COMMENT '职位ID',
  entry_date DATE COMMENT '入职日期',
  regular_date DATE COMMENT '转正日期',
  resign_date DATE COMMENT '离职日期',
  work_email VARCHAR(100) COMMENT '工作邮箱',
  work_phone VARCHAR(20) COMMENT '工作电话',
  office_location VARCHAR(100) COMMENT '办公地点',
  supervisor_id BIGINT COMMENT '直属上级ID',
  work_years INTEGER COMMENT '工作年限',
  education INTEGER COMMENT '学历（1-专科 2-本科 3-硕士 4-博士 5-其他）',
  graduate_school VARCHAR(100) COMMENT '毕业院校',
  major VARCHAR(100) COMMENT '专业',
  graduate_year INTEGER COMMENT '毕业年份',
  contract_status INTEGER DEFAULT 0 COMMENT '合同状态（0-未签 1-已签 2-过期 3-终止）',
  current_contract_id BIGINT COMMENT '当前合同ID',
  
  -- 律师特有属性
  license_number VARCHAR(50) COMMENT '律师执业证号（仅当employeeType=LAWYER时有效）',
  license_issue_date DATE COMMENT '执业证颁发日期',
  license_expire_date DATE COMMENT '执业证过期日期',
  practice_years INTEGER COMMENT '执业年限',
  lawyer_level INTEGER COMMENT '律师职级',
  practice_areas VARCHAR(500) COMMENT '执业领域，逗号分隔',
  expertise VARCHAR(500) COMMENT '专长领域',
  profile TEXT COMMENT '律师简介',
  achievements TEXT COMMENT '律师成就',
  team_id BIGINT COMMENT '所属团队ID',
  mentor_id BIGINT COMMENT '导师ID',
  is_partner BOOLEAN DEFAULT FALSE COMMENT '是否合伙人',
  partner_date DATE COMMENT '成为合伙人日期',
  equity_ratio DECIMAL(10,4) COMMENT '股权比例',
  
  -- 行政人员特有属性
  function_type INTEGER COMMENT '职能类型',
  function_desc VARCHAR(200) COMMENT '职能描述',
  job_duties TEXT COMMENT '工作职责',
  service_scope VARCHAR(500) COMMENT '服务范围',
  skill_certificates VARCHAR(500) COMMENT '技能证书',
  center_type INTEGER COMMENT '中心类型',
  has_other_functions BOOLEAN DEFAULT FALSE COMMENT '是否有其他职能',
  other_functions VARCHAR(500) COMMENT '其他职能',
  resign_reason VARCHAR(500) COMMENT '离职原因',
  
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_work_number (work_number),
  UNIQUE KEY uk_user_id (user_id),
  KEY idx_person_id (person_id),
  KEY idx_employee_department_id (department_id),
  KEY idx_employee_position_id (position_id),
  KEY idx_license_number (license_number),
  KEY idx_employee_type (employee_type),
  KEY idx_employee_status (employee_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工信息表';

-- per_contact表（联系方式表）
CREATE TABLE IF NOT EXISTS per_contact (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  person_id BIGINT NOT NULL COMMENT '人员ID',
  type INTEGER DEFAULT 1 COMMENT '联系类型（1-个人 2-工作 3-其他）',
  mobile VARCHAR(20) COMMENT '手机号码',
  phone VARCHAR(20) COMMENT '电话号码',
  email VARCHAR(100) COMMENT '电子邮箱',
  wechat VARCHAR(100) COMMENT '微信号',
  qq VARCHAR(20) COMMENT 'QQ号',
  country VARCHAR(50) DEFAULT '中国' COMMENT '国家',
  province VARCHAR(50) COMMENT '省份',
  city VARCHAR(50) COMMENT '城市',
  district VARCHAR(50) COMMENT '区县',
  address VARCHAR(256) COMMENT '详细地址',
  postal_code VARCHAR(20) COMMENT '邮政编码',
  is_default BOOLEAN DEFAULT FALSE COMMENT '是否默认联系方式',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_person_id (person_id),
  KEY idx_contact_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='联系方式表';

-- per_contract表（人事合同表）
CREATE TABLE IF NOT EXISTS per_contract (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  person_id BIGINT NOT NULL COMMENT '人员ID',
  contract_number VARCHAR(50) NOT NULL COMMENT '合同编号',
  type INTEGER DEFAULT 1 COMMENT '合同类型（1-劳动合同 2-服务合同 3-保密协议 4-竞业限制协议）',
  name VARCHAR(100) NOT NULL COMMENT '合同名称',
  start_date DATE NOT NULL COMMENT '合同开始日期',
  end_date DATE COMMENT '合同结束日期',
  duration INTEGER COMMENT '合同期限（月）',
  probation_period INTEGER COMMENT '试用期（月）',
  base_salary DECIMAL(12,2) COMMENT '基本工资',
  position_salary DECIMAL(12,2) COMMENT '岗位工资',
  performance_salary DECIMAL(12,2) COMMENT '绩效工资',
  confidentiality_agreement TEXT COMMENT '保密协议',
  non_compete TEXT COMMENT '竞业限制',
  sign_date DATE COMMENT '签订日期',
  sign_location VARCHAR(100) COMMENT '签订地点',
  company_signer VARCHAR(50) COMMENT '公司签订人',
  status INTEGER DEFAULT 1 COMMENT '合同状态（1-生效 2-终止 3-解除）',
  termination_date DATE COMMENT '终止/解除日期',
  termination_reason VARCHAR(500) COMMENT '终止/解除原因',
  attachment_url VARCHAR(255) COMMENT '附件URL',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_number (contract_number),
  KEY idx_person_id (person_id),
  KEY idx_contract_status (status),
  KEY idx_contract_start_date (start_date),
  KEY idx_contract_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人事合同表';

-- per_employee_organization表（员工与组织关系表）
CREATE TABLE IF NOT EXISTS per_employee_organization (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  employee_id BIGINT NOT NULL COMMENT '员工ID',
  organization_id BIGINT NOT NULL COMMENT '组织ID',
  organization_type VARCHAR(20) COMMENT '组织类型',
  position_id BIGINT COMMENT '职位ID',
  is_primary BOOLEAN DEFAULT FALSE COMMENT '是否主要组织',
  start_date DATE COMMENT '开始日期',
  end_date DATE COMMENT '结束日期',
  status INTEGER DEFAULT 1 COMMENT '关联状态（1-有效 0-无效）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_employee_org (employee_id, organization_id, position_id),
  KEY idx_employee_id (employee_id),
  KEY idx_organization_id (organization_id),
  KEY idx_position_id (position_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工与组织关系表';

-- per_employee_position_history表（员工职位变更历史表）
CREATE TABLE IF NOT EXISTS per_employee_position_history (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  employee_id BIGINT NOT NULL COMMENT '员工ID',
  organization_id BIGINT COMMENT '组织ID',
  from_position_id BIGINT COMMENT '变更前职位ID',
  from_position_name VARCHAR(50) COMMENT '变更前职位名称',
  to_position_id BIGINT NOT NULL COMMENT '变更后职位ID',
  to_position_name VARCHAR(50) NOT NULL COMMENT '变更后职位名称',
  effective_date DATE NOT NULL COMMENT '变更生效日期',
  change_reason VARCHAR(255) COMMENT '变更原因',
  operator_id BIGINT COMMENT '操作人ID',
  operator_name VARCHAR(50) COMMENT '操作人姓名',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_employee_id (employee_id),
  KEY idx_effective_date (effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工职位变更历史表';

-- per_education_experience表（教育经历表）
CREATE TABLE IF NOT EXISTS per_education_experience (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  employee_id BIGINT NOT NULL COMMENT '员工ID',
  school_name VARCHAR(100) NOT NULL COMMENT '学校名称',
  college_name VARCHAR(100) COMMENT '学院/系名称',
  major VARCHAR(100) COMMENT '专业名称',
  degree INTEGER COMMENT '学位（1-专科 2-本科 3-硕士 4-博士 5-其他）',
  education INTEGER COMMENT '学历（1-专科 2-本科 3-硕士研究生 4-博士研究生 5-其他）',
  start_date DATE COMMENT '开始日期',
  end_date DATE COMMENT '结束日期',
  is_full_time BOOLEAN DEFAULT TRUE COMMENT '是否全日制',
  is_highest BOOLEAN DEFAULT FALSE COMMENT '是否最高学历',
  certificate_url VARCHAR(255) COMMENT '证书附件URL',
  description VARCHAR(500) COMMENT '描述',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_employee_id (employee_id),
  KEY idx_is_highest (is_highest)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教育经历表';

-- per_work_experience表（工作经历表）
CREATE TABLE IF NOT EXISTS per_work_experience (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  employee_id BIGINT NOT NULL COMMENT '员工ID',
  company_name VARCHAR(100) NOT NULL COMMENT '公司名称',
  department_name VARCHAR(100) COMMENT '部门名称',
  position_name VARCHAR(100) COMMENT '职位名称',
  start_date DATE COMMENT '开始日期',
  end_date DATE COMMENT '结束日期',
  is_current BOOLEAN DEFAULT FALSE COMMENT '是否目前工作',
  job_description TEXT COMMENT '工作内容',
  leave_reason VARCHAR(255) COMMENT '离职原因',
  reference_person VARCHAR(50) COMMENT '证明人',
  reference_contact VARCHAR(50) COMMENT '证明人联系方式',
  reference_url VARCHAR(255) COMMENT '证明材料URL',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_employee_id (employee_id),
  KEY idx_is_current (is_current)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工作经历表';

-- 恢复外键约束
SET FOREIGN_KEY_CHECKS = 1;
