-- 文档表
CREATE TABLE IF NOT EXISTS doc_document (
    id bigint NOT NULL AUTO_INCREMENT,
    document_number varchar(50) NOT NULL,
    document_name varchar(200) NOT NULL,
    document_type varchar(50) NOT NULL,
    security_level varchar(50) NOT NULL,
    document_status varchar(50) NOT NULL DEFAULT 'DRAFT',
    category_id bigint NOT NULL,
    folder varchar(500) DEFAULT NULL,
    tags varchar(1000) DEFAULT NULL,
    law_firm_id bigint NOT NULL,
    case_id bigint DEFAULT NULL,
    client_id bigint DEFAULT NULL,
    contract_id bigint DEFAULT NULL,
    department_id varchar(50) DEFAULT NULL,
    keywords varchar(500) DEFAULT NULL,
    summary varchar(2000) DEFAULT NULL,
    current_version varchar(20) DEFAULT NULL,
    retention_time datetime DEFAULT NULL,
    related_documents varchar(500) DEFAULT NULL,
    template_id varchar(100) DEFAULT NULL,
    language varchar(100) DEFAULT NULL,
    need_archive tinyint(1) DEFAULT '0',
    archive_time datetime DEFAULT NULL,
    ocr_status varchar(20) DEFAULT 'NOT_STARTED',
    ocr_time datetime DEFAULT NULL,
    ocr_error_message varchar(500) DEFAULT NULL,
    status varchar(20) NOT NULL DEFAULT 'ENABLED',
    version int DEFAULT '0',
    remark varchar(500) DEFAULT NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by varchar(50) DEFAULT NULL,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by varchar(50) DEFAULT NULL,
    deleted tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_number (document_number),
    KEY idx_document_type (document_type),
    KEY idx_document_status (document_status),
    KEY idx_category_id (category_id),
    KEY idx_law_firm_id (law_firm_id),
    KEY idx_case_id (case_id),
    KEY idx_create_time (create_time)
);

-- 文档存储表
CREATE TABLE IF NOT EXISTS doc_document_storage (
    id bigint NOT NULL AUTO_INCREMENT,
    document_id bigint NOT NULL,
    file_name varchar(200) NOT NULL,
    file_type varchar(50) NOT NULL,
    file_size bigint NOT NULL,
    storage_path varchar(500) NOT NULL,
    md5 varchar(32) DEFAULT NULL,
    status varchar(20) NOT NULL DEFAULT 'ENABLED',
    version int DEFAULT '0',
    remark varchar(500) DEFAULT NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by varchar(50) DEFAULT NULL,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by varchar(50) DEFAULT NULL,
    deleted tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_id (document_id),
    FOREIGN KEY (document_id) REFERENCES doc_document (id)
);

-- 文档版本表
CREATE TABLE IF NOT EXISTS doc_document_version (
    id bigint NOT NULL AUTO_INCREMENT,
    document_id bigint NOT NULL,
    version_number varchar(20) NOT NULL,
    file_name varchar(200) NOT NULL,
    file_type varchar(50) NOT NULL,
    file_size bigint NOT NULL,
    storage_path varchar(500) NOT NULL,
    md5 varchar(32) DEFAULT NULL,
    change_description varchar(2000) DEFAULT NULL,
    status varchar(20) NOT NULL DEFAULT 'ENABLED',
    version int DEFAULT '0',
    remark varchar(500) DEFAULT NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by varchar(50) DEFAULT NULL,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by varchar(50) DEFAULT NULL,
    deleted tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_version (document_id, version_number),
    FOREIGN KEY (document_id) REFERENCES doc_document (id)
); 