spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-mysql}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    allow-missing-beans: true
    banner-mode: off
    log-startup-info: false
    lazy-initialization: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: LawFirmHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    enabled: false
  liquibase:
    enabled: false
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  autoconfigure:
    exclude:
      - org.flowable.spring.boot.FlowableAutoConfiguration
      - org.flowable.spring.boot.ProcessEngineServicesAutoConfiguration
      - org.flowable.spring.boot.actuate.endpoint.ProcessEngineEndpointAutoConfiguration
      - org.flowable.spring.boot.actuate.info.FlowableInfoAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineServicesAutoConfiguration
      - org.flowable.spring.boot.engine.FlowableEngineAutoConfiguration
      - org.flowable.spring.boot.EndpointAutoConfiguration
      - org.flowable.spring.boot.FlowableSecurityAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineServicesAutoConfiguration
      - com.lawfirm.core.workflow.config.FlowableConfig
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    global-config:
      db-config:
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1
  data:
    jpa:
      repositories:
        enabled: false
    ldap:
      repositories:
        enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# 安全配置
security:
  enabled: false

method:
  security:
    enabled: false

dev:
  auth:
    simplified-security: true

# 律师事务所功能模块开关
lawfirm:
  audit:
    enabled: true
  workflow:
    enabled: false
  client:
    enabled: true
  auth:
    enabled: true
  module:
    case: true
    contract: true
    knowledge:
      enabled: true
  search:
    enabled: true
    type: database
  storage:
    enabled: true
    defaultType: LOCAL
    defaultBucketId: 1
    path:
      baseDir: ${user.home}/.law-firm/storage
      tempDir: ${user.home}/.law-firm/storage/temp
      urlPrefix: http://localhost:8080/api/files
    local:
      enabled: true
      basePath: ${user.home}/.law-firm/storage
      urlPrefix: http://localhost:8080/api/files
    minio:
      enabled: false
      endpoint: http://minio.example.com
      port: 9000
      accessKey: minioadmin
      secretKey: minioadmin
      useSsl: false

# 日志配置
law:
  firm:
    log:
      enableMethodLog: true
      enableRequestLog: true
      logStackTrace: true

# API安全配置
api:
  security:
    xss:
      exclude-urls:
        - "/api/v1/auth/login"
        - "/api/v1/auth/register"
        - "/api/v1/document/upload"
        - "/api/v1/knowledge/content"
  doc:
    filter:
      enabled: true

# 应用信息配置
app:
  name: "law-firm-api"
  version: "1.0.0"
  description: "律师事务所管理系统API服务"

# API文档配置 - 统一使用Knife4j
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
    url: /v3/api-docs
    urls-primary-name: default
    urls:
      - name: default
        url: /v3/api-docs
  packages-to-scan: com.lawfirm
  paths-to-match: /**
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  auto-tag-classes: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  cache:
    disabled: true
  override-with-generic-response: false
  group-configs:
    - group: all
      display-name: "所有接口"
      packages-to-scan: 
        - com.lawfirm
    - group: auth
      display-name: "认证模块"
      packages-to-scan: 
        - com.lawfirm.auth.controller
      paths-to-match: 
        - /auth/**
        - /role/**
        - /permission/**
        - /user/**
    - group: personnel
      display-name: "人事模块"
      packages-to-scan: 
        - com.lawfirm.personnel.controller
      paths-to-match: 
        - /personnel/**
    - group: client
      display-name: "客户模块"
      packages-to-scan: 
        - com.lawfirm.client.controller
      paths-to-match: 
        - /client/**
    - group: case
      display-name: "案件模块"
      packages-to-scan: 
        - com.lawfirm.cases.controller
      paths-to-match: 
        - /case/**
        - /cases/**
    - group: contract
      display-name: "合同模块"
      packages-to-scan: 
        - com.lawfirm.contract.controller
      paths-to-match: 
        - /contract/**
    - group: document
      display-name: "文档模块"
      packages-to-scan: 
        - com.lawfirm.document.controller
      paths-to-match: 
        - /document/**
    - group: knowledge
      display-name: "知识模块"
      packages-to-scan: 
        - com.lawfirm.knowledge.controller
      paths-to-match: 
        - /knowledge/**
    - group: finance
      display-name: "财务模块"
      packages-to-scan: 
        - com.lawfirm.finance.controller
      paths-to-match: 
        - /finance/**
    - group: system
      display-name: "系统模块"
      packages-to-scan: 
        - com.lawfirm.system.controller
      paths-to-match: 
        - /system/**

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: false
    enable-host: false
    enable-version: false
    enable-footer: false
    enable-home-custom: true
    enable-after-script: true
    custom-js: |
      window.onload = function() {
        // 解决Base64解析错误
        const originalJSON = JSON.parse;
        JSON.parse = function(text) {
          if (text && typeof text === 'string' && text.startsWith('ey')) {
            console.warn('检测到可能的Base64编码内容:', text.substring(0, 30) + '...');
            try {
              // 尝试正常解析
              return originalJSON(text);
            } catch (e) {
              console.warn('JSON解析错误，尝试Base64解码', e);
              try {
                // 尝试先Base64解码
                const decoded = atob(text);
                console.log('Base64解码成功，解码后内容:', decoded.substring(0, 30) + '...');
                return originalJSON(decoded);
              } catch (e2) {
                console.error('Base64解码也失败', e2);
                throw e; // 使用原始错误
              }
            }
          }
          return originalJSON(text);
        };
      }
  production: false
  basic:
    enable: false
    username: admin
    password: admin
  # 启用Knife4j增强
  enhance: true

# 消息服务配置
message:
  enabled: true
  async:
    enabled: true
  rocketmq:
    topic: law-firm-message
    consumer-group: law-firm-consumer

# RocketMQ配置
rocketmq:
  enabled: false
  producer:
    enabled: false
  consumer:
    enabled: false

# Flowable配置
flowable:
  enabled: false
  process-engine:
    enable: false
  dmn-engine:
    enable: false
  idm-engine:
    enable: false
  form-engine:
    enable: false
  content-engine:
    enable: false
  event-registry-engine:
    enable: false
  rest:
    enabled: false
  actuator:
    enabled: false
  database-schema-update: false
  check-process-definitions: false

# 配置刷新相关设置
config:
  refresh:
    enabled: false
    refresh-interval: 30000
    refresh-on-startup: true
    source-type: file

# Lucene搜索配置
search:
  engine: lucene
  enabled: true
  lucene:
    index-dir: ${user.home}/.law-firm/lucene-index
    ram-buffer-size-mb: 32
    max-results: 1000
    highlight-enabled: true
    highlight-pre-tag: <em>
    highlight-post-tag: </em>

# AI模块配置
law.firm.ai:
  enabled: true
  defaultProvider: openai
  timeout: 30
  maxConcurrentRequests: 10
  enableCache: true
  enableSensitiveFilter: true
  enableRiskAssessment: true
  debug: false
law.firm.ai.model:
  openai:
    apiKey: ${AI_OPENAI_API_KEY:sk-demo-key}
    baseUrl: https://api.openai.com/v1
    defaultModel: gpt-4
  baidu:
    apiKey: ${AI_BAIDU_API_KEY:}
    secretKey: ${AI_BAIDU_SECRET_KEY:}
    baseUrl: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop
    defaultModel: ERNIE-Bot-4

# 健康检查配置
management:
  health:
    elasticsearch:
      enabled: false

# 知识库模块配置
knowledge:
  storage:
    basePath: ${user.home}/.law-firm/knowledge
    tempPath: ${user.home}/.law-firm/knowledge/temp
  document:
    maxSize: 10MB
    allowedExtensions: .doc,.docx,.pdf,.md,.txt
  attachment:
    maxSize: 20MB
    maxCountPerKnowledge: 10
    allowedExtensions: .doc,.docx,.pdf,.jpg,.png,.zip
  category:
    maxDepth: 3
  search:
    enableHighlight: true
    maxResultCount: 100
    minKeywordLength: 2
  statistic:
    cron: 0 0 1 * * ?

# 审计模块配置
law.firm.audit:
  enabled: true
  async:
    enabled: true
    poolSize: 4
    queueCapacity: 1000
  logType: db
  includeRequestParams: true
  includeResponseBody: false
