# 测试环境配置
spring:
  # 数据源配置
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE_TEST}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}
      connection-test-query: SELECT 1
  
  # Flyway配置
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    validate-on-migrate: ${SPRING_FLYWAY_VALIDATE_ON_MIGRATE}
    locations: classpath:db/migration
    table: flyway_schema_history
    encoding: UTF-8
    placeholders:
      schema: ${SPRING_FLYWAY_PLACEHOLDERS_SCHEMA}
  
  # Redis测试配置
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      database: ${SPRING_REDIS_DATABASE_TEST}
      timeout: ${SPRING_REDIS_TIMEOUT}
      lettuce:
        pool:
          min-idle: ${SPRING_REDIS_LETTUCE_POOL_MIN_IDLE}
          max-idle: ${SPRING_REDIS_LETTUCE_POOL_MAX_IDLE}
          max-active: ${SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE}
          max-wait: ${SPRING_REDIS_LETTUCE_POOL_MAX_WAIT}
  
  # 禁用缓存
  cache:
    type: none

# 测试环境专用配置
lawfirm:
  # 搜索引擎配置
  search:
    enabled: ${LAWFIRM_SEARCH_ENABLED:false}
  
  # 存储配置
  storage:
    enabled: ${LAWFIRM_STORAGE_ENABLED:true}
    defaultType: ${LAWFIRM_STORAGE_TYPE:LOCAL}
    path:
      baseDir: ${LAWFIRM_STORAGE_PATH:${user.home}/.law-firm/test/storage}
      tempDir: ${LAWFIRM_STORAGE_TEMP_PATH:${user.home}/.law-firm/test/storage/temp}
    local:
      enabled: true
      basePath: ${LAWFIRM_STORAGE_LOCAL_PATH:${user.home}/.law-firm/test/storage}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:${user.home}/logs/law-firm-test.log} 