# 数据源配置
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 
    type: com.zaxxer.hikari.HikariDataSource
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1

# 数据库初始化配置
sql:
  init:
    mode: always
    schema-locations: classpath:db/schema.sql
    data-locations: classpath:db/data.sql
    continue-on-error: false

# 开发模式配置
dev:
  # 开发模式下认证配置
  auth:
    # 禁用Redis会话存储
    session-store: memory
    # 令牌有效期（秒）
    token-expiration: 86400

# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: DEBUG
    org.mybatis: INFO
    com.baomidou.mybatisplus: INFO
    org.springframework.jdbc: DEBUG

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类扫描路径，使用通配符
  type-aliases-package: com.lawfirm.model.**.entity
  # 类型处理器
  type-handlers-package: com.lawfirm.common.core.handler
  # 配置文件，避免和Java代码配置冲突
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 避免XML解析错误
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 避免类型冲突
    use-java-type: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0 