# 律师事务所管理系统主应用配置
spring:
  application:
    name: law-firm-management
  profiles:
    # 默认激活的环境配置
    active: ${SPRING_PROFILES_ACTIVE:local}
    # 包含所有业务模块配置
    include:
      # 核心业务模块
      - system     # 系统管理
      - auth       # 认证授权
      - personnel  # 人事管理
      - finance    # 财务管理
      - document   # 文档管理
      - knowledge  # 知识管理
      # 业务功能模块
      - case       # 案件管理
      - contract   # 合同管理
      - client     # 客户管理
      - archive    # 归档管理
      # 辅助功能模块
      - task       # 任务管理
      - conflict   # 冲突检查
      - schedule   # 日程管理
      - analysis   # 数据分析
      # API文档配置
      - api-docs   # API文档
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    lazy-initialization: false
    banner-mode: off
  # 数据服务配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # Flyway数据库迁移配置
  flyway:
    enabled: false
  # 禁用不需要的自动配置
  jpa:
    open-in-view: false
    enabled: false
  data:
    jpa:
      repositories:
        enabled: false
  # Web相关配置  
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 安全配置
  security:
    enabled: true
    ignore-urls:
      - "/favicon.ico"
      - "/error"
      - "/health"
      - "/version"
  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1
  # SQL初始化配置
  sql:
    init:
      mode: never
  # 静态资源配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/

# 服务器配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  compression:
    enabled: false

# 应用基本信息
app:
  name: "法律事务管理系统"
  version: "1.0.0"
  description: "专业法律事务管理平台"

# 业务模块集成配置
lawfirm:
  module:
    case: true
    contract: true
    knowledge:
      enabled: true
  # 搜索服务配置
  search:
    enabled: true
    type: lucene
  # 存储服务配置
  storage:
    enabled: true
    defaultType: LOCAL
    path:
      baseDir: ${LAWFIRM_STORAGE_PATH:${user.home}/.law-firm/storage}
      tempDir: ${LAWFIRM_STORAGE_TEMP_PATH:${user.home}/.law-firm/storage/temp}
    local:
      enabled: true
      basePath: ${LAWFIRM_STORAGE_LOCAL_PATH:${user.home}/.law-firm/storage}

# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: INFO
