spring:
  application:
    name: law-firm-management
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-mysql}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    lazy-initialization: false
    banner-mode: off
  # 禁用JPA自动配置
  jpa:
    open-in-view: false
    enabled: false
  data:
    jpa:
      repositories:
        enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    enabled: true
    ignore-urls:
      - "/favicon.ico"
      - "/error"
      - "/health"
      - "/version"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Zjy-1314
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1
  sql:
    init:
      mode: never
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  compression:
    enabled: false

# 添加应用基本配置
app:
  name: "法律事务管理系统"
  version: "1.0.0"
  description: "专业法律事务管理平台"

# 简化的模块配置
lawfirm:
  module:
    case: true
    contract: true
    knowledge:
      enabled: true
  search:
    enabled: true
    type: lucene
  storage:
    enabled: true
    defaultType: LOCAL
    path:
      baseDir: ${user.home}/.law-firm/storage
      tempDir: ${user.home}/.law-firm/storage/temp
    local:
      enabled: true
      basePath: ${user.home}/.law-firm/storage

# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: INFO
