spring:
  # 生产环境数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:law_firm}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      # 生产环境连接池配置
      minimum-idle: 20
      maximum-pool-size: 100
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: LawFirmHikariCP
      # 连接测试配置
      connection-test-query: SELECT 1
      validation-timeout: 10000
      # 自动提交设置
      auto-commit: true
      # 连接初始化SQL
      connection-init-sql: SET NAMES utf8mb4
      # 泄漏检测
      leak-detection-threshold: 60000
      # 注册JMX监控
      register-mbeans: true
  
  # 生产环境Redis配置
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 10000
      lettuce:
        pool:
          max-active: 500
          max-wait: -1
          max-idle: 50
          min-idle: 10
  
  # 生产环境文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  # 生产环境仅执行迁移，不清空数据库
  flyway:
    enabled: true
    clean-disabled: true
    validate-on-migrate: true

# 生产环境服务器配置
server:
  port: ${SERVER_PORT:80}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  tomcat:
    # 生产环境线程池配置
    max-threads: 500
    min-spare-threads: 30
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000

# 生产环境仅允许特定源跨域
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://admin.lawfirm.com}
  # 生产环境下不使用通配符允许所有域
  use-wildcard: false

# 生产环境API文档配置 - 默认禁用
springdoc:
  api-docs:
    enabled: ${ENABLE_API_DOCS:false}
  swagger-ui:
    enabled: ${ENABLE_API_DOCS:false}

# 生产环境Knife4j配置 - 默认禁用
knife4j:
  enable: ${ENABLE_API_DOCS:false}
  production: true # 生产环境模式

# 生产环境日志级别
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:WARN}
    com.lawfirm: ${LOGGING_LEVEL_APP:INFO}
    org.springframework: ${LOGGING_LEVEL_SPRING:WARN}
    com.baomidou.mybatisplus: ${LOGGING_LEVEL_MYBATIS:WARN}
  file:
    # 生产环境保留更多日志历史
    max-history: ${LOG_FILE_MAX_HISTORY:90}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:10GB}

# 生产环境禁用MyBatis Plus详细日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 生产环境安全配置
law-firm:
  security:
    jwt:
      # 生产环境更长的令牌有效期
      expiration: ${JWT_EXPIRATION:86400}
    # 生产环境禁用模拟用户
    mock-user:
      enabled: false
    # 生产环境启用所有安全措施
    disable:
      csrf: false
      xss-filter: false
  
  # 生产环境启用所有核心模块
  core:
    workflow:
      enabled: true
    storage:
      enabled: true
      # 生产环境使用云存储
      type: ${STORAGE_TYPE:minio}
      minio:
        endpoint: ${MINIO_ENDPOINT:http://minio:9000}
        access-key: ${MINIO_ACCESS_KEY:minioadmin}
        secret-key: ${MINIO_SECRET_KEY:minioadmin}
        bucket: ${MINIO_BUCKET:law-firm}
    search:
      enabled: true
      searchEngineType: ${SEARCH_ENGINE_TYPE:database}
    audit:
      enabled: true 
  
  # 定义系统数据库名
  common:
    data:
      system-database: ${SYSTEM_DATABASE:law_firm}
      module-init-enabled: true 