# 统一安全配置
# 本配置文件统一管理安全相关配置，确保安全策略一致性
spring:
  config:
    activate:
      on-profile: security

# 律师事务所安全配置
lawfirm:
  security:
    # JWT配置
    jwt:
      # JWT密钥 - 生产环境必须使用强密钥
      secret: ${JWT_SECRET:LawFirm2024!@#$%^&*()_+SecretKey}
      # 令牌有效期配置
      expiration:
        # 访问令牌有效期（秒）
        access-token: ${JWT_ACCESS_TOKEN_EXPIRATION:7200}    # 2小时
        # 刷新令牌有效期（秒） 
        refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION:604800} # 7天
        # 记住我模式有效期（秒）
        remember-me: ${JWT_REMEMBER_ME_EXPIRATION:2592000}   # 30天
      # JWT签发者
      issuer: ${JWT_ISSUER:law-firm-system}
      # JWT受众
      audience: ${JWT_AUDIENCE:law-firm-users}
      
    # 密码策略配置
    password:
      # 密码强度要求
      strength:
        # 最小长度
        min-length: ${PASSWORD_MIN_LENGTH:8}
        # 最大长度
        max-length: ${PASSWORD_MAX_LENGTH:64}
        # 必须包含大写字母
        require-uppercase: ${PASSWORD_REQUIRE_UPPERCASE:true}
        # 必须包含小写字母
        require-lowercase: ${PASSWORD_REQUIRE_LOWERCASE:true}
        # 必须包含数字
        require-digit: ${PASSWORD_REQUIRE_DIGIT:true}
        # 必须包含特殊字符
        require-special-char: ${PASSWORD_REQUIRE_SPECIAL:true}
        # 特殊字符集合
        special-chars: ${PASSWORD_SPECIAL_CHARS:!@#$%^&*()_+-=[]{}|;:,.<>?}
      
      # 密码生命周期
      lifecycle:
        # 密码过期天数
        expire-days: ${PASSWORD_EXPIRE_DAYS:90}
        # 密码过期前提醒天数
        expire-warn-days: ${PASSWORD_EXPIRE_WARN_DAYS:7}
        # 历史密码检查数量
        history-count: ${PASSWORD_HISTORY_COUNT:5}
        # 密码重复间隔（小时）
        repeat-interval-hours: ${PASSWORD_REPEAT_INTERVAL:24}
      
      # 密码加密配置
      encryption:
        # 加密算法
        algorithm: ${PASSWORD_ENCRYPTION_ALGORITHM:bcrypt}
        # BCrypt强度
        bcrypt-strength: ${PASSWORD_BCRYPT_STRENGTH:12}
        # 加盐长度
        salt-length: ${PASSWORD_SALT_LENGTH:16}
    
    # 登录安全配置
    login:
      # 登录限制
      limits:
        # 最大失败次数
        max-fail-attempts: ${LOGIN_MAX_FAIL_ATTEMPTS:5}
        # 锁定时间（分钟）
        lockout-duration: ${LOGIN_LOCKOUT_DURATION:30}
        # 锁定后冷却时间（分钟）
        cooldown-duration: ${LOGIN_COOLDOWN_DURATION:5}
        # 是否允许多端同时登录
        allow-multiple-sessions: ${LOGIN_ALLOW_MULTIPLE:false}
        # 同一IP最大并发登录数
        max-concurrent-per-ip: ${LOGIN_MAX_CONCURRENT_IP:10}
      
      # 验证码配置
      captcha:
        # 是否启用验证码
        enabled: ${LOGIN_CAPTCHA_ENABLED:true}
        # 验证码类型：math, char, image, slide
        type: ${LOGIN_CAPTCHA_TYPE:math}
        # 验证码长度
        length: ${LOGIN_CAPTCHA_LENGTH:4}
        # 验证码有效期（秒）
        expiration: ${LOGIN_CAPTCHA_EXPIRATION:300}
        # 失败次数达到多少次后启用验证码
        trigger-after-failures: ${LOGIN_CAPTCHA_TRIGGER:3}
        
    # 会话管理配置
    session:
      # 会话超时时间（秒）
      timeout: ${SESSION_TIMEOUT:7200}
      # 最大并发会话数
      max-sessions: ${SESSION_MAX_COUNT:1}
      # 会话固化保护
      fixation-protection: ${SESSION_FIXATION_PROTECTION:true}
      # 会话Cookie配置
      cookie:
        # Cookie名称
        name: ${SESSION_COOKIE_NAME:LAWFIRM_SESSION}
        # 是否仅HTTPS
        secure: ${SESSION_COOKIE_SECURE:false}
        # HttpOnly
        http-only: ${SESSION_COOKIE_HTTP_ONLY:true}
        # SameSite策略
        same-site: ${SESSION_COOKIE_SAME_SITE:Lax}
    
    # IP访问控制
    ip-access:
      # 是否启用IP白名单
      whitelist-enabled: ${SECURITY_IP_WHITELIST_ENABLED:false}
      # IP白名单
      whitelist: ${SECURITY_IP_WHITELIST:127.0.0.1,::1}
      # 是否启用IP黑名单
      blacklist-enabled: ${SECURITY_IP_BLACKLIST_ENABLED:true}
      # IP黑名单
      blacklist: ${SECURITY_IP_BLACKLIST:}
      # 地理位置限制
      geo-restriction:
        enabled: ${SECURITY_GEO_RESTRICTION_ENABLED:false}
        allowed-countries: ${SECURITY_ALLOWED_COUNTRIES:CN,HK,MO,TW}
    
    # API安全配置
    api:
      # 接口签名验证
      signature:
        enabled: ${API_SIGNATURE_ENABLED:false}
        algorithm: ${API_SIGNATURE_ALGORITHM:HmacSHA256}
        header-name: ${API_SIGNATURE_HEADER:X-API-Signature}
        timestamp-header: ${API_TIMESTAMP_HEADER:X-API-Timestamp}
        # 签名有效期（秒）
        validity: ${API_SIGNATURE_VALIDITY:300}
      
      # API限流配置
      rate-limit:
        # 全局限流
        global:
          enabled: ${API_RATE_LIMIT_GLOBAL_ENABLED:true}
          # 每分钟请求数
          requests-per-minute: ${API_RATE_LIMIT_GLOBAL_RPM:1000}
        # 用户级限流
        user:
          enabled: ${API_RATE_LIMIT_USER_ENABLED:true}
          requests-per-minute: ${API_RATE_LIMIT_USER_RPM:100}
        # IP级限流
        ip:
          enabled: ${API_RATE_LIMIT_IP_ENABLED:true}
          requests-per-minute: ${API_RATE_LIMIT_IP_RPM:200}
      
      # 跨域配置
      cors:
        # 允许的源
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://localhost:3000}
        # 允许的方法
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
        # 允许的头部
        allowed-headers: ${CORS_ALLOWED_HEADERS:*}
        # 是否允许凭证
        allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
        # 预检请求缓存时间
        max-age: ${CORS_MAX_AGE:3600}
    
    # 数据保护配置
    data-protection:
      # 敏感数据加密
      encryption:
        enabled: ${DATA_ENCRYPTION_ENABLED:true}
        # 加密算法
        algorithm: ${DATA_ENCRYPTION_ALGORITHM:AES}
        # 密钥长度
        key-length: ${DATA_ENCRYPTION_KEY_LENGTH:256}
        # 加密模式
        mode: ${DATA_ENCRYPTION_MODE:GCM}
      
      # 数据脱敏
      masking:
        enabled: ${DATA_MASKING_ENABLED:true}
        # 手机号脱敏
        phone-pattern: ${DATA_MASKING_PHONE:${phone:3:4}}
        # 身份证脱敏
        id-card-pattern: ${DATA_MASKING_ID_CARD:${idCard:6:4}}
        # 邮箱脱敏
        email-pattern: ${DATA_MASKING_EMAIL:${email:3}}
    
    # 审计配置
    audit:
      # 是否启用安全审计
      enabled: ${SECURITY_AUDIT_ENABLED:true}
      # 审计事件类型
      events:
        - LOGIN_SUCCESS
        - LOGIN_FAILURE
        - LOGOUT
        - PASSWORD_CHANGE
        - PERMISSION_DENIED
        - SUSPICIOUS_ACTIVITY
      # 审计日志保留天数
      retention-days: ${SECURITY_AUDIT_RETENTION:180}
      # 是否实时告警
      real-time-alert: ${SECURITY_AUDIT_REAL_TIME:true}
    
    # 环境特定配置
    environment:
      # 开发环境配置
      dev:
        # 开发环境允许模拟用户
        mock-user-enabled: true
        # 开发环境JWT密钥（较弱）
        jwt-secret: "dev-secret-key-2024"
        # 开发环境禁用部分安全检查
        security-checks-disabled: true
      
      # 测试环境配置  
      test:
        # 测试环境允许模拟用户
        mock-user-enabled: true
        # 测试环境JWT密钥
        jwt-secret: "test-secret-key-2024"
        # 测试环境简化密码策略
        password-policy-relaxed: true
      
      # 生产环境配置
      prod:
        # 生产环境禁用模拟用户
        mock-user-enabled: false
        # 生产环境强制HTTPS
        force-https: true
        # 生产环境启用所有安全检查
        all-security-checks-enabled: true 