# MySQL数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Zjy-1314}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # SQL初始化配置
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: UTF-8
      continue-on-error: true
      platform: mysql
      separator: ;;
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      enabled: false
  
  # Flyway配置
  flyway:
    enabled: false
    baseline-on-migrate: true
    group: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: true
    schemas: law_firm
    fail-on-missing-locations: false
    
  # 禁止覆盖Bean定义
  main:
    allow-bean-definition-overriding: true
    
  # 编码配置
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

# Jasypt加密配置
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD:}
    algorithm: PBEWithMD5AndDES
    provider-name: SunJCE

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lawfirm.model.**.entity
  type-handlers-package: com.lawfirm.common.core.handler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: DEBUG
    org.mybatis: INFO
    com.baomidou.mybatisplus: INFO
    org.springframework.jdbc: DEBUG

# JWT配置
law:
  firm:
    security:
      jwt:
        secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
        expiration: 86400000 # 24小时
        refresh-expiration: 604800000 # 7天
        issuer: law-firm-auth
        audience: law-firm-web

# 开发模式配置
dev:
  use-redis: false
  auth:
    session-store: memory
    disable-redis: true
    simplified-security: true
    disable-original-security: true
    token-expiration: 86400
    anonymous-urls:
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/swagger-ui/index.html"
      - "/v3/api-docs/**"
      - "/swagger-resources/**"
      - "/webjars/**"
      - "/doc.html"
      - "/doc"
      - "/docs"
      - "/api-docs"
    
# 搜索配置
search:
  enabled: true
  default-strategy: database

# AI配置
law.firm.ai:
  enabled: true
  defaultProvider: openai
  timeout: 30

# 禁用原始安全配置
auth:
  security:
    enabled: false

# 健康检查配置
management:
  health:
    redis:
      enabled: true

# 应用信息配置
app:
  name: "law-firm-api"
  version: "1.0.0"
  description: "律师事务所管理系统API服务"

# 禁用响应压缩，确保API文档正常显示
server:
  compression:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

# SpringDoc文档配置
springdoc:
  api-docs:
    compression:
      enabled: false 