spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:law_firm}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:law_firm}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASSWORD:}
      timeout: 10000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 5
      enabled: true
  
  # SQL初始化配置
  sql:
    init:
      mode: never
      
  # Flyway配置
  flyway:
    enabled: false
  
  # 允许覆盖Bean定义
  main:
    allow-bean-definition-overriding: true
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# Jasypt加密配置 - 生产环境请使用环境变量传入密钥
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    provider-name: SunJCE

# CORS跨域配置
cors:
  # 允许的源，多个源用逗号分隔
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://*.lawfirm.com}
  # 允许的HTTP方法
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  # 允许的请求头
  allowed-headers: Authorization,Content-Type,X-Requested-With
  # 暴露的响应头
  exposed-headers: Authorization
  # 是否允许Cookie
  allow-credentials: true
  # 最大缓存时间（秒）
  max-age: 3600

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lawfirm.model.**.entity
  type-handlers-package: com.lawfirm.common.core.handler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # 生产环境禁用SQL日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    root: WARN
    com.lawfirm: INFO
    org.mybatis: ERROR
    com.baomidou.mybatisplus: ERROR
    org.springframework.jdbc: ERROR
    org.springframework: WARN
  file:
    name: /var/log/law-firm/api.log
    path: ${LOG_PATH:/var/log/law-firm}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# JWT配置
law:
  firm:
    security:
      jwt:
        secret: ${JWT_SECRET:8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb}
        expiration: 43200000 # 12小时
        refresh-expiration: 604800000 # 7天
        issuer: law-firm-auth
        audience: law-firm-web

# 接口文档配置
springdoc:
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:false}
    path: /api-docs
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}

# API文档访问凭据
api:
  doc:
    username: ${API_DOC_USERNAME:admin}
    password: ${API_DOC_PASSWORD:ComplexP@ssw0rd}

# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: true

# 应用信息配置  
app:
  name: "law-firm-api"
  version: "1.0.0"
  description: "律师事务所管理系统API服务"

# 安全配置
security:
  jwt:
    token-expiration-seconds: 86400
    refresh-token-expiration-seconds: 604800
    token-secret: ${JWT_SECRET:defaultsecretkey12345678901234567890}
  password:
    check-strength: true
    min-length: 8
    require-special-chars: true
    require-digits: true
    require-uppercase: true

# 文件存储配置
file:
  storage:
    type: ${FILE_STORAGE_TYPE:local}
    local:
      path: ${FILE_STORAGE_PATH:/data/law-firm/files}
    oss:
      endpoint: ${OSS_ENDPOINT:}
      access-key: ${OSS_ACCESS_KEY:}
      secret-key: ${OSS_SECRET_KEY:}
      bucket-name: ${OSS_BUCKET_NAME:}

# 缓存配置
cache:
  ttl:
    default: 3600
    user: 1800
    menu: 7200

# 请求速率限制
rate-limit:
  enabled: true
  default-limit: 100
  ip-limit: 50
  burst: 20

# 方法安全
method:
  security:
    enabled: true

# 服务器配置
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  tomcat:
    max-threads: 400
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 1000
    connection-timeout: 30000
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    session:
      timeout: 1800s 