# 开发模式无Redis配置
# 用于开发环境下不依赖Redis的配置

# 应用配置
app:
  name: law-firm-api
  version: 1.0.0
  description: 律师事务所管理系统API服务
  author: LawFirm Team

# 开发模式标识
dev:
  use-redis: false
  auth:
    # 内存存储会话
    session-store: memory
    # 禁用Redis会话
    disable-redis: true
    # 简化安全配置
    simplified-security: true
    # 禁用原始安全配置
    disable-original-security: true
    
# 添加数据源配置避免主配置文件依赖
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: LawFirmHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 禁用H2配置
  h2:
    console:
      enabled: false
  # 禁用数据库初始化脚本
  sql:
    init:
      enabled: false
  # 禁用Redis
  data:
    redis:
      enabled: false
  # 禁用Elasticsearch
  elasticsearch:
    enabled: false
  # 禁用Redis自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
  # 允许Bean定义覆盖
  main:
    allow-bean-definition-overriding: true
  # 简化安全设置
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:${random.uuid}}
      roles: ADMIN
    filter:
      dispatcher-types: REQUEST,ASYNC
    headers:
      frame: SAMEORIGIN
      xss: true
  # 禁用Flyway
  flyway:
    enabled: false
  # 禁用Liquibase
  liquibase:
    enabled: false
  # 禁用Runner
  runner:
    enabled: false

# 禁用Redisson配置
redisson:
  enabled: false

# 自定义认证配置
auth:
  security:
    enabled: false
  redis:
    enabled: false
  captcha:
    enabled: false
  mock:
    enabled: true
  debug: true

# 添加Jasypt加密配置
jasypt:
  encryptor:
    password: your-secret-key
    algorithm: PBEWithMD5AndDES
    provider-name: SunJCE 

# JWT配置
law:
  firm:
    security:
      jwt:
        secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
        expiration: 86400000
        refresh-expiration: 604800000
        issuer: law-firm-auth
        audience: law-firm-web

# 禁用搜索功能
search:
  enabled: false

# Elasticsearch配置
elasticsearch:
  enabled: false
  cluster:
    name: law-firm-cluster
    nodes:
      - localhost:9200

# 存储配置
storage:
  # 默认存储类型
  default-type: LOCAL
  # 默认存储桶ID
  default-bucket-id: 1
  # 路径配置
  path:
    # 本地存储根路径
    base-dir: ${user.home}/lawfirm/storage
    # 临时目录
    temp-dir: ${java.io.tmpdir}/lawfirm/temp
    # URL前缀
    url-prefix: http://localhost:8080/api/storage
  # 上传配置
  upload:
    # 最大文件大小 (100MB)
    max-size: 104857600
    # 分片大小 (5MB)
    chunk-size: 5242880
    # 允许的文件类型 (全部允许使用*)
    allowed-types: '*'
    # 禁止的文件类型
    denied-types: exe,bat,sh,dll
  # 本地存储配置
  local:
    enabled: true
    base-path: ${user.home}/lawfirm/storage
    url-prefix: http://localhost:8080/api/storage

# 文档模块配置
document:
  storage:
    default-type: LOCAL
    local-path: ${user.home}/lawfirm/document
    temp-path: ${java.io.tmpdir}/document-temp
    base-url: /api/document/file
    preview-url: /api/document/preview
    allowed-types: doc,docx,pdf,txt,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip,rar
    max-size: 104857600

# 财务模块配置 - 使用统一的命名规范
lawfirm:
  storage:
    enabled: true
  finance:
    cache:
      enabled: false
      expireTime: 3600
    event:
      async: false
      retryTimes: 3
    business:
      maxPageSize: 100
      exportLimit: 1000
  auth:
    redis:
      enabled: false
    captcha:
      enabled: false
    mock:
      enabled: true

# 配置刷新设置
config:
  refresh:
    enabled: false
    refresh-interval: 60000
    refresh-on-startup: false
    source-type: file
    source-path: config/

# 统一的缓存配置命名规范 (law.firm.* 格式)
law.firm.cache:
  enabled: false
  type: LOCAL
  expiration: 30
  refresh-time: 10

# 日志配置 - 使用统一的命名规范
law.firm.log:
  enable-method-log: false
  enable-request-log: false
  enable-async-log: false
  enable-tracing: false
  log-request-params: true
  log-response-body: true
  log-stack-trace: true
  exclude-paths:
    - /swagger-ui/**
    - /v3/api-docs/**

# 启用更详细的日志
logging:
  level:
    com.lawfirm: DEBUG
    org.springframework.security: DEBUG

# 禁用监控端点
management:
  health:
    elasticsearch:
      enabled: false 