spring:
  application:
    name: law-firm-api
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入各业务模块配置，避免重复配置
    include:
      - system    # 系统管理
      - auth      # 认证授权
      - client    # 客户管理
      - case      # 案件管理
      - contract  # 合同管理
      - document  # 文档管理
      - finance   # 财务管理
      - knowledge # 知识管理
      - task      # 任务管理
      - schedule  # 日程管理
      - personnel # 人员管理
      - analysis  # 分析功能
      - archive   # 档案管理
  # 允许Bean定义覆盖 - 重要，解决Bean冲突问题
  main:
    allow-bean-definition-overriding: true
    # 禁用懒加载，确保所有Bean在启动时完全初始化
    lazy-initialization: false
    # 允许循环引用
    allow-circular-references: true
    # 主应用类
    sources:
      - com.lawfirm.api.LawFirmApiApplication
  # 排除不需要的自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:law_firm}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: LawFirmHikariCP
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 10000
      lettuce:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0
      # 禁用Redis自动配置的存储库支持，使用自定义配置
      repositories:
        enabled: false
  # 线程池任务执行器配置
  task:
    execution:
      enabled: true
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        thread-name-prefix: law-firm-task-
  # 控制器Bean名称后缀，避免冲突
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  # Flyway数据库迁移配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
    # 禁用自动迁移，由应用程序控制迁移流程
    auto-migrate: false
  output:
    ansi:
      enabled: always

# 服务器配置
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    max-connections: 8192

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  # 不设置typeEnumsPackage以避免枚举扫描导致的类型推断问题
  # type-aliases-package: com.lawfirm.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    return-instance-for-empty-row: false
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: AUTO

# 跨域配置 - 整合common-web的跨域配置
cors:
  allowed-origins: "*"

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.lawfirm
  paths-to-match: /**

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.baomidou.mybatisplus: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/law-firm-api.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 系统参数配置 - 这里只放顶层配置，模块内配置通过include引入
"law-firm":
  # 安全配置
  security:
    jwt:
      secret: ${JWT_SECRET:lawfirm123456}
      expiration: ${JWT_EXPIRATION:86400}
      header: ${JWT_HEADER:Authorization}
      "token-start-with": ${JWT_TOKEN_START_WITH:Bearer }
      "token-header": ${JWT_TOKEN_HEADER:Authorization}
  
  # 核心模块配置
  core:
    audit:
      enabled: false
  
  # 搜索服务配置
  search:
    enabled: true
    # 设置为lucene
    searchEngineType: lucene
    # Lucene配置
    lucene:
      # 索引存储目录
      indexDir: ${user.home}/.law-firm/lucene-index
      # 内存缓冲区大小(MB)
      ramBufferSizeMb: 32
      # 最大搜索结果数
      maxResults: 1000
      # 是否启用高亮
      highlightEnabled: true
      # 高亮前置标签
      highlightPreTag: <em>
      # 高亮后置标签
      highlightPostTag: </em>
      # 分析器类型: standard, chinese, ik
      analyzer: ik
  
  # 通用配置
  common:
    core:
      enabled: true
    web:
      enabled: true
    data:
      enabled: true
      "module-init-enabled": true
    cache:
      enabled: true
    security:
      enabled: true
    log:
      enabled: false
      executor:
        bean-name: taskExecutor
    message:
      enabled: true

# 其他配置保持不变
# ... existing code ... 