spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-mysql}
  config:
    import:
      - optional:classpath:/config/apidoc.yml
      - optional:classpath:/config/knife4j.yml
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    allow-missing-beans: true
    banner-mode: off
    log-startup-info: false
    lazy-initialization: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: LawFirmHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    enabled: false
  liquibase:
    enabled: false
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    # 确保Jackson正确处理中文
    property-naming-strategy: SNAKE_CASE
    default-charset: UTF-8
    # 强制编码设置
    encoder:
      non-unicode: false
    parser:
      allow-unquoted-control-chars: false
      allow-backslash-escaping-any-character: false
  autoconfigure:
    exclude:
      - org.flowable.spring.boot.FlowableAutoConfiguration
      - org.flowable.spring.boot.ProcessEngineServicesAutoConfiguration
      - org.flowable.spring.boot.actuate.endpoint.ProcessEngineEndpointAutoConfiguration
      - org.flowable.spring.boot.actuate.info.FlowableInfoAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineServicesAutoConfiguration
      - org.flowable.spring.boot.engine.FlowableEngineAutoConfiguration
      - org.flowable.spring.boot.EndpointAutoConfiguration
      - org.flowable.spring.boot.FlowableSecurityAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineServicesAutoConfiguration
      - com.lawfirm.core.workflow.config.FlowableConfig
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    global-config:
      db-config:
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1
  data:
    jpa:
      repositories:
        enabled: false
    ldap:
      repositories:
        enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
  # Spring Security配置 (从重复的spring节移至此处)
  security:
    user:
      name: admin
      password: admin123
    filter:
      dispatcher-types: REQUEST,FORWARD
    # 显式允许匿名访问的路径
    permitAll:
      - "/doc.html"
      - "/doc.html/**"
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/webjars/**"

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    # 增强Tomcat编码配置
    relaxed-query-chars: <,>,|,[,],^,`,{,}
    relaxed-path-chars: <,>,|,[,],^,`,{,}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true

# 使用临时措施完全禁用Spring Security
security:
  enabled: false
  basic:
    enabled: false
  ignore-paths:
    - "/**"

# 显式禁用方法安全
method:
  security:
    enabled: false

# 开发环境认证简化配置
dev:
  auth:
    simplified-security: true
    session-store: memory
    disable-redis: true
    # 允许的匿名访问路径
    anonymous-urls:
      - "/**" # 允许所有路径匿名访问
      - "/doc.html"
      - "/doc.html/**"
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/webjars/**"

# 律师事务所功能模块开关
lawfirm:
  audit:
    enabled: true
  workflow:
    enabled: false
  client:
    enabled: true
  auth:
    enabled: true
  module:
    case: true
    contract: true
    knowledge:
      enabled: true
  search:
    enabled: true
    type: database
  storage:
    enabled: true
    defaultType: LOCAL
    defaultBucketId: 1
    path:
      baseDir: ${user.home}/.law-firm/storage
      tempDir: ${user.home}/.law-firm/storage/temp
      urlPrefix: http://localhost:8080/api/files
    local:
      enabled: true
      basePath: ${user.home}/.law-firm/storage
      urlPrefix: http://localhost:8080/api/files
    minio:
      enabled: false
      endpoint: http://minio.example.com
      port: 9000
      accessKey: minioadmin
      secretKey: minioadmin
      useSsl: false

# 日志配置
law:
  firm:
    log:
      enableMethodLog: true
      enableRequestLog: true
      logStackTrace: true
      # 添加中文支持
      charset: UTF-8

# API安全配置
api:
  security:
    xss:
      exclude-urls:
        - "/api/v1/auth/login"
        - "/api/v1/auth/register"
        - "/api/v1/document/upload"
        - "/api/v1/knowledge/content"
        # API文档路径
        - "/doc.html"
        - "/doc.html/**"
        - "/swagger-ui.html" 
        - "/swagger-ui/**"
        - "/v3/api-docs/**"
        - "/swagger-resources/**" 
        - "/webjars/**"
  doc:
    filter:
      enabled: true

# 应用信息配置
app:
  name: "law-firm-api"
  version: "1.0.0"
  description: "律师事务所管理系统API服务"

# 消息服务配置
message:
  enabled: true
  async:
    enabled: true

# RocketMQ配置
rocketmq:
  enabled: false
  producer:
    enabled: false
  consumer:
    enabled: false

# Flowable配置
flowable:
  enabled: false
  process-engine:
    enable: false
  dmn-engine:
    enable: false
  idm-engine:
    enable: false
  form-engine:
    enable: false
  content-engine:
    enable: false
  event-registry-engine:
    enable: false
  rest:
    enabled: false
  actuator:
    enabled: false
  database-schema-update: false
  check-process-definitions: false

# 配置刷新相关设置
config:
  refresh:
    enabled: false
    refresh-interval: 30000
    refresh-on-startup: true
    source-type: file

# 添加API文档配置，确保内容不被加密
springdoc:
  api-docs:
    safe-content: true
    disable-content-encoding: true
  swagger-ui:
    disable-content-encoding: true
    
# knife4j专用配置，禁用加密
knife4j:
  enable: true
  basic:
    enable: false
  production: false
  # 禁用API文档加密
  enable-website-encrypt: false  
  enable-content-encrypt: false

# Lucene搜索配置
search:
  engine: lucene
  enabled: true
  lucene:
    index-dir: ${user.home}/.law-firm/lucene-index
    ram-buffer-size-mb: 32
    max-results: 1000
    highlight-enabled: true
    highlight-pre-tag: <em>
    highlight-post-tag: </em>

# AI模块配置
law.firm.ai:
  enabled: true
  defaultProvider: openai
  timeout: 30
  maxConcurrentRequests: 10
  enableCache: true
  enableSensitiveFilter: true
  enableRiskAssessment: true
  debug: false
law.firm.ai.model:
  openai:
    apiKey: ${AI_OPENAI_API_KEY:sk-demo-key}
    baseUrl: https://api.openai.com/v1
    defaultModel: gpt-4
  baidu:
    apiKey: ${AI_BAIDU_API_KEY:}
    secretKey: ${AI_BAIDU_SECRET_KEY:}
    baseUrl: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop
    defaultModel: ERNIE-Bot-4

# 健康检查配置
management:
  health:
    elasticsearch:
      enabled: false

# 知识库模块配置
knowledge:
  storage:
    basePath: ${user.home}/.law-firm/knowledge
    tempPath: ${user.home}/.law-firm/knowledge/temp
  document:
    maxSize: 10MB
    allowedExtensions: .doc,.docx,.pdf,.md,.txt
  attachment:
    maxSize: 20MB
    maxCountPerKnowledge: 10
    allowedExtensions: .doc,.docx,.pdf,.jpg,.png,.zip
  category:
    maxDepth: 3
  search:
    enableHighlight: true
    maxResultCount: 100
    minKeywordLength: 2
  statistic:
    cron: 0 0 1 * * ?

# 审计模块配置
law.firm.audit:
  enabled: true
  async:
    enabled: true
    poolSize: 4
    queueCapacity: 1000
  logType: db
  includeRequestParams: true
  includeResponseBody: false

# Springdoc和Knife4j配置已移动到apidoc.yml
