# SpringDoc OpenAPI配置
springdoc:
  # API文档基本配置
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  # Swagger UI配置
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true
  # 全局默认设置
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.lawfirm
  # 路径配置
  paths-to-match: 
    - /api/**
  # 显示执行器端点
  show-actuator: false

# 仅在开发环境中打印更详细的API相关日志
logging:
  level:
    org.springdoc: INFO
    io.swagger.v3: INFO 