# 律师事务所管理系统配置文件
# 配置优先级说明：
#  1. 命令行参数 (--param=value)
#  2. 环境变量 (MYSQL_DATABASE, MYSQL_HOST 等)
#  3. 配置文件 (application.yml)
#  4. 代码中的默认值
#
# 多环境配置说明：
# - dev: 开发环境 (application-dev.yml)
# - test: 测试环境 (application-test.yml)
# - prod: 生产环境 (application-prod.yml)

spring:
  # 确保所有组件使用UTF-8编码
  mandatory-file-encoding: UTF-8
  application:
    name: law-firm-api
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入各业务模块配置，避免重复配置
    include:
      - system    # 系统管理
      - auth      # 认证授权
      - client    # 客户管理
      - case      # 案件管理
      - contract  # 合同管理
      - document  # 文档管理
      - finance   # 财务管理
      - knowledge # 知识管理
      - task      # 任务管理
      - schedule  # 日程管理
      - personnel # 人员管理
      - analysis  # 分析功能
      - archive   # 档案管理
  # 主要配置保留在这里，让应用启动时便于查看
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    allow-circular-references: true
    sources:
      - com.lawfirm.api.LawFirmApiApplication
  # 排除不需要的自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${spring.database.name}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useConfigs=maxPerformance
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    # 数据库名称配置 - 便于其他组件引用
    database-name: ${spring.database.name}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: LawFirmHikariCP
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 10000
      lettuce:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0
      repositories:
        enabled: true
  # 禁用不需要的组件
  ldap:
    embedded:
      enabled: false
    repositories:
      enabled: false
  security:
    ldap:
      enabled: false
  mail:
    enabled: false
    host: ""
    port: -1
  rabbitmq:
    enabled: false
    host: ""
    port: -1
  # 线程池任务执行器配置
  task:
    execution:
      enabled: true
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        thread-name-prefix: law-firm-task-
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  # Flyway数据库迁移配置
  flyway:
    enabled: true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${spring.database.name}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useConfigs=maxPerformance
    user: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: true
    auto-migrate: true
  output:
    ansi:
      enabled: always
  # Jackson JSON配置
  jackson:
    default-property-inclusion: non-null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    property-naming-strategy: SNAKE_CASE
  # 全局属性 - 数据库名称
  database:
    name: ${MYSQL_DATABASE:law_firm}
  # Spring MVC静态资源配置
  mvc:
    # 添加静态资源配置
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      # 静态资源处理
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
      chain:
        strategy:
          content:
            enabled: true
      # 明确添加API文档资源映射
      add-mappings: true

# 服务器配置
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  tomcat:
    max-threads: 200
    max-connections: 8192

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    return-instance-for-empty-row: false
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: AUTO

# 跨域配置
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost:5666,http://localhost:5666,https://localhost:8000,https://localhost:3000}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    com.baomidou.mybatisplus: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:./logs/law-firm-api.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:3GB}
    # 清理策略：保留30天日志，总容量限制3GB，自动删除旧日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# API文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    # 禁用base64编码，确保返回明文JSON
    json-base64-encoded: false
  swagger-ui:
    enabled: false
  # 内容类型配置
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.lawfirm
  show-actuator: false
  writer-with-default-pretty-printer: true
  api-docs.resolve-schema-properties: true
  default-support-form-data: true
  api-docs.version: OPENAPI_3_0

# Knife4j增强配置
knife4j:
  enable: ${KNIFE4J_ENABLE:true}
  production: false
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 数据模型
    enable-version: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2023-2025 XYZ Law Firm
    enable-host-submission: false
    enable-request-cache: true
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md
  documents:
    - group: 默认分组
      name: 接口文档
      locations: classpath:markdown/接口说明.md

# 系统参数配置
law-firm:
  # 安全配置
  security:
    jwt:
      secret: ${JWT_SECRET:lawfirm123456}
      expiration: ${JWT_EXPIRATION:86400}
  
  # API相关配置
  api:
    # API基础路径前缀
    base-path: /api
    # API版本控制
    version:
      enabled: true
      current: v1
    # 缓存配置
    cache:
      enabled: ${API_CACHE_ENABLED:true}
      default-ttl: ${API_CACHE_DEFAULT_TTL:3600}
    # 访问审计日志配置
    audit:
      enabled: ${API_AUDIT_ENABLED:true}
      exclude-paths: ${API_AUDIT_EXCLUDE_PATHS:/static/**,/webjars/**,/error/**,/favicon.ico,/actuator/**}
      sensitive-fields: ${API_AUDIT_SENSITIVE_FIELDS:password,secret,token,creditCard,idCard}
    # 限流配置
    rate-limit:
      enabled: ${RATE_LIMIT_ENABLED:true}
      ip-limit-enabled: ${IP_LIMIT_ENABLED:true}
      ip-limit-rate: ${IP_LIMIT_RATE:50}
      ip-limit-interval: ${IP_LIMIT_INTERVAL:1}
      ip-limit-paths:
        - /api/auth/login
    # 幂等性配置
    idempotent:
      enabled: ${IDEMPOTENT_ENABLED:true}
      default-expire-time: ${IDEMPOTENT_EXPIRE_TIME:60}
      auto-generate: ${IDEMPOTENT_AUTO_GENERATE:false}
    # 防重复提交配置
    repeat-submit:
      enabled: ${REPEAT_SUBMIT_ENABLED:true}
      default-interval: ${REPEAT_SUBMIT_INTERVAL:5000}
      user-based: ${REPEAT_SUBMIT_USER_BASED:true}
    # 分布式锁配置
    distributed-lock:
      enabled: ${DISTRIBUTED_LOCK_ENABLED:true}
      default-wait-time: ${DISTRIBUTED_LOCK_WAIT_TIME:5}
      default-lease-time: ${DISTRIBUTED_LOCK_LEASE_TIME:30}
  
  # 核心模块配置
  core:
    audit:
      enabled: true
  
  # 搜索服务配置
  search:
    enabled: true
    searchEngineType: lucene
    lucene:
      indexDir: ${user.home}/.law-firm/lucene-index
      ramBufferSizeMb: 32
      maxResults: 1000
      highlightEnabled: true
      highlightPreTag: <em>
      highlightPostTag: </em>
      analyzer: ik
  
  # 通用配置
  common:
    core:
      enabled: true
    web:
      enabled: true
    data:
      enabled: true
      module-init-enabled: true
    cache:
      enabled: true
    security:
      enabled: true
    log:
      enabled: true
      method-log: true
      log-request-params: true
      log-response-body: false
      enable-async-log: true
      executor:
        bean-name: taskExecutor
    message:
      enabled: true

# Actuator配置 - 简化
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    redis:
      enabled: false
