# 开发环境配置
spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:}}
    hikari:
      pool-name: HikariCP-Dev
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 数据库迁移配置 - 开发环境启用，以自动创建表结构
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration
    out-of-order: true

# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.lawfirm.common.data: DEBUG
    # 添加Flyway日志，以便查看SQL执行情况
    org.flywaydb: DEBUG

# 开发环境下禁用安全组件，方便测试
security:
  enabled: false

# 开发环境业务模块配置
lawfirm:
  # 搜索服务配置
  search:
    enabled: false
  # 存储服务配置
  storage:
    enabled: true
    defaultType: LOCAL
    path:
      baseDir: ${user.home}/.law-firm/storage
      tempDir: ${user.home}/.law-firm/storage/temp
  # 缓存配置
  cache:
    enabled: false
    type: LOCAL
  # 数据库服务 - 开发环境启用
  database:
    enabled: true 