spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-mysql}
  main:
    allow-bean-definition-overriding: true
    allow-missing-beans: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    jdbcUrl: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 
  flyway:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  autoconfigure:
    exclude:
      - org.flowable.spring.boot.FlowableAutoConfiguration
      - org.flowable.spring.boot.ProcessEngineServicesAutoConfiguration
      - org.flowable.spring.boot.actuate.endpoint.ProcessEngineEndpointAutoConfiguration
      - org.flowable.spring.boot.actuate.info.FlowableInfoAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineServicesAutoConfiguration
      - org.flowable.spring.boot.engine.FlowableEngineAutoConfiguration
      - org.flowable.spring.boot.EndpointAutoConfiguration
      - org.flowable.spring.boot.FlowableSecurityAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineServicesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.ldap.LdapRepositoriesAutoConfiguration
      - com.lawfirm.document.config.DocumentSearchConfig
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1
  data:
    jpa:
      repositories:
        enabled: false
    ldap:
      repositories:
        enabled: false
  sql:
    init:
      enabled: false
      mode: never
      platform: none

server:
  port: 8080
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

# 其他配置保持不变...

law:
  firm:
    log:
      enableMethodLog: true
      enableRequestLog: true
      logStackTrace: true

# API文档过滤器配置
api:
  doc:
    filter:
      enabled: false

# 应用信息配置
app:
  name: "law-firm-api"
  version: "1.0.0"
  description: "律师事务所管理系统API服务"

# API文档配置 - 只使用Knife4j
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  packages-to-scan: com.lawfirm
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  cache:
    disabled: true

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-search: true
    enable-debug: true
    enable-open-api: true
  production: false

# 搜索服务配置
lawfirm:
  search:
    enabled: true
    type: lucene
  module:
    knowledge:
      enabled: true
  storage:
    enabled: true
    defaultType: LOCAL
    defaultBucketId: 1
    path:
      baseDir: ${user.home}/.law-firm/storage
      tempDir: ${user.home}/.law-firm/storage/temp
      urlPrefix: http://localhost:8080/api/files
    local:
      enabled: true
      basePath: ${user.home}/.law-firm/storage
      urlPrefix: http://localhost:8080/api/files
    minio:
      enabled: false
      endpoint: http://minio.example.com
      port: 9000
      accessKey: minioadmin
      secretKey: minioadmin
      useSsl: false
  # AI模块配置
  ai:
    enabled: true
    defaultProvider: openai
    timeout: 30
    maxConcurrentRequests: 10
    enableCache: true
    enableSensitiveFilter: true
    enableRiskAssessment: true
    debug: false
  ai.model:
    openai:
      apiKey: ${AI_OPENAI_API_KEY:sk-demo-key}
      baseUrl: https://api.openai.com/v1
      defaultModel: gpt-4
    baidu:
      apiKey: ${AI_BAIDU_API_KEY:}
      secretKey: ${AI_BAIDU_SECRET_KEY:}
      baseUrl: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop
      defaultModel: ERNIE-Bot-4

# Lucene搜索配置
search:
  engine: lucene
  enabled: true
  lucene:
    index-dir: ${user.home}/.law-firm/lucene-index
    ram-buffer-size-mb: 32
    max-results: 1000
    highlight-enabled: true
    highlight-pre-tag: <em>
    highlight-post-tag: </em>
    analyzer: ik
  index:
    case:
      name: law_firm_case
    document:
      name: law_firm_document
    client:
      name: law_firm_client
    contract:
      name: law_firm_contract

# 健康检查配置
management:
  health:
    elasticsearch:
      enabled: false

# 知识库模块配置
knowledge:
  storage:
    basePath: ${user.home}/.law-firm/knowledge
    tempPath: ${user.home}/.law-firm/knowledge/temp
  document:
    maxSize: 10MB
    allowedExtensions: .doc,.docx,.pdf,.md,.txt
  attachment:
    maxSize: 20MB
    maxCountPerKnowledge: 10
    allowedExtensions: .doc,.docx,.pdf,.jpg,.png,.zip
  category:
    maxDepth: 3
  search:
    enableHighlight: true
    maxResultCount: 100
    minKeywordLength: 2
  statistic:
    cron: 0 0 1 * * ?

# 审计模块配置
audit:
  enabled: true
  async: true
  log-type: db
  include-request-params: true
  include-response-body: false

# 消息服务配置
message:
  enabled: true
  async:
    enabled: false  # 禁用异步消息，使用同步消息实现
  template:
    cache-enabled: true
    refresh-interval: 3600
