# 开发模式无Redis配置
# 用于开发环境下不依赖Redis的配置

# 开发模式标识
dev:
  use-redis: false
  auth:
    # 内存存储会话
    session-store: memory
    # 禁用Redis会话
    disable-redis: true
    # 简化安全配置
    simplified-security: true
    # 禁用原始安全配置
    disable-original-security: true
    
# 添加数据源配置避免主配置文件依赖
spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 
    type: com.zaxxer.hikari.HikariDataSource
  # 禁用Redis
  data:
    redis:
      enabled: false
  # 禁用Redis自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  # 我们已解决循环依赖问题，不再需要强制允许循环引用
  main:
    allow-bean-definition-overriding: true
  # 简化安全设置
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
    filter:
      dispatcher-types: REQUEST,ASYNC
    headers:
      frame: SAMEORIGIN
      xss: true

# 禁用Redisson配置
redisson:
  enabled: false

# 禁用原始安全配置
auth:
  security:
    enabled: false

# 添加Jasypt加密配置
jasypt:
  encryptor:
    password: your-secret-key
    algorithm: PBEWithMD5AndDES
    provider-name: SunJCE 

# 财务模块配置
finance:
  cache:
    enabled: false
    expireTime: 3600
  event:
    async: false
    retryTimes: 3
  business:
    maxPageSize: 100
    exportLimit: 1000

# 配置刷新设置
config:
  refresh:
    enabled: false
    refresh-interval: 60000
    refresh-on-startup: false
    source-type: file
    source-path: config/

# 缓存配置
law-firm:
  cache:
    enabled: false
    type: LOCAL
    expiration: 30
    refresh-time: 10

# 日志配置
lawfirm:
  log:
    enable-method-log: false
    enable-request-log: false
    enable-async-log: false
    enable-tracing: false
    log-request-params: true
    log-response-body: true
    log-stack-trace: true
    exclude-paths:
      - /swagger-ui/**
      - /v3/api-docs/** 