server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: law-firm-api
  security:
    user:
      name: admin
      password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs 