# 测试环境配置
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/law_firm_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${TEST_DB_USERNAME:root}
    password: ${TEST_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
    # 动态数据源配置，测试环境不启用
    dynamic:
      enabled: false
  # Redis配置
  data:
    redis:
      host: ${TEST_REDIS_HOST:localhost}
      port: ${TEST_REDIS_PORT:6379}
      database: 1  # 使用单独的库，避免影响开发环境
      password: ${TEST_REDIS_PASSWORD:}
  # 数据库迁移配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    out-of-order: true

# 日志配置 - 测试环境减少DEBUG日志
logging:
  level:
    root: INFO
    com.lawfirm: INFO  # 开发环境是DEBUG
    org.springframework: INFO
    org.springframework.web: INFO  # 开发环境是DEBUG
    com.lawfirm.common.data: INFO  # 开发环境是DEBUG
    # 保留Flyway日志，以便查看SQL执行情况
    org.flywaydb: INFO

# 启用基本安全组件
security:
  enabled: true
  ignore-urls:
    - "/favicon.ico"
    - "/error"
    - "/health"
    - "/version"
    - "/api/auth/login"
    - "/api/auth/logout"
    - "/api/auth/captcha"
    - "/api/docs/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

# 测试环境业务模块配置
lawfirm:
  # 搜索服务配置 - 测试环境开启
  search:
    enabled: true
    type: lucene
  # 存储服务配置
  storage:
    enabled: true
    defaultType: LOCAL
    path:
      baseDir: ${user.home}/.law-firm-test/storage
      tempDir: ${user.home}/.law-firm-test/storage/temp
  # 缓存配置 - 测试环境开启
  cache:
    enabled: true
    type: REDIS

# 管理端点配置 - 仅测试环境可见，生产环境会禁用
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 