spring:
  # 测试环境使用H2内存数据库
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:law_firm_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  
  # 测试环境禁用Redis，使用内存模拟
  data:
    redis:
      enabled: true
  
  # 测试环境每次启动清空数据库
  h2:
    console:
      enabled: true
      path: /h2-console
  
  flyway:
    enabled: true
    clean-on-validation-error: true
    clean-disabled: false

# 测试环境服务器配置
server:
  port: 8180  # 修复端口冲突，使用8180避免与客户模块冲突
  servlet:
    context-path: /

# 测试环境允许所有跨域
cors:
  allowed-origins: "*"

# 测试环境日志级别
logging:
  level:
    root: INFO
    com.lawfirm: DEBUG
    org.springframework: INFO
    org.springframework.test: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.flywaydb: DEBUG

# 测试环境MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 测试环境安全配置
law-firm:
  security:
    # 测试环境模拟用户
    mock-user:
      enabled: true
      username: test
      role: ROLE_USER
    # 测试环境禁用安全限制
    disable:
      csrf: true
      xss-filter: true
  
  # 测试环境OnlyOffice配置
  onlyoffice:
    enabled: ${ONLYOFFICE_ENABLED:false}  # 测试环境默认禁用
    url: ${ONLYOFFICE_URL:http://localhost:8088}
    secret: ${ONLYOFFICE_SECRET:lawfirm-onlyoffice-jwt-secret-test}
    header: ${ONLYOFFICE_HEADER:Authorization}
    callback-url: ${ONLYOFFICE_CALLBACK_URL:http://localhost:8180/api/v1/documents/onlyoffice/callback}
    max-file-size: ${ONLYOFFICE_MAX_FILE_SIZE:10485760}  # 10MB (测试环境限制)
    edit-timeout: ${ONLYOFFICE_EDIT_TIMEOUT:30}  # 30分钟
    supported-formats:
      - docx  # 测试环境只支持主要格式
      - xlsx
      - pptx
    co-edit:
      enabled: ${ONLYOFFICE_COEDIT_ENABLED:false}  # 测试环境禁用协同编辑
      max-users: ${ONLYOFFICE_COEDIT_MAX_USERS:2}
      auto-save-interval: ${ONLYOFFICE_COEDIT_AUTO_SAVE_INTERVAL:60}
  
  # 测试环境核心模块配置
  core:
    workflow:
      enabled: false
    storage:
      enabled: true
      type: memory
    search:
      enabled: true
      searchEngineType: database
      index-path: ./indices-test
    audit:
      enabled: true
  
  # 测试环境权限系统配置
  permission:
    # 测试环境可选择性启用权限验证
    validate: ${PERMISSION_VALIDATE:false}
    cache:
      # 测试环境启用缓存但使用很短的过期时间便于测试
      enabled: ${PERMISSION_CACHE_ENABLED:true}
      ttl: ${PERMISSION_CACHE_TTL:300}  # 5分钟
      max-size: ${PERMISSION_CACHE_MAX_SIZE:1000}
    management:
      # 测试环境启用权限管理功能便于测试
      enabled: ${PERMISSION_MANAGEMENT_ENABLED:true} 

# 测试环境API文档配置
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}

# 测试环境Knife4j配置
knife4j:
  enable: ${KNIFE4J_ENABLE:true}
  production: false