# Docker环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:law_firm}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:lawfirm_default}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: ${DB_MIN_IDLE:5}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      connection-test-query: SELECT 1
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:10s}
      lettuce:
        pool:
          min-idle: ${REDIS_MIN_IDLE:0}
          max-idle: ${REDIS_MAX_IDLE:8}
          max-active: ${REDIS_MAX_ACTIVE:8}
          max-wait: ${REDIS_MAX_WAIT:-1ms}
  
  # Flyway配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration,classpath:db/migration/modules
    table: flyway_schema_history
    encoding: UTF-8
    placeholders:
      schema: ${DB_NAME:law_firm}
    out-of-order: true
    ignore-migration-patterns: '*:missing'
  
  # 文件上传限制
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:50MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}

# 工作流配置
flowable:
  enabled: ${FLOWABLE_ENABLED:false}
  async-executor-activate: ${FLOWABLE_ASYNC_EXECUTOR_ACTIVATE:false}

# 自定义配置
lawfirm:
  # 搜索引擎配置
  search:
    enabled: ${LAWFIRM_SEARCH_ENABLED:true}
    type: ${LAWFIRM_SEARCH_TYPE:lucene}
  
  # 存储配置
  storage:
    enabled: ${LAWFIRM_STORAGE_ENABLED:true}
    defaultType: ${LAWFIRM_STORAGE_TYPE:LOCAL}
    path:
      baseDir: ${LAWFIRM_STORAGE_PATH:/app/storage}
      tempDir: ${LAWFIRM_STORAGE_TEMP_PATH:/app/storage/temp}
    local:
      enabled: true
      basePath: ${LAWFIRM_STORAGE_LOCAL_PATH:/app/storage}

# 日志配置
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lawfirm: ${LOGGING_LEVEL_APP:INFO}
    org.springframework: ${LOGGING_LEVEL_SPRING:WARN}
    com.zaxxer.hikari: ${LOGGING_LEVEL_HIKARI:INFO}
    org.apache.ibatis: ${LOGGING_LEVEL_MYBATIS:INFO}
  file:
    name: ${LOG_FILE:/app/logs/app.log} 