spring:
  # SQL初始化配置
  sql:
    init:
      mode: never
      
  # 禁用Flyway
  flyway:
    enabled: false
    
  # 配置导入
  config:
    import:
      - optional:classpath:/config/apidoc.yml
      
  # 安全配置
  security:
    basic:
      enabled: false
      
  # 允许Bean覆盖
  main:
    allow-bean-definition-overriding: true
    
# 开发模式配置
dev:
  auth:
    simplified-security: true
    
# API文档配置
api:
  doc:
    enabled: true
    
# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    
# Knife4j配置
knife4j:
  enable: true
  production: false
  
# 日志配置
logging:
  level:
    root: INFO
    com.lawfirm: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: TRACE
    
# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api 