spring:
  # 开发环境数据源 - 可以使用H2内存数据库方便开发
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/law_firm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    hikari:
      # 开发环境连接池配置
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      # 自动注册JMX监控
      register-mbeans: true
  
  # 开发环境禁用Redis，使用内存模拟
  data:
    redis:
      host: localhost
      port: 6379
  
  # 开发环境自动初始化数据库
  flyway:
    enabled: true
    clean-disabled: false
    # 确保在开发环境中禁用自动迁移
    validate-on-migrate: false
    auto-migrate: false

  # 任务执行器配置
  task:
    execution:
      enabled: true
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        thread-name-prefix: app-task-

# 开发环境服务器配置
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

# 开发环境允许所有跨域
cors:
  allowed-origins: "*"

# 开发环境日志级别
logging:
  level:
    root: DEBUG
    com.lawfirm: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.cache: INFO
    com.baomidou.mybatisplus: DEBUG
    org.flywaydb: DEBUG

# 开发环境启用API文档
# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true
#   show-actuator: false

# 开发环境禁用Redis健康检查
management:
  endpoint:
    health:
      validate-group-membership: false
  health:
    redis:
      enabled: false
    ldap:
      enabled: false
    mail:
      enabled: false
    rabbit:
      enabled: false
    defaults:
      enabled: true

# MyBatis Plus开发环境配置 
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启注解扫描
    use-generated-keys: true
    default-statement-timeout: 60
    map-underscore-to-camel-case: true
  # 添加Mapper接口扫描包路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 确保实体类包被扫描
  type-aliases-package: com.lawfirm.model
  # 配置Mapper扫描包
  mapper-scan-package: com.lawfirm.model.**.mapper
  # 实体类父类包配置
  super-entity: com.lawfirm.model.base.entity.BaseEntity
  # 启用全局ID类型为AUTO
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 开发环境安全配置
"law-firm":
  security:
    # 开发环境可以启用模拟用户
    "mock-user":
      enabled: true
      username: admin
      role: ROLE_ADMIN
    # 开发环境禁用某些安全限制
    disable:
      csrf: true
      "xss-filter": false
    # 开发环境启用密码解密（可选配置）
    "db-password":
      enabled: false
      "secret-key": DevSecretKey
  
  # 开发环境核心模块配置
  core:
    workflow:
      enabled: true
    storage:
      enabled: true  # 启用存储模块
      # 添加StorageManager实现类配置
      manager-class: com.lawfirm.core.storage.manager.DefaultStorageManager
      local:
        root-path: ./storage
    search:
      enabled: true
      searchEngineType: database
      "index-path": ./indices
    audit:
      enabled: false
      
  # 开发环境日志模块配置
  common:
    log:
      enabled: false
      executor:
        bean-name: taskExecutor
      
    # 开发环境数据库配置
    data:
      enabled: true
      "module-init-enabled": true
      "system-database": law_firm
      # 数据库监控
      monitoring:
        enabled: true
        performance:
          enabled: true