spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-mysql}
  main:
    allow-bean-definition-overriding: true
    allow-missing-beans: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 
  flyway:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  autoconfigure:
    exclude:
      - org.flowable.spring.boot.FlowableAutoConfiguration
      - org.flowable.spring.boot.ProcessEngineServicesAutoConfiguration
      - org.flowable.spring.boot.actuate.endpoint.ProcessEngineEndpointAutoConfiguration
      - org.flowable.spring.boot.actuate.info.FlowableInfoAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineAutoConfiguration
      - org.flowable.spring.boot.app.AppEngineServicesAutoConfiguration
      - org.flowable.spring.boot.engine.FlowableEngineAutoConfiguration
      - org.flowable.spring.boot.EndpointAutoConfiguration
      - org.flowable.spring.boot.FlowableSecurityAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineAutoConfiguration
      - org.flowable.spring.boot.idm.IdmEngineServicesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.ldap.LdapRepositoriesAutoConfiguration
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: deleted
        logic-not-delete-value: 0
        logic-delete-value: 1
  data:
    elasticsearch:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false
    ldap:
      repositories:
        enabled: false
    elasticsearch-reactive:
      repositories:
        enabled: false
  sql:
    init:
      enabled: false
      mode: never
      platform: none

server:
  port: 8080
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

# 其他配置保持不变...

law:
  firm:
    log:
      enableMethodLog: true
      enableRequestLog: true
      logStackTrace: true

# 应用信息配置
app:
  name: "law-firm-api"
  version: "1.0.0"
  description: "律师事务所管理系统API服务"

# API文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.lawfirm
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lawfirm

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: 
    enable-home-custom: false
    enable-search: true
    enable-footer: false
    enable-footer-custom: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  production: false
  basic:
    enable: false
  documents:
    - name: 接口文档
      locations: classpath:markdown/*
  cors: true
