spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:law_firm}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100
    connection-timeout: 30000
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    session:
      timeout: 1800s

# 接口文档配置
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:false}
    path: /api-docs

# API文档访问凭据
api:
  doc:
    username: ${API_DOC_USERNAME:admin}
    password: ${API_DOC_PASSWORD:ComplexP@ssw0rd}

# 安全配置
security:
  jwt:
    token-expiration-seconds: 86400
    refresh-token-expiration-seconds: 604800
    token-secret: ${JWT_SECRET:defaultsecretkey12345678901234567890}
  password:
    check-strength: true
    min-length: 8
    require-special-chars: true
    require-digits: true
    require-uppercase: true

# 日志配置
logging:
  file:
    path: ${LOG_PATH:/var/log/law-firm}
  level:
    root: warn
    com.lawfirm: info
    org.springframework: WARN

# 文件存储配置
file:
  storage:
    type: ${FILE_STORAGE_TYPE:local}
    local:
      path: ${FILE_STORAGE_PATH:/data/law-firm/files}
    oss:
      endpoint: ${OSS_ENDPOINT:}
      access-key: ${OSS_ACCESS_KEY:}
      secret-key: ${OSS_SECRET_KEY:}
      bucket-name: ${OSS_BUCKET_NAME:}

# 缓存配置
cache:
  ttl:
    default: 3600
    user: 1800
    menu: 7200

# 请求速率限制
rate-limit:
  enabled: true
  default-limit: 100
  ip-limit: 50
  burst: 20

# 方法安全
method:
  security:
    enabled: true 