spring:
  # 数据源配置
  datasource:
    dynamic:
      datasource:
        document:
          url: ${spring.datasource.master.url}
          username: ${spring.datasource.master.username}
          password: ${spring.datasource.master.password}
          driver-class-name: ${spring.datasource.master.driver-class-name}
  
  # Flyway数据库迁移配置
  flyway:
    enabled: true
    locations: classpath:META-INF/db/migration
    baseline-on-migrate: true
    baseline-version: 6000
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history_document
  
  # SQL脚本执行配置
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
      schema-locations: classpath:META-INF/db/migration/V*.sql
      continue-on-error: true

# 律师事务所系统核心配置
lawfirm:
  storage:
    enabled: true  # 启用存储服务 (无连字符)
  
law-firm:
  storage:
    enabled: true  # 启用存储服务 (有连字符)
  core:
    storage:
      enabled: true  # 启用核心存储服务 