spring:
  datasource:
    url: jdbc:mysql://localhost:3306/law_firm_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true

logging:
  level:
    com.lawfirm.document: debug
    org.hibernate.SQL: debug

document:
  storage:
    base-path: D:/data/documents
    temp-path: D:/data/documents/temp 