# 文档管理模块基础配置
spring:
  application:
    name: law-firm-document
  profiles:
    # 默认激活开发环境
    active: ${SPRING_PROFILES_ACTIVE:dev}
    # 引入文档管理模块特定配置
    include: document

# 服务器配置
server:
  # 服务端口
  port: ${DOCUMENT_SERVER_PORT:8084}
  servlet:
    # 上下文路径
    context-path: ${DOCUMENT_CONTEXT_PATH:/api/document}

# 日志配置
logging:
  level:
    # 文档模块日志级别
    com.lawfirm.document: ${DOCUMENT_LOG_LEVEL:DEBUG}
    # Spring框架日志级别
    org.springframework: INFO