spring:
  # 数据源配置
  datasource:
    dynamic:
      datasource:
        document:
          url: ${spring.datasource.master.url}
          username: ${spring.datasource.master.username}
          password: ${spring.datasource.master.password}
          driver-class-name: ${spring.datasource.master.driver-class-name}
  
  # SQL脚本执行配置
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
      schema-locations: classpath:db/migration/V*.sql
      continue-on-error: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 文档模块配置
document:
  # 存储配置
  storage:
    # 默认存储类型：LOCAL, OSS, S3
    default-type: ${DOCUMENT_STORAGE_TYPE:LOCAL}
    # 本地存储路径
    local-path: ${DOCUMENT_LOCAL_PATH:${user.home}/lawfirm/document}
    # 临时文件存储路径
    temp-path: ${DOCUMENT_TEMP_PATH:${java.io.tmpdir}/document-temp}
    # 文件访问基础URL
    base-url: ${DOCUMENT_BASE_URL:/api/document/file}
    # 预览文件访问URL
    preview-url: ${DOCUMENT_PREVIEW_URL:/api/document/preview}
    # 允许的文件类型
    allowed-types: ${DOCUMENT_ALLOWED_TYPES:doc,docx,pdf,txt,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip,rar}
    # 最大文件大小（字节）
    max-size: ${DOCUMENT_MAX_SIZE:104857600}
  
  # 预览配置
  preview:
    # 是否启用水印
    watermark-enabled: ${DOCUMENT_WATERMARK_ENABLED:true}
    # 水印文字
    watermark-text: ${DOCUMENT_WATERMARK_TEXT:预览版本，仅供查看}
    # 是否启用转换
    convert-enabled: ${DOCUMENT_CONVERT_ENABLED:true}
    # 支持预览的文件类型
    supported-types: ${DOCUMENT_PREVIEW_TYPES:pdf,doc,docx,xls,xlsx,ppt,pptx,txt,jpg,jpeg,png,gif}

  # 版本控制
  version:
    # 是否启用版本控制
    enabled: ${DOCUMENT_VERSION_ENABLED:true}
    # 最大保留版本数
    max-count: ${DOCUMENT_VERSION_MAX_COUNT:10}

  # 分享配置
  share:
    # 默认过期时间（小时）
    default-expire-hours: ${DOCUMENT_SHARE_EXPIRE:24}
    # 最大过期时间（小时）
    max-expire-hours: ${DOCUMENT_SHARE_MAX_EXPIRE:720}
    # 是否启用密码保护
    password-protection: ${DOCUMENT_SHARE_PASSWORD:true}

# 定时任务配置
scheduling:
  enabled: ${SCHEDULING_ENABLED:true}
  # Cron表达式
  cleanup-temp-files: ${SCHEDULING_CLEANUP_TEMP:0 0 2 * * ?}
  calculate-storage-usage: ${SCHEDULING_STORAGE_USAGE:0 0 3 * * ?}
  rebuild-document-index: ${SCHEDULING_REBUILD_INDEX:0 0 1 ? * SUN}
  optimize-search-index: ${SCHEDULING_OPTIMIZE_INDEX:0 0 4 * * ?}
  cleanup-expired-documents: ${SCHEDULING_CLEANUP_EXPIRED:0 0 5 * * ?}
  cleanup-operation-logs: ${SCHEDULING_CLEANUP_LOGS:0 0 6 1 * ?} 