CREATE TABLE `client` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `client_no` varchar(32) NOT NULL COMMENT '客户编号',
  `client_name` varchar(100) NOT NULL COMMENT '客户名称',
  `client_type` tinyint NOT NULL COMMENT '客户类型（1:个人、2:企业）',
  `certificate_type` tinyint NOT NULL COMMENT '证件类型（1:身份证、2:护照、3:营业执照）',
  `certificate_no` varchar(50) NOT NULL COMMENT '证件号码',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) DEFAULT NULL COMMENT '电子邮箱',
  `address` varchar(255) DEFAULT NULL COMMENT '联系地址',
  `status` tinyint NOT NULL COMMENT '客户状态（1:潜在、2:正式、3:流失）',
  `lawyer_id` bigint DEFAULT NULL COMMENT '所属律师ID',
  `source_channel` tinyint DEFAULT NULL COMMENT '来源渠道（1:自主开发、2:同行推荐、3:客户介绍、4:网络推广、5:其他）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建者',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_no` (`client_no`),
  UNIQUE KEY `uk_certificate_no` (`certificate_no`),
  KEY `idx_lawyer_id` (`lawyer_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户表'; 