-- 案件模块表结构初始化
-- 版本: V7001
-- 模块: case
-- 创建时间: 2023-10-01
-- 说明: 创建案件管理模块相关表结构，基于实体类定义

-- 设置字符集和数据库选项
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- case_info表（案件基本信息表）
CREATE TABLE IF NOT EXISTS case_info (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  case_name VARCHAR(200) NOT NULL COMMENT '案件名称',
  case_description TEXT COMMENT '案件描述',
  case_type INTEGER COMMENT '案件类型',
  case_status INTEGER DEFAULT 0 COMMENT '案件状态（0-待受理 1-进行中 2-已结案 3-已关闭）',
  case_progress INTEGER COMMENT '案件进展',
  case_stage INTEGER COMMENT '案件阶段',
  case_difficulty INTEGER COMMENT '案件难度',
  case_importance INTEGER COMMENT '案件重要性',
  case_priority INTEGER COMMENT '案件优先级',
  case_source INTEGER COMMENT '案件来源',
  handle_type INTEGER COMMENT '办理方式',
  fee_type INTEGER COMMENT '收费类型',
  estimated_amount DECIMAL(12,2) COMMENT '预估金额',
  actual_amount DECIMAL(12,2) COMMENT '实际金额',
  client_id BIGINT COMMENT '委托人ID',
  client_name VARCHAR(100) COMMENT '委托人名称',
  opposing_party VARCHAR(100) COMMENT '对方当事人',
  lawyer_id BIGINT COMMENT '主办律师ID',
  lawyer_name VARCHAR(50) COMMENT '主办律师姓名',
  department_id BIGINT COMMENT '部门ID',
  department_name VARCHAR(50) COMMENT '部门名称',
  court_name VARCHAR(100) COMMENT '法院/仲裁机构',
  judge_name VARCHAR(50) COMMENT '法官/仲裁员',
  court_case_number VARCHAR(100) COMMENT '案号',
  filing_time DATE COMMENT '立案时间',
  closing_time DATE COMMENT '结案时间',
  expected_closing_time DATE COMMENT '预计结案时间',
  case_result INTEGER COMMENT '案件结果',
  case_tags VARCHAR(255) COMMENT '案件标签，多个标签以逗号分隔',
  has_conflict BOOLEAN DEFAULT FALSE COMMENT '是否有利益冲突',
  conflict_description VARCHAR(500) COMMENT '冲突说明',
  is_confidential BOOLEAN DEFAULT FALSE COMMENT '是否需要保密',
  confidential_level INTEGER COMMENT '保密级别',
  remarks VARCHAR(500) COMMENT '备注',
  last_operation_time DATETIME COMMENT '最后操作时间',
  last_operator_id BIGINT COMMENT '最后操作人ID',
  last_operator_name VARCHAR(50) COMMENT '最后操作人姓名',
  process_instance_id VARCHAR(64) COMMENT '流程实例ID',
  leader_id BIGINT COMMENT '负责人ID',
  client_status VARCHAR(50) COMMENT '客户状态',
  risk_status INTEGER COMMENT '风险状态',
  risk_reason VARCHAR(500) COMMENT '风险原因',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_case_number (case_number),
  KEY idx_case_name (case_name),
  KEY idx_case_type (case_type),
  KEY idx_case_status (case_status),
  KEY idx_client_id (client_id),
  KEY idx_lawyer_id (lawyer_id),
  KEY idx_filing_time (filing_time),
  KEY idx_closing_time (closing_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件基本信息表';

-- case_team表（案件团队表）
CREATE TABLE IF NOT EXISTS case_team (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  case_name VARCHAR(200) COMMENT '案件名称',
  member_id BIGINT NOT NULL COMMENT '团队成员ID（律师ID）',
  member_name VARCHAR(50) NOT NULL COMMENT '团队成员姓名',
  member_role INTEGER NOT NULL COMMENT '团队成员角色',
  department_id BIGINT COMMENT '部门ID',
  department_name VARCHAR(50) COMMENT '部门名称',
  responsibility VARCHAR(500) COMMENT '负责内容',
  workload_percentage DECIMAL(5,2) COMMENT '工作量占比（百分比）',
  profit_percentage DECIMAL(5,2) COMMENT '收益分配比例（百分比）',
  join_time DATETIME COMMENT '加入时间',
  exit_time DATETIME COMMENT '退出时间',
  is_primary BOOLEAN DEFAULT FALSE COMMENT '是否为主要负责人',
  operation_permission INTEGER DEFAULT 0 COMMENT '操作权限（0-只读，1-编辑，2-管理）',
  view_permission INTEGER DEFAULT 0 COMMENT '查看权限（0-全部，1-部分，2-仅自己负责部分）',
  receive_notification BOOLEAN DEFAULT TRUE COMMENT '是否接收通知',
  notification_frequency INTEGER DEFAULT 0 COMMENT '通知频率（0-实时，1-每日，2-每周）',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_case_member (case_id, member_id),
  KEY idx_case_id (case_id),
  KEY idx_member_id (member_id),
  KEY idx_member_role (member_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件团队表';

-- case_participant表（案件参与方表）
CREATE TABLE IF NOT EXISTS case_participant (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  participant_type INTEGER NOT NULL COMMENT '参与方类型',
  participant_name VARCHAR(100) NOT NULL COMMENT '参与方名称（个人姓名或组织名称）',
  role_description VARCHAR(255) COMMENT '参与方角色说明',
  contact_person VARCHAR(50) COMMENT '联系人',
  contact_phone VARCHAR(20) COMMENT '联系电话',
  contact_email VARCHAR(100) COMMENT '联系邮箱',
  contact_address VARCHAR(255) COMMENT '联系地址',
  id_type INTEGER COMMENT '证件类型（1-身份证，2-护照，3-营业执照，4-其他）',
  id_number VARCHAR(50) COMMENT '证件号码',
  is_organization BOOLEAN DEFAULT FALSE COMMENT '是否为组织/公司',
  organization_type VARCHAR(50) COMMENT '组织类型（企业、政府机构、社会组织等）',
  legal_representative VARCHAR(50) COMMENT '法定代表人',
  social_credit_code VARCHAR(30) COMMENT '统一社会信用代码',
  is_primary BOOLEAN DEFAULT FALSE COMMENT '是否为主要参与方',
  need_notification BOOLEAN DEFAULT FALSE COMMENT '是否需要通知',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_participant_type (participant_type),
  KEY idx_participant_name (participant_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件参与方表';

-- case_task表（案件任务表）
CREATE TABLE IF NOT EXISTS case_task (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  task_title VARCHAR(200) NOT NULL COMMENT '任务标题',
  task_type INTEGER COMMENT '任务类型',
  task_status INTEGER DEFAULT 0 COMMENT '任务状态',
  task_priority INTEGER DEFAULT 0 COMMENT '任务优先级',
  task_description TEXT COMMENT '任务描述',
  start_time DATETIME COMMENT '开始时间',
  deadline DATETIME COMMENT '截止时间',
  completion_time DATETIME COMMENT '完成时间',
  estimated_hours DOUBLE COMMENT '预计工时（小时）',
  actual_hours DOUBLE COMMENT '实际工时（小时）',
  creator_id BIGINT COMMENT '创建人ID',
  creator_name VARCHAR(50) COMMENT '创建人姓名',
  assignee_id BIGINT COMMENT '负责人ID',
  assignee_name VARCHAR(50) COMMENT '负责人姓名',
  collaborator_ids VARCHAR(255) COMMENT '协作人IDs（逗号分隔）',
  collaborator_names VARCHAR(255) COMMENT '协作人姓名（逗号分隔）',
  parent_task_id BIGINT COMMENT '父任务ID',
  progress_percentage INTEGER DEFAULT 0 COMMENT '进度百分比（0-100）',
  need_review BOOLEAN DEFAULT FALSE COMMENT '是否需要审核',
  reviewer_id BIGINT COMMENT '审核人ID',
  reviewer_name VARCHAR(50) COMMENT '审核人姓名',
  review_time DATETIME COMMENT '审核时间',
  review_opinion VARCHAR(500) COMMENT '审核意见',
  need_reminder BOOLEAN DEFAULT FALSE COMMENT '是否需要提醒',
  reminder_time DATETIME COMMENT '提醒时间',
  is_reminded BOOLEAN DEFAULT FALSE COMMENT '是否已提醒',
  document_ids VARCHAR(255) COMMENT '关联文档IDs（逗号分隔）',
  event_ids VARCHAR(255) COMMENT '关联事件IDs（逗号分隔）',
  tags VARCHAR(255) COMMENT '标签（逗号分隔）',
  remarks VARCHAR(500) COMMENT '备注',
  workflow_task_id VARCHAR(64) COMMENT '工作流任务ID',
  pause_reason VARCHAR(255) COMMENT '暂停原因',
  cancel_reason VARCHAR(255) COMMENT '取消原因',
  completion_note VARCHAR(500) COMMENT '完成备注',
  progress_note VARCHAR(500) COMMENT '进度备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_task_status (task_status),
  KEY idx_task_priority (task_priority),
  KEY idx_assignee_id (assignee_id),
  KEY idx_deadline (deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件任务表';

-- case_document表（案件文档表）
CREATE TABLE IF NOT EXISTS case_document (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  document_name VARCHAR(200) NOT NULL COMMENT '文档名称',
  document_type INTEGER COMMENT '文档类型',
  document_status INTEGER DEFAULT 0 COMMENT '文档状态',
  security_level INTEGER DEFAULT 0 COMMENT '文档安全级别',
  document_path VARCHAR(500) COMMENT '文档路径',
  document_format VARCHAR(20) COMMENT '文档格式',
  document_size BIGINT COMMENT '文档大小（字节）',
  document_description TEXT COMMENT '文档描述',
  document_keywords VARCHAR(255) COMMENT '文档关键词',
  version_number VARCHAR(20) DEFAULT '1.0' COMMENT '版本号',
  is_latest_version BOOLEAN DEFAULT TRUE COMMENT '是否为最新版本',
  previous_version_id BIGINT COMMENT '上一版本ID',
  creator_id BIGINT COMMENT '创建人ID',
  creator_name VARCHAR(50) COMMENT '创建人姓名',
  last_modifier_id BIGINT COMMENT '最后修改人ID',
  last_modifier_name VARCHAR(50) COMMENT '最后修改人姓名',
  last_modified_time DATETIME COMMENT '最后修改时间',
  is_encrypted BOOLEAN DEFAULT FALSE COMMENT '是否加密',
  encryption_method VARCHAR(50) COMMENT '加密方式',
  need_review BOOLEAN DEFAULT FALSE COMMENT '是否需要审核',
  reviewer_id BIGINT COMMENT '审核人ID',
  reviewer_name VARCHAR(50) COMMENT '审核人姓名',
  review_time DATETIME COMMENT '审核时间',
  review_opinion VARCHAR(500) COMMENT '审核意见',
  is_external BOOLEAN DEFAULT FALSE COMMENT '是否对外提供',
  is_archived BOOLEAN DEFAULT FALSE COMMENT '是否归档',
  archive_time DATETIME COMMENT '归档时间',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_document_type (document_type),
  KEY idx_document_status (document_status),
  KEY idx_security_level (security_level),
  KEY idx_creator_id (creator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件文档表';

-- case_event表（案件事件表）
CREATE TABLE IF NOT EXISTS case_event (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  event_title VARCHAR(200) NOT NULL COMMENT '事件标题',
  event_type INTEGER COMMENT '事件类型',
  event_status INTEGER DEFAULT 0 COMMENT '事件状态',
  event_description TEXT COMMENT '事件描述',
  event_time DATETIME NOT NULL COMMENT '事件时间',
  event_location VARCHAR(255) COMMENT '事件地点',
  event_duration INTEGER COMMENT '事件持续时间（分钟）',
  is_all_day BOOLEAN DEFAULT FALSE COMMENT '是否全天事件',
  organizer_id BIGINT COMMENT '组织者ID',
  organizer_name VARCHAR(50) COMMENT '组织者姓名',
  participant_ids VARCHAR(255) COMMENT '参与者IDs（逗号分隔）',
  participant_names VARCHAR(255) COMMENT '参与者姓名（逗号分隔）',
  need_reminder BOOLEAN DEFAULT FALSE COMMENT '是否需要提醒',
  reminder_time DATETIME COMMENT '提醒时间',
  is_reminded BOOLEAN DEFAULT FALSE COMMENT '是否已提醒',
  recurrence_rule VARCHAR(255) COMMENT '重复规则',
  recurrence_end_time DATETIME COMMENT '重复结束时间',
  parent_event_id BIGINT COMMENT '父事件ID',
  document_ids VARCHAR(255) COMMENT '关联文档IDs（逗号分隔）',
  task_ids VARCHAR(255) COMMENT '关联任务IDs（逗号分隔）',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_event_type (event_type),
  KEY idx_event_status (event_status),
  KEY idx_event_time (event_time),
  KEY idx_organizer_id (organizer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件事件表';

-- case_fee表（案件费用表）
CREATE TABLE IF NOT EXISTS case_fee (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  fee_name VARCHAR(100) NOT NULL COMMENT '费用名称',
  fee_type INTEGER COMMENT '费用类型',
  fee_amount DECIMAL(12,2) NOT NULL COMMENT '费用金额',
  currency VARCHAR(10) DEFAULT 'CNY' COMMENT '费用币种',
  fee_status INTEGER DEFAULT 0 COMMENT '费用状态',
  occurrence_time DATETIME COMMENT '发生时间',
  payment_time DATETIME COMMENT '支付时间',
  payment_method VARCHAR(50) COMMENT '支付方式',
  payer_id BIGINT COMMENT '支付人ID',
  payer_name VARCHAR(50) COMMENT '支付人姓名',
  receiver_id BIGINT COMMENT '收款人ID',
  receiver_name VARCHAR(50) COMMENT '收款人姓名',
  receipt_number VARCHAR(50) COMMENT '票据编号',
  receipt_type VARCHAR(50) COMMENT '票据类型',
  is_reimbursable BOOLEAN DEFAULT FALSE COMMENT '是否可报销',
  reimbursement_status INTEGER COMMENT '报销状态',
  reimbursement_time DATETIME COMMENT '报销时间',
  is_recurring BOOLEAN DEFAULT FALSE COMMENT '是否recurring费用',
  recurrence_period VARCHAR(50) COMMENT '重复周期',
  recurrence_end_time DATETIME COMMENT '重复结束时间',
  fee_description TEXT COMMENT '费用描述',
  attachment_ids VARCHAR(255) COMMENT '附件IDs（逗号分隔）',
  approver_id BIGINT COMMENT '审批人ID',
  approver_name VARCHAR(50) COMMENT '审批人姓名',
  approval_time DATETIME COMMENT '审批时间',
  approval_status INTEGER COMMENT '审批状态',
  approval_opinion VARCHAR(500) COMMENT '审批意见',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_fee_type (fee_type),
  KEY idx_fee_status (fee_status),
  KEY idx_occurrence_time (occurrence_time),
  KEY idx_payment_time (payment_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件费用表';

-- case_contract_relation表（案件合同关联表）
CREATE TABLE IF NOT EXISTS case_contract_relation (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  contract_number VARCHAR(50) NOT NULL COMMENT '合同编号',
  relation_type INTEGER COMMENT '关联类型',
  relation_description VARCHAR(255) COMMENT '关联描述',
  is_primary BOOLEAN DEFAULT FALSE COMMENT '是否为主要关联',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_case_contract (case_id, contract_id),
  KEY idx_case_id (case_id),
  KEY idx_contract_id (contract_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件合同关联表';

-- 案件团队成员表（成员与角色的关联表）
CREATE TABLE IF NOT EXISTS case_team_member (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  team_id BIGINT NOT NULL COMMENT '团队ID',
  member_id BIGINT NOT NULL COMMENT '成员ID',
  member_name VARCHAR(50) NOT NULL COMMENT '成员姓名',
  join_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
  exit_time DATETIME COMMENT '退出时间',
  position VARCHAR(50) COMMENT '职位',
  responsibility VARCHAR(255) COMMENT '职责',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_team_member (team_id, member_id),
  KEY idx_case_id (case_id),
  KEY idx_member_id (member_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件团队成员表';

-- 案件任务分配表
CREATE TABLE IF NOT EXISTS case_assignment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  assignee_id BIGINT NOT NULL COMMENT '受理人ID',
  assignee_name VARCHAR(50) NOT NULL COMMENT '受理人姓名',
  assigner_id BIGINT COMMENT '分配人ID',
  assigner_name VARCHAR(50) COMMENT '分配人姓名',
  assignment_time DATETIME COMMENT '分配时间',
  acceptance_time DATETIME COMMENT '接受时间',
  completion_time DATETIME COMMENT '完成时间',
  assignment_status INTEGER DEFAULT 0 COMMENT '分配状态',
  work_hours DOUBLE COMMENT '工作时长（小时）',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_assignee (task_id, assignee_id),
  KEY idx_case_id (case_id),
  KEY idx_assignee_id (assignee_id),
  KEY idx_assignment_status (assignment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件任务分配表';

-- 案件备注表
CREATE TABLE IF NOT EXISTS case_note (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  case_id BIGINT NOT NULL COMMENT '案件ID',
  case_number VARCHAR(50) NOT NULL COMMENT '案件编号',
  note_title VARCHAR(200) COMMENT '备注标题',
  note_content TEXT NOT NULL COMMENT '备注内容',
  note_type INTEGER COMMENT '备注类型',
  creator_id BIGINT COMMENT '创建人ID',
  creator_name VARCHAR(50) COMMENT '创建人姓名',
  is_important BOOLEAN DEFAULT FALSE COMMENT '是否重要',
  is_private BOOLEAN DEFAULT FALSE COMMENT '是否私密',
  visible_to VARCHAR(500) COMMENT '可见范围（用户IDs，逗号分隔）',
  related_entity_type VARCHAR(50) COMMENT '关联实体类型',
  related_entity_id BIGINT COMMENT '关联实体ID',
  tags VARCHAR(255) COMMENT '标签（逗号分隔）',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_creator_id (creator_id),
  KEY idx_note_type (note_type),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件备注表';

-- 恢复外键约束
SET FOREIGN_KEY_CHECKS = 1;
