-- 财务模块表结构初始化
-- 版本: V8001
-- 模块: finance
-- 创建时间: 2023-10-01
-- 说明: 创建财务管理模块相关表结构，基于实体类定义

-- 设置字符集和数据库选项
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- fin_account表（账户表）
CREATE TABLE IF NOT EXISTS fin_account (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  account_number VARCHAR(32) NOT NULL COMMENT '账户编号',
  account_name VARCHAR(100) NOT NULL COMMENT '账户名称',
  account_type VARCHAR(20) NOT NULL COMMENT '账户类型',
  account_status VARCHAR(20) NOT NULL COMMENT '账户状态',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  balance DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '账户余额',
  frozen_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '冻结金额',
  available_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '可用金额',
  credit_limit DECIMAL(12,2) DEFAULT 0.00 COMMENT '信用额度',
  bank_name VARCHAR(100) COMMENT '开户行',
  bank_account VARCHAR(32) COMMENT '银行账号',
  account_holder VARCHAR(50) COMMENT '开户人',
  client_id BIGINT COMMENT '关联客户ID',
  department_id BIGINT COMMENT '关联部门ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_account_number (account_number),
  KEY idx_account_name (account_name),
  KEY idx_client_id (client_id),
  KEY idx_department_id (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账户表';

-- fin_transaction表（交易表）
CREATE TABLE IF NOT EXISTS fin_transaction (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  transaction_number VARCHAR(32) NOT NULL COMMENT '交易编号',
  transaction_type VARCHAR(20) NOT NULL COMMENT '交易类型',
  amount DECIMAL(12,2) NOT NULL COMMENT '交易金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  transaction_time DATETIME NOT NULL COMMENT '交易时间',
  from_account_id BIGINT COMMENT '付款账户ID',
  to_account_id BIGINT COMMENT '收款账户ID',
  business_id BIGINT COMMENT '关联业务ID',
  business_type VARCHAR(50) COMMENT '关联业务类型',
  summary VARCHAR(200) COMMENT '交易摘要',
  transaction_remark VARCHAR(500) COMMENT '交易备注',
  department_id BIGINT COMMENT '部门ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_transaction_number (transaction_number),
  KEY idx_transaction_type (transaction_type),
  KEY idx_transaction_time (transaction_time),
  KEY idx_from_account_id (from_account_id),
  KEY idx_to_account_id (to_account_id),
  KEY idx_business_id (business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易表';

-- fin_invoice表（发票表）
CREATE TABLE IF NOT EXISTS fin_invoice (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  invoice_number VARCHAR(50) NOT NULL COMMENT '发票编号',
  invoice_type VARCHAR(20) NOT NULL COMMENT '发票类型',
  invoice_status VARCHAR(20) NOT NULL COMMENT '发票状态',
  amount DECIMAL(12,2) NOT NULL COMMENT '发票金额',
  law_firm_id BIGINT COMMENT '律所ID',
  case_id BIGINT COMMENT '案件ID',
  client_id BIGINT COMMENT '客户ID',
  title VARCHAR(200) NOT NULL COMMENT '发票抬头',
  content VARCHAR(500) COMMENT '发票内容',
  issue_time DATETIME COMMENT '开票时间',
  issued_by VARCHAR(50) COMMENT '开票人',
  taxpayer_number VARCHAR(50) COMMENT '纳税人识别号',
  registered_address VARCHAR(200) COMMENT '注册地址',
  registered_phone VARCHAR(50) COMMENT '注册电话',
  bank_name VARCHAR(100) COMMENT '开户银行',
  bank_account VARCHAR(50) COMMENT '银行账号',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoice_number (invoice_number),
  KEY idx_invoice_type (invoice_type),
  KEY idx_invoice_status (invoice_status),
  KEY idx_case_id (case_id),
  KEY idx_client_id (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发票表';

-- fin_receivable表（应收账款表）
CREATE TABLE IF NOT EXISTS fin_receivable (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  receivable_no VARCHAR(32) NOT NULL COMMENT '应收账款编号',
  receivable_name VARCHAR(100) NOT NULL COMMENT '应收账款名称',
  contract_id BIGINT NOT NULL COMMENT '关联合同ID',
  contract_no VARCHAR(32) NOT NULL COMMENT '合同编号',
  total_amount DECIMAL(12,2) NOT NULL COMMENT '应收总金额',
  received_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '已收金额',
  unreceived_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '未收金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  credit_period INTEGER COMMENT '账期（天）',
  expected_receipt_date DATETIME COMMENT '预计收款日期',
  overdue_days INTEGER DEFAULT 0 COMMENT '逾期天数',
  status INTEGER NOT NULL COMMENT '应收款状态',
  payment_plan_id BIGINT COMMENT '关联付款计划ID',
  case_id BIGINT COMMENT '关联案件ID',
  client_id BIGINT NOT NULL COMMENT '关联客户ID',
  lawyer_id BIGINT COMMENT '负责律师ID',
  department_id BIGINT COMMENT '部门ID',
  last_receipt_date DATETIME COMMENT '最近收款日期',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_receivable_no (receivable_no),
  KEY idx_contract_id (contract_id),
  KEY idx_case_id (case_id),
  KEY idx_client_id (client_id),
  KEY idx_status (status),
  KEY idx_expected_receipt_date (expected_receipt_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应收账款表';

-- fin_payment表（付款表）
CREATE TABLE IF NOT EXISTS fin_payment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  payment_no VARCHAR(32) NOT NULL COMMENT '付款编号',
  payment_type VARCHAR(20) NOT NULL COMMENT '付款类型',
  amount DECIMAL(12,2) NOT NULL COMMENT '付款金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  payment_status VARCHAR(20) NOT NULL COMMENT '付款状态',
  payment_time DATETIME COMMENT '付款时间',
  payer_account_id BIGINT COMMENT '付款账户ID',
  payee_account_id BIGINT COMMENT '收款账户ID',
  payer_name VARCHAR(100) COMMENT '付款方名称',
  payee_name VARCHAR(100) COMMENT '收款方名称',
  payment_method VARCHAR(20) COMMENT '付款方式',
  transaction_id BIGINT COMMENT '关联交易ID',
  business_id BIGINT COMMENT '关联业务ID',
  business_type VARCHAR(50) COMMENT '关联业务类型',
  approval_status VARCHAR(20) COMMENT '审批状态',
  approver_id BIGINT COMMENT '审批人ID',
  approval_time DATETIME COMMENT '审批时间',
  department_id BIGINT COMMENT '部门ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_no (payment_no),
  KEY idx_payment_type (payment_type),
  KEY idx_payment_status (payment_status),
  KEY idx_payment_time (payment_time),
  KEY idx_business_id (business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='付款表';

-- fin_billing表（账单表）
CREATE TABLE IF NOT EXISTS fin_billing (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  billing_no VARCHAR(32) NOT NULL COMMENT '账单编号',
  billing_name VARCHAR(100) NOT NULL COMMENT '账单名称',
  billing_type VARCHAR(20) NOT NULL COMMENT '账单类型',
  billing_status VARCHAR(20) NOT NULL COMMENT '账单状态',
  total_amount DECIMAL(12,2) NOT NULL COMMENT '账单总金额',
  paid_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '已付金额',
  unpaid_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '未付金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  billing_date DATETIME NOT NULL COMMENT '账单日期',
  due_date DATETIME COMMENT '到期日期',
  client_id BIGINT NOT NULL COMMENT '客户ID',
  contract_id BIGINT COMMENT '合同ID',
  case_id BIGINT COMMENT '案件ID',
  billing_period_start DATETIME COMMENT '账单周期开始时间',
  billing_period_end DATETIME COMMENT '账单周期结束时间',
  payment_terms VARCHAR(200) COMMENT '付款条件',
  invoice_status VARCHAR(20) COMMENT '发票状态',
  invoice_id BIGINT COMMENT '关联发票ID',
  department_id BIGINT COMMENT '部门ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_billing_no (billing_no),
  KEY idx_billing_type (billing_type),
  KEY idx_billing_status (billing_status),
  KEY idx_client_id (client_id),
  KEY idx_contract_id (contract_id),
  KEY idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账单表';

-- fin_billing_record表（账单记录表）
CREATE TABLE IF NOT EXISTS fin_billing_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  billing_id BIGINT NOT NULL COMMENT '账单ID',
  billing_no VARCHAR(32) NOT NULL COMMENT '账单编号',
  record_type VARCHAR(20) NOT NULL COMMENT '记录类型',
  item_name VARCHAR(100) NOT NULL COMMENT '项目名称',
  item_description VARCHAR(500) COMMENT '项目描述',
  quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00 COMMENT '数量',
  unit_price DECIMAL(12,2) NOT NULL COMMENT '单价',
  amount DECIMAL(12,2) NOT NULL COMMENT '金额',
  discount_rate DECIMAL(5,2) DEFAULT 0.00 COMMENT '折扣率',
  discount_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '折扣金额',
  actual_amount DECIMAL(12,2) NOT NULL COMMENT '实际金额',
  tax_rate DECIMAL(5,2) DEFAULT 0.00 COMMENT '税率',
  tax_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '税额',
  service_date DATETIME COMMENT '服务日期',
  service_provider_id BIGINT COMMENT '服务提供者ID',
  service_provider_name VARCHAR(100) COMMENT '服务提供者名称',
  case_id BIGINT COMMENT '案件ID',
  contract_id BIGINT COMMENT '合同ID',
  item_status VARCHAR(20) COMMENT '项目状态',
  sort_order INTEGER DEFAULT 0 COMMENT '排序号',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  KEY idx_billing_id (billing_id),
  KEY idx_record_type (record_type),
  KEY idx_case_id (case_id),
  KEY idx_contract_id (contract_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账单记录表';

-- fin_payment_plan表（付款计划表）
CREATE TABLE IF NOT EXISTS fin_payment_plan (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  plan_no VARCHAR(32) NOT NULL COMMENT '计划编号',
  plan_name VARCHAR(100) NOT NULL COMMENT '计划名称',
  plan_type VARCHAR(20) NOT NULL COMMENT '计划类型',
  plan_status VARCHAR(20) NOT NULL COMMENT '计划状态',
  contract_id BIGINT COMMENT '合同ID',
  contract_no VARCHAR(32) COMMENT '合同编号',
  client_id BIGINT NOT NULL COMMENT '客户ID',
  total_amount DECIMAL(12,2) NOT NULL COMMENT '总金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  installment_count INTEGER DEFAULT 1 COMMENT '分期次数',
  start_date DATETIME COMMENT '开始日期',
  end_date DATETIME COMMENT '结束日期',
  first_payment_date DATETIME COMMENT '首次付款日期',
  first_payment_amount DECIMAL(12,2) COMMENT '首次付款金额',
  payment_cycle VARCHAR(20) COMMENT '付款周期',
  payment_day INTEGER COMMENT '付款日',
  reminder_days INTEGER DEFAULT 0 COMMENT '提前提醒天数',
  auto_reminder BOOLEAN DEFAULT FALSE COMMENT '是否自动提醒',
  auto_billing BOOLEAN DEFAULT FALSE COMMENT '是否自动生成账单',
  department_id BIGINT COMMENT '部门ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_plan_no (plan_no),
  KEY idx_plan_type (plan_type),
  KEY idx_plan_status (plan_status),
  KEY idx_contract_id (contract_id),
  KEY idx_client_id (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='付款计划表';

-- fin_income表（收入表）
CREATE TABLE IF NOT EXISTS fin_income (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  income_no VARCHAR(32) NOT NULL COMMENT '收入编号',
  income_type VARCHAR(20) NOT NULL COMMENT '收入类型',
  income_category VARCHAR(50) COMMENT '收入类别',
  amount DECIMAL(12,2) NOT NULL COMMENT '收入金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  income_date DATETIME NOT NULL COMMENT '收入日期',
  income_status VARCHAR(20) NOT NULL COMMENT '收入状态',
  account_id BIGINT COMMENT '入账账户ID',
  transaction_id BIGINT COMMENT '关联交易ID',
  source_type VARCHAR(20) COMMENT '来源类型',
  source_id BIGINT COMMENT '来源ID',
  contract_id BIGINT COMMENT '合同ID',
  case_id BIGINT COMMENT '案件ID',
  client_id BIGINT COMMENT '客户ID',
  invoice_id BIGINT COMMENT '发票ID',
  is_taxable BOOLEAN DEFAULT FALSE COMMENT '是否需要纳税',
  tax_rate DECIMAL(5,2) DEFAULT 0.00 COMMENT '税率',
  tax_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '税额',
  description VARCHAR(500) COMMENT '收入描述',
  department_id BIGINT COMMENT '部门ID',
  cost_center_id BIGINT COMMENT '成本中心ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_income_no (income_no),
  KEY idx_income_type (income_type),
  KEY idx_income_date (income_date),
  KEY idx_client_id (client_id),
  KEY idx_contract_id (contract_id),
  KEY idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='收入表';

-- fin_expense表（支出表）
CREATE TABLE IF NOT EXISTS fin_expense (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  expense_no VARCHAR(32) NOT NULL COMMENT '支出编号',
  expense_type VARCHAR(20) NOT NULL COMMENT '支出类型',
  expense_category VARCHAR(50) COMMENT '支出类别',
  amount DECIMAL(12,2) NOT NULL COMMENT '支出金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  expense_date DATETIME NOT NULL COMMENT '支出日期',
  expense_status VARCHAR(20) NOT NULL COMMENT '支出状态',
  account_id BIGINT COMMENT '支出账户ID',
  transaction_id BIGINT COMMENT '关联交易ID',
  payee_name VARCHAR(100) COMMENT '收款方名称',
  payee_account VARCHAR(50) COMMENT '收款方账号',
  payee_bank VARCHAR(100) COMMENT '收款方银行',
  purpose VARCHAR(200) COMMENT '用途',
  is_reimbursable BOOLEAN DEFAULT FALSE COMMENT '是否可报销',
  reimbursement_status VARCHAR(20) COMMENT '报销状态',
  is_deductible BOOLEAN DEFAULT FALSE COMMENT '是否可抵扣',
  contract_id BIGINT COMMENT '合同ID',
  case_id BIGINT COMMENT '案件ID',
  invoice_id BIGINT COMMENT '发票ID',
  approval_status VARCHAR(20) COMMENT '审批状态',
  approver_id BIGINT COMMENT '审批人ID',
  approval_time DATETIME COMMENT '审批时间',
  department_id BIGINT COMMENT '部门ID',
  cost_center_id BIGINT COMMENT '成本中心ID',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_expense_no (expense_no),
  KEY idx_expense_type (expense_type),
  KEY idx_expense_date (expense_date),
  KEY idx_contract_id (contract_id),
  KEY idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支出表';

-- fin_budget表（预算表）
CREATE TABLE IF NOT EXISTS fin_budget (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  budget_no VARCHAR(32) NOT NULL COMMENT '预算编号',
  budget_name VARCHAR(100) NOT NULL COMMENT '预算名称',
  budget_type VARCHAR(20) NOT NULL COMMENT '预算类型',
  budget_status VARCHAR(20) NOT NULL COMMENT '预算状态',
  budget_period VARCHAR(20) NOT NULL COMMENT '预算期间',
  start_date DATETIME NOT NULL COMMENT '开始日期',
  end_date DATETIME NOT NULL COMMENT '结束日期',
  total_amount DECIMAL(12,2) NOT NULL COMMENT '预算总金额',
  used_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '已用金额',
  remaining_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '剩余金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  department_id BIGINT COMMENT '部门ID',
  cost_center_id BIGINT COMMENT '成本中心ID',
  creator_id BIGINT COMMENT '创建人ID',
  approver_id BIGINT COMMENT '审批人ID',
  approval_time DATETIME COMMENT '审批时间',
  approval_status VARCHAR(20) COMMENT '审批状态',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_budget_no (budget_no),
  KEY idx_budget_type (budget_type),
  KEY idx_budget_status (budget_status),
  KEY idx_department_id (department_id),
  KEY idx_cost_center_id (cost_center_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预算表';

-- fin_cost_center表（成本中心表）
CREATE TABLE IF NOT EXISTS fin_cost_center (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  cost_center_code VARCHAR(32) NOT NULL COMMENT '成本中心编码',
  cost_center_name VARCHAR(100) NOT NULL COMMENT '成本中心名称',
  parent_id BIGINT COMMENT '父级ID',
  level INTEGER DEFAULT 1 COMMENT '层级',
  manager_id BIGINT COMMENT '负责人ID',
  manager_name VARCHAR(50) COMMENT '负责人姓名',
  department_id BIGINT COMMENT '部门ID',
  department_name VARCHAR(50) COMMENT '部门名称',
  description VARCHAR(500) COMMENT '描述',
  path VARCHAR(255) COMMENT '路径',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_cost_center_code (cost_center_code),
  KEY idx_parent_id (parent_id),
  KEY idx_department_id (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成本中心表';

-- fin_financial_report表（财务报表表）
CREATE TABLE IF NOT EXISTS fin_financial_report (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  report_no VARCHAR(32) NOT NULL COMMENT '报表编号',
  report_name VARCHAR(100) NOT NULL COMMENT '报表名称',
  report_type VARCHAR(20) NOT NULL COMMENT '报表类型',
  report_period VARCHAR(20) NOT NULL COMMENT '报表周期',
  start_date DATETIME NOT NULL COMMENT '开始日期',
  end_date DATETIME NOT NULL COMMENT '结束日期',
  report_status VARCHAR(20) NOT NULL COMMENT '报表状态',
  generate_time DATETIME COMMENT '生成时间',
  report_content TEXT COMMENT '报表内容',
  report_format VARCHAR(20) DEFAULT 'JSON' COMMENT '报表格式',
  report_path VARCHAR(255) COMMENT '报表路径',
  creator_id BIGINT COMMENT '创建人ID',
  creator_name VARCHAR(50) COMMENT '创建人姓名',
  department_id BIGINT COMMENT '部门ID',
  is_archived BOOLEAN DEFAULT FALSE COMMENT '是否归档',
  archive_time DATETIME COMMENT '归档时间',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_report_no (report_no),
  KEY idx_report_type (report_type),
  KEY idx_report_period (report_period),
  KEY idx_start_date (start_date),
  KEY idx_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务报表表';

-- fin_fee表（费用表）
CREATE TABLE IF NOT EXISTS fin_fee (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  fee_no VARCHAR(32) NOT NULL COMMENT '费用编号',
  fee_name VARCHAR(100) NOT NULL COMMENT '费用名称',
  fee_type VARCHAR(20) NOT NULL COMMENT '费用类型',
  fee_category VARCHAR(50) COMMENT '费用类别',
  fee_amount DECIMAL(12,2) NOT NULL COMMENT '费用金额',
  currency VARCHAR(10) NOT NULL COMMENT '币种',
  fee_date DATETIME NOT NULL COMMENT '费用日期',
  fee_status INTEGER NOT NULL COMMENT '费用状态',
  business_id BIGINT COMMENT '关联业务ID',
  business_type VARCHAR(50) COMMENT '关联业务类型',
  contract_id BIGINT COMMENT '合同ID',
  case_id BIGINT COMMENT '案件ID',
  client_id BIGINT COMMENT '客户ID',
  department_id BIGINT COMMENT '部门ID',
  cost_center_id BIGINT COMMENT '成本中心ID',
  is_billable BOOLEAN DEFAULT TRUE COMMENT '是否可计费',
  is_billed BOOLEAN DEFAULT FALSE COMMENT '是否已计费',
  billing_id BIGINT COMMENT '账单ID',
  approval_status VARCHAR(20) COMMENT '审批状态',
  approver_id BIGINT COMMENT '审批人ID',
  approval_time DATETIME COMMENT '审批时间',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(500) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_fee_no (fee_no),
  KEY idx_fee_type (fee_type),
  KEY idx_fee_date (fee_date),
  KEY idx_business_id (business_id),
  KEY idx_contract_id (contract_id),
  KEY idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='费用表';

-- fin_fee_relation表（费用关联表）
CREATE TABLE IF NOT EXISTS fin_fee_relation (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tenant_id BIGINT COMMENT '租户ID',
  tenant_code VARCHAR(50) COMMENT '租户编码',
  finance_fee_id BIGINT NOT NULL COMMENT '财务费用ID',
  source_type VARCHAR(20) NOT NULL COMMENT '来源类型（CONTRACT-合同费用，CASE-案件费用）',
  source_id BIGINT NOT NULL COMMENT '来源ID（合同费用ID或案件费用ID）',
  contract_id BIGINT COMMENT '关联合同ID',
  contract_number VARCHAR(50) COMMENT '关联合同编号',
  case_id BIGINT COMMENT '关联案件ID',
  case_number VARCHAR(50) COMMENT '关联案件编号',
  relation_type VARCHAR(50) COMMENT '关联类型',
  remarks VARCHAR(500) COMMENT '备注',
  version INTEGER DEFAULT 0 COMMENT '版本号',
  sort INTEGER DEFAULT 0 COMMENT '排序号',
  status INTEGER DEFAULT 0 COMMENT '状态（0-正常，1-禁用）',
  deleted INTEGER DEFAULT 0 COMMENT '删除标记（0-正常，1-删除）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(50) COMMENT '创建人',
  update_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  update_by VARCHAR(50) COMMENT '更新人',
  remark VARCHAR(255) COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_finance_fee_id (finance_fee_id),
  KEY idx_source (source_type, source_id),
  KEY idx_contract_id (contract_id),
  KEY idx_case_id (case_id),
  KEY idx_source_id (source_id),
  KEY idx_finance_fee_source (finance_fee_id, source_type, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='费用关联表';

-- 恢复外键约束
SET FOREIGN_KEY_CHECKS = 1;
