-- 案件基本信息表
CREATE TABLE IF NOT EXISTS case_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_number VARCHAR(64) NOT NULL COMMENT '案件编号',
    case_name VARCHAR(255) NOT NULL COMMENT '案件名称',
    case_description TEXT COMMENT '案件描述',
    case_type INT NOT NULL COMMENT '案件类型',
    case_status INT NOT NULL COMMENT '案件状态',
    case_progress INT COMMENT '案件进展',
    case_stage INT COMMENT '案件阶段',
    case_difficulty INT COMMENT '案件难度',
    case_importance INT COMMENT '案件重要性',
    case_priority INT COMMENT '案件优先级',
    case_source INT COMMENT '案件来源',
    handle_type INT COMMENT '办理方式',
    fee_type INT COMMENT '收费类型',
    estimated_amount DECIMAL(12,2) COMMENT '预估金额',
    actual_amount DECIMAL(12,2) COMMENT '实际金额',
    client_id BIGINT COMMENT '委托人ID',
    client_name VARCHAR(100) COMMENT '委托人名称',
    opposing_party VARCHAR(255) COMMENT '对方当事人',
    lawyer_id BIGINT COMMENT '主办律师ID',
    lawyer_name VARCHAR(50) COMMENT '主办律师姓名',
    department_id BIGINT COMMENT '部门ID',
    department_name VARCHAR(100) COMMENT '部门名称',
    court_name VARCHAR(100) COMMENT '法院/仲裁机构',
    judge_name VARCHAR(50) COMMENT '法官/仲裁员',
    court_case_number VARCHAR(100) COMMENT '案号',
    filing_time DATE COMMENT '立案时间',
    closing_time DATE COMMENT '结案时间',
    expected_closing_time DATE COMMENT '预计结案时间',
    case_result INT COMMENT '案件结果',
    case_tags VARCHAR(255) COMMENT '案件标签',
    has_conflict BOOLEAN DEFAULT FALSE COMMENT '是否有利益冲突',
    conflict_description TEXT COMMENT '冲突说明',
    is_confidential BOOLEAN DEFAULT FALSE COMMENT '是否需要保密',
    confidential_level INT COMMENT '保密级别',
    remarks TEXT COMMENT '备注',
    last_operator_id BIGINT COMMENT '最后操作人ID',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    UNIQUE INDEX uk_case_number (case_number, tenant_id),
    INDEX idx_case_status (case_status),
    INDEX idx_lawyer_id (lawyer_id),
    INDEX idx_client_id (client_id),
    INDEX idx_filing_time (filing_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件基本信息表';

-- 案件团队表
CREATE TABLE IF NOT EXISTS case_team (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    team_name VARCHAR(100) COMMENT '团队名称',
    team_leader_id BIGINT COMMENT '团队负责人ID',
    team_leader_name VARCHAR(50) COMMENT '团队负责人姓名',
    department_id BIGINT COMMENT '部门ID',
    department_name VARCHAR(100) COMMENT '部门名称',
    team_status INT COMMENT '团队状态',
    description TEXT COMMENT '团队描述',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件团队表';

-- 案件参与方表
CREATE TABLE IF NOT EXISTS case_participant (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    participant_type INT NOT NULL COMMENT '参与方类型',
    participant_id BIGINT COMMENT '参与方ID',
    participant_name VARCHAR(100) NOT NULL COMMENT '参与方名称',
    role_type INT COMMENT '角色类型',
    role_desc VARCHAR(255) COMMENT '角色描述',
    contact_person VARCHAR(50) COMMENT '联系人',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    contact_email VARCHAR(100) COMMENT '联系邮箱',
    address VARCHAR(255) COMMENT '地址',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_participant_type (participant_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件参与方表';

-- 案件任务分配表
CREATE TABLE IF NOT EXISTS case_assignment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    team_id BIGINT COMMENT '团队ID',
    assignment_type INT NOT NULL COMMENT '分配类型',
    assignee_id BIGINT NOT NULL COMMENT '受理人ID',
    assignee_name VARCHAR(50) NOT NULL COMMENT '受理人姓名',
    assigner_id BIGINT NOT NULL COMMENT '分配人ID',
    assigner_name VARCHAR(50) NOT NULL COMMENT '分配人姓名',
    assignment_content TEXT COMMENT '分配内容',
    start_time DATETIME COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    estimated_hours DECIMAL(10,2) COMMENT '预计工时',
    actual_hours DECIMAL(10,2) COMMENT '实际工时',
    priority INT COMMENT '优先级',
    status INT NOT NULL COMMENT '状态',
    complete_percent INT DEFAULT 0 COMMENT '完成百分比',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_assignee_id (assignee_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件任务分配表';

-- 案件文档表
CREATE TABLE IF NOT EXISTS case_document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    document_name VARCHAR(255) NOT NULL COMMENT '文档名称',
    document_type VARCHAR(50) COMMENT '文档类型',
    document_category INT COMMENT '文档分类',
    file_size BIGINT COMMENT '文件大小(字节)',
    file_format VARCHAR(20) COMMENT '文件格式',
    storage_path VARCHAR(500) NOT NULL COMMENT '存储路径',
    version VARCHAR(20) COMMENT '版本号',
    is_final BOOLEAN DEFAULT FALSE COMMENT '是否为最终版',
    confidential_level INT COMMENT '保密级别',
    upload_user_id BIGINT COMMENT '上传用户ID',
    upload_user_name VARCHAR(50) COMMENT '上传用户姓名',
    upload_time DATETIME COMMENT '上传时间',
    description TEXT COMMENT '文档描述',
    keywords VARCHAR(255) COMMENT '关键词',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_document_type (document_type),
    INDEX idx_document_category (document_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件文档表'; 