-- 初始化案件状态变更记录表
CREATE TABLE IF NOT EXISTS case_status_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    case_number VARCHAR(64) COMMENT '案件编号',
    old_status INT COMMENT '原状态',
    new_status INT NOT NULL COMMENT '新状态',
    change_reason TEXT COMMENT '变更原因',
    operator_id BIGINT NOT NULL COMMENT '操作人ID',
    operator_name VARCHAR(50) NOT NULL COMMENT '操作人姓名',
    operation_time DATETIME NOT NULL COMMENT '操作时间',
    ip_address VARCHAR(50) COMMENT 'IP地址',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_operator_id (operator_id),
    INDEX idx_operation_time (operation_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件状态变更记录表';

-- 初始化案件事件表
CREATE TABLE IF NOT EXISTS case_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    event_title VARCHAR(255) NOT NULL COMMENT '事件标题',
    event_content TEXT COMMENT '事件内容',
    event_type INT NOT NULL COMMENT '事件类型',
    event_time DATETIME NOT NULL COMMENT '事件时间',
    location VARCHAR(255) COMMENT '事件地点',
    event_duration INT COMMENT '事件时长(分钟)',
    related_people VARCHAR(500) COMMENT '相关人员',
    importance INT COMMENT '重要程度',
    status INT NOT NULL COMMENT '事件状态',
    remind_time DATETIME COMMENT '提醒时间',
    is_reminded BOOLEAN DEFAULT FALSE COMMENT '是否已提醒',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_event_time (event_time),
    INDEX idx_event_type (event_type),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件事件表';

-- 初始化案件笔记表
CREATE TABLE IF NOT EXISTS case_note (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    note_title VARCHAR(255) NOT NULL COMMENT '笔记标题',
    note_content TEXT COMMENT '笔记内容',
    note_type INT COMMENT '笔记类型',
    note_time DATETIME NOT NULL COMMENT '记录时间',
    tags VARCHAR(255) COMMENT '标签',
    visibility INT COMMENT '可见性',
    importance INT COMMENT '重要程度',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_note_type (note_type),
    INDEX idx_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件笔记表';

-- 初始化案件费用表
CREATE TABLE IF NOT EXISTS case_fee (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    fee_name VARCHAR(255) NOT NULL COMMENT '费用名称',
    fee_type INT NOT NULL COMMENT '费用类型',
    fee_amount DECIMAL(12,2) NOT NULL COMMENT '费用金额',
    fee_status INT NOT NULL COMMENT '费用状态',
    fee_date DATE NOT NULL COMMENT '费用日期',
    payee VARCHAR(100) COMMENT '收款方',
    payer VARCHAR(100) COMMENT '付款方',
    payment_method INT COMMENT '支付方式',
    payment_time DATETIME COMMENT '支付时间',
    description TEXT COMMENT '费用说明',
    invoice_no VARCHAR(100) COMMENT '发票号',
    has_invoice BOOLEAN DEFAULT FALSE COMMENT '是否有发票',
    invoice_title VARCHAR(200) COMMENT '发票抬头',
    invoice_type INT COMMENT '发票类型',
    tax_number VARCHAR(50) COMMENT '税号',
    bank_account VARCHAR(100) COMMENT '银行账号',
    bank_name VARCHAR(100) COMMENT '开户行',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_fee_type (fee_type),
    INDEX idx_fee_status (fee_status),
    INDEX idx_fee_date (fee_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件费用表';

-- 初始化案件任务表
CREATE TABLE IF NOT EXISTS case_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_id BIGINT NOT NULL COMMENT '案件ID',
    task_name VARCHAR(255) NOT NULL COMMENT '任务名称',
    task_description TEXT COMMENT '任务描述',
    task_type INT COMMENT '任务类型',
    task_status INT NOT NULL COMMENT '任务状态',
    priority INT COMMENT '优先级',
    assignee_id BIGINT COMMENT '负责人ID',
    assignee_name VARCHAR(50) COMMENT '负责人姓名',
    start_time DATETIME COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    deadline DATETIME COMMENT '截止时间',
    estimated_hours DECIMAL(10,2) COMMENT '预计工时',
    actual_hours DECIMAL(10,2) COMMENT '实际工时',
    complete_percent INT DEFAULT 0 COMMENT '完成百分比',
    parent_task_id BIGINT COMMENT '父任务ID',
    remarks TEXT COMMENT '备注',
    created_by BIGINT NOT NULL COMMENT '创建人',
    created_time DATETIME NOT NULL COMMENT '创建时间',
    updated_by BIGINT COMMENT '更新人',
    updated_time DATETIME COMMENT '更新时间',
    deleted BOOLEAN DEFAULT FALSE COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    INDEX idx_case_id (case_id),
    INDEX idx_task_status (task_status),
    INDEX idx_assignee_id (assignee_id),
    INDEX idx_deadline (deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件任务表'; 