-- 创建案件基本信息表
CREATE TABLE IF NOT EXISTS case_info (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  case_number varchar(50) NOT NULL COMMENT '案件编号',
  case_name varchar(100) NOT NULL COMMENT '案件名称',
  case_description varchar(500) DEFAULT NULL COMMENT '案件描述',
  case_type int DEFAULT NULL COMMENT '案件类型',
  case_status int DEFAULT NULL COMMENT '案件状态',
  case_progress int DEFAULT NULL COMMENT '案件进展',
  case_stage int DEFAULT NULL COMMENT '案件阶段',
  case_difficulty int DEFAULT NULL COMMENT '案件难度',
  case_importance int DEFAULT NULL COMMENT '案件重要性',
  case_priority int DEFAULT NULL COMMENT '案件优先级',
  case_source int DEFAULT NULL COMMENT '案件来源',
  handle_type int DEFAULT NULL COMMENT '办理方式',
  fee_type int DEFAULT NULL COMMENT '收费类型',
  estimated_amount decimal(15,2) DEFAULT NULL COMMENT '预估金额',
  actual_amount decimal(15,2) DEFAULT NULL COMMENT '实际金额',
  client_id bigint DEFAULT NULL COMMENT '委托人ID',
  client_name varchar(100) DEFAULT NULL COMMENT '委托人名称',
  opposing_party varchar(100) DEFAULT NULL COMMENT '对方当事人',
  lawyer_id bigint DEFAULT NULL COMMENT '主办律师ID',
  lawyer_name varchar(50) DEFAULT NULL COMMENT '主办律师姓名',
  department_id bigint DEFAULT NULL COMMENT '部门ID',
  department_name varchar(50) DEFAULT NULL COMMENT '部门名称',
  court_name varchar(100) DEFAULT NULL COMMENT '法院/仲裁机构',
  judge_name varchar(50) DEFAULT NULL COMMENT '法官/仲裁员',
  court_case_number varchar(50) DEFAULT NULL COMMENT '案号',
  filing_time date DEFAULT NULL COMMENT '立案时间',
  closing_time date DEFAULT NULL COMMENT '结案时间',
  expected_closing_time date DEFAULT NULL COMMENT '预计结案时间',
  case_result int DEFAULT NULL COMMENT '案件结果',
  case_tags varchar(255) DEFAULT NULL COMMENT '案件标签，多个标签以逗号分隔',
  has_conflict tinyint DEFAULT '0' COMMENT '是否有利益冲突',
  conflict_description varchar(500) DEFAULT NULL COMMENT '冲突说明',
  is_confidential tinyint DEFAULT '0' COMMENT '是否需要保密',
  confidential_level int DEFAULT NULL COMMENT '保密级别',
  remarks varchar(500) DEFAULT NULL COMMENT '备注',
  last_operation_time datetime DEFAULT NULL COMMENT '最后操作时间',
  last_operator_id bigint DEFAULT NULL COMMENT '最后操作人ID',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  version int DEFAULT '0' COMMENT '版本号',
  sort int DEFAULT '0' COMMENT '排序',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (id),
  UNIQUE KEY uk_case_number (case_number,tenant_id,deleted),
  KEY idx_client_id (client_id),
  KEY idx_lawyer_id (lawyer_id),
  KEY idx_case_status (case_status),
  KEY idx_filing_time (filing_time),
  KEY idx_closing_time (closing_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件基本信息表';

-- 创建案件团队表
CREATE TABLE IF NOT EXISTS case_team (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  case_id bigint NOT NULL COMMENT '案件ID',
  team_name varchar(50) NOT NULL COMMENT '团队名称',
  lead_lawyer_id bigint DEFAULT NULL COMMENT '团队负责人ID',
  lead_lawyer_name varchar(50) DEFAULT NULL COMMENT '团队负责人姓名',
  team_status int DEFAULT '1' COMMENT '团队状态',
  description varchar(500) DEFAULT NULL COMMENT '团队描述',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  version int DEFAULT '0' COMMENT '版本号',
  sort int DEFAULT '0' COMMENT '排序',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件团队表';

-- 创建案件团队成员表
CREATE TABLE IF NOT EXISTS case_team_member (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  team_id bigint NOT NULL COMMENT '团队ID',
  case_id bigint NOT NULL COMMENT '案件ID',
  user_id bigint NOT NULL COMMENT '用户ID',
  user_name varchar(50) DEFAULT NULL COMMENT '用户姓名',
  role_type varchar(30) DEFAULT NULL COMMENT '角色类型(LEAD_LAWYER,LAWYER,TRAINEE,ASSISTANT)',
  role_name varchar(50) DEFAULT NULL COMMENT '角色名称',
  assign_time datetime DEFAULT NULL COMMENT '分配时间',
  dismiss_time datetime DEFAULT NULL COMMENT '解除时间',
  status int DEFAULT '1' COMMENT '状态',
  remarks varchar(255) DEFAULT NULL COMMENT '备注',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  version int DEFAULT '0' COMMENT '版本号',
  sort int DEFAULT '0' COMMENT '排序',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (id),
  KEY idx_team_id (team_id),
  KEY idx_case_id (case_id),
  KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件团队成员表';

-- 创建案件当事人表
CREATE TABLE IF NOT EXISTS case_party (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  case_id bigint NOT NULL COMMENT '案件ID',
  party_type varchar(30) NOT NULL COMMENT '当事人类型(PLAINTIFF,DEFENDANT,THIRD_PARTY)',
  party_name varchar(100) NOT NULL COMMENT '当事人名称',
  party_identity varchar(50) DEFAULT NULL COMMENT '当事人身份',
  identity_number varchar(50) DEFAULT NULL COMMENT '证件号码',
  contact_person varchar(50) DEFAULT NULL COMMENT '联系人',
  contact_phone varchar(20) DEFAULT NULL COMMENT '联系电话',
  address varchar(255) DEFAULT NULL COMMENT '地址',
  email varchar(100) DEFAULT NULL COMMENT '邮箱',
  remarks varchar(500) DEFAULT NULL COMMENT '备注',
  tenant_id bigint NOT NULL COMMENT '租户ID',
  tenant_code varchar(50) DEFAULT NULL COMMENT '租户编码',
  version int DEFAULT '0' COMMENT '版本号',
  sort int DEFAULT '0' COMMENT '排序',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by varchar(50) DEFAULT NULL COMMENT '创建者',
  update_by varchar(50) DEFAULT NULL COMMENT '更新者',
  deleted tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
  PRIMARY KEY (id),
  KEY idx_case_id (case_id),
  KEY idx_party_type (party_type),
  KEY idx_party_name (party_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件当事人表'; 