elasticsearch:
  cluster:
    name: ${ES_CLUSTER_NAME:law-firm-cluster}
    nodes: 
      - host: localhost
        port: 9200
        scheme: http
      - ${ES_NODE:localhost:9200}
  client:
    connect-timeout: ${ES_CONNECT_TIMEOUT:5000}
    socket-timeout: ${ES_SOCKET_TIMEOUT:60000}
    max-retries: ${ES_MAX_RETRIES:3}
  index:
    number-of-shards: ${ES_NUMBER_OF_SHARDS:3}
    number-of-replicas: ${ES_NUMBER_OF_REPLICAS:1}

logging:
  level:
    com.lawfirm.core.search: ${LOG_LEVEL:DEBUG}
    org.elasticsearch: INFO 