# 搜索模块配置

# Elasticsearch配置
elasticsearch:
  cluster:
    name: ${ES_CLUSTER_NAME:law-firm-cluster}
    nodes: 
      - host: ${ES_HOST:localhost}
        port: ${ES_PORT:9200}
        scheme: ${ES_SCHEME:http}
      - ${ES_NODE:localhost:9200}
  client:
    connect-timeout: ${ES_CONNECT_TIMEOUT:5000}
    socket-timeout: ${ES_SOCKET_TIMEOUT:60000}
    max-retries: ${ES_MAX_RETRIES:3}
  index:
    number-of-shards: ${ES_NUMBER_OF_SHARDS:3}
    number-of-replicas: ${ES_NUMBER_OF_REPLICAS:1}

# 索引配置
search:
  index:
    case:
      name: ${SEARCH_INDEX_CASE:law_firm_case}
      refresh-interval: ${SEARCH_INDEX_CASE_REFRESH:30s}
    document:
      name: ${SEARCH_INDEX_DOCUMENT:law_firm_document}
      refresh-interval: ${SEARCH_INDEX_DOCUMENT_REFRESH:1m}
    client:
      name: ${SEARCH_INDEX_CLIENT:law_firm_client}
      refresh-interval: ${SEARCH_INDEX_CLIENT_REFRESH:1m}
    contract:
      name: ${SEARCH_INDEX_CONTRACT:law_firm_contract}
      refresh-interval: ${SEARCH_INDEX_CONTRACT_REFRESH:1m}

# 日志配置
logging:
  level:
    com.lawfirm.core.search: ${LOG_LEVEL_SEARCH:DEBUG}
    org.elasticsearch: ${LOG_LEVEL_ELASTICSEARCH:INFO} 